const fs = require('fs');

const materials = [
  {
    name: "Hydroxyapatite (HAP)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "25.8, 40\n31.8, 100\n32.2, 60\n32.9, 55\n39.8, 20\n49.5, 30",
    description: "A naturally occurring mineral form of calcium apatite. It is the main inorganic constituent of tooth enamel and bone, extensively used for bone grafts and dental implants.",
    formula: "Ca10(PO4)6(OH)2",
    elements: ["Ca", "P", "O", "H"],
    crystalSystem: "Hexagonal",
    spaceGroup: "P63/m",
    density: 3.16,
    applications: ["Bone Grafts", "Dental Implants", "Orthopedics"],
  },
  {
    name: "Beta-Tricalcium Phosphate (B-TCP)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "25.8, 20\n27.8, 80\n31.0, 100\n34.3, 50\n47.1, 40",
    description: "A highly resorbable bioceramic widely used in synthetic bone void fillers. It is gradually replaced by natural bone after implantation.",
    formula: "Ca3(PO4)2",
    elements: ["Ca", "P", "O"],
    crystalSystem: "Rhombohedral",
    spaceGroup: "R-3c",
    density: 3.07,
    applications: ["Bone Void Fillers", "Tissue Engineering", "Drug Delivery"],
  },
  {
    name: "Alpha-Tricalcium Phosphate (A-TCP)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "22.8, 40\n24.1, 50\n29.1, 80\n30.7, 100\n31.3, 70",
    description: "A high-temperature polymorph of TCP, significantly more soluble than the beta phase. Used widely as a reactive component in self-setting calcium phosphate cements.",
    formula: "Ca3(PO4)2",
    elements: ["Ca", "P", "O"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21/a",
    density: 2.86,
    applications: ["Bone Cements", "Biodegradable Ceramics"],
  },
  {
    name: "Fluorapatite",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "25.8, 40\n31.9, 100\n32.2, 50\n33.1, 60\n46.9, 30",
    description: "A highly stable, acid-resistant calcium phosphate mineral formed when fluoride ions replace hydroxyl groups in hydroxyapatite, famously enhancing tooth decay resistance.",
    formula: "Ca10(PO4)6F2",
    elements: ["Ca", "P", "O", "F"],
    crystalSystem: "Hexagonal",
    spaceGroup: "P63/m",
    density: 3.20,
    applications: ["Dental Enamel Remineralization", "Caries Prevention"],
  },
  {
    name: "Bioglass 45S5",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "22.5, 40\n29.1, 100\n33.8, 80\n48.3, 50",
    description: "A highly bioactive synthetic silica-based glass composition that bonds rapidly to hard and soft tissues. Exhibits characteristic amorphous broad halos combined with crystalline nucleated domains.",
    formula: "SiO2-Na2O-CaO-P2O5",
    elements: ["Si", "Na", "Ca", "P", "O"],
    crystalSystem: "Amorphous",
    spaceGroup: "P1",
    density: 2.70,
    applications: ["Bone Repair", "Dental Products", "Wound Healing"],
  },
  {
    name: "Zirconia (Tetragonal Y-TZP)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "30.2, 100\n34.6, 20\n35.3, 30\n50.2, 50\n59.8, 40",
    description: "Yttria-stabilized tetragonal zirconia polycrystal. A highly inert, extremely fracture-tough bioceramic utilized for robust dental crowns and joint arthroplasty components.",
    formula: "ZrO2",
    elements: ["Zr", "O", "Y"],
    crystalSystem: "Tetragonal",
    spaceGroup: "P42/nmc",
    density: 6.05,
    applications: ["Dental Crowns", "Hip Replacements", "Abutments"],
  },
  {
    name: "Alumina (Bio-Grade)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "25.6, 40\n35.1, 100\n37.8, 50\n43.3, 80\n52.5, 50\n57.5, 60",
    description: "High-purity sapphire-like aluminum oxide used in biomedicine due to its exceptional wear resistance and bioinert nature. Popular for femoral heads in total hip replacements.",
    formula: "Al2O3",
    elements: ["Al", "O"],
    crystalSystem: "Rhombohedral",
    spaceGroup: "R-3c",
    density: 3.97,
    applications: ["Femoral Heads", "Wear-Resistant Bearings", "Dental Implants"],
  },
  {
    name: "Titanium Dioxide (Rutile)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "27.4, 100\n36.1, 50\n41.2, 25\n54.3, 60\n56.6, 20",
    description: "A highly biocompatible and photochemically stable polymorph of TiO2. Often formed as a passivating surface oxide layer on medical-grade titanium implants.",
    formula: "TiO2",
    elements: ["Ti", "O"],
    crystalSystem: "Tetragonal",
    spaceGroup: "P42/mnm",
    density: 4.25,
    applications: ["Implant Coatings", "Photocatalytic Disinfection", "Pharmaceutical Excipient"],
  },
  {
    name: "Calcium Carbonate (Calcite)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "23.0, 20\n29.4, 100\n36.0, 15\n39.4, 30\n43.1, 20\n47.5, 25",
    description: "The most stable polymorph of calcium carbonate. Extensively used in pharmaceutical formulations as antacids and basic dietary calcium supplements.",
    formula: "CaCO3",
    elements: ["Ca", "C", "O"],
    crystalSystem: "Rhombohedral",
    spaceGroup: "R-3c",
    density: 2.71,
    applications: ["Dietary Supplements", "Antacids", "Bone Scaffolds"],
  },
  {
    name: "Carbonated Apatite (Dahllite)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "25.8, 30\n31.8, 100\n32.1, 50\n32.9, 45\n46.7, 25",
    description: "Biological apatite found in human bones and teeth, which features carbonate substitution replacing phosphate or hydroxyl groups, making it more soluble than pure HAP.",
    formula: "Ca10(PO4,CO3)6(OH,CO3)2",
    elements: ["Ca", "P", "C", "O", "H"],
    crystalSystem: "Hexagonal",
    spaceGroup: "P63/m",
    density: 3.10,
    applications: ["Biomimetic Scaffolds", "Hard Tissue Analogues"],
  },
  {
    name: "Barium Sulfate",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "20.5, 40\n25.8, 60\n26.8, 100\n28.7, 50\n31.5, 45\n42.6, 50",
    description: "A dense, completely radiopaque inorganic compound used frequently as an X-ray contrast agent for gastrointestinal tract clinical imaging.",
    formula: "BaSO4",
    elements: ["Ba", "S", "O"],
    crystalSystem: "Orthorhombic",
    spaceGroup: "Pnma",
    density: 4.50,
    applications: ["X-Ray Contrast Media", "Radiopaque Bone Cements"],
  },
  {
    name: "Magnesium Hydroxide (Brucite)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "18.6, 100\n32.8, 40\n37.9, 60\n50.8, 50\n58.6, 30",
    description: "The main functional ingredient in Milk of Magnesia. Medically utilized as a gentle antacid and osmotic laxative.",
    formula: "Mg(OH)2",
    elements: ["Mg", "O", "H"],
    crystalSystem: "Hexagonal",
    spaceGroup: "P-3m1",
    density: 2.39,
    applications: ["Antacids", "Laxatives", "Burn Treatments"],
  },
  {
    name: "Silver Sulfadiazine",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "10.2, 100\n11.9, 80\n20.4, 50\n25.1, 60\n28.8, 40",
    description: "A topical sulfonamide antibacterial agent complexed with silver. Heavily utilized in clinical settings to prevent burn wound infections.",
    formula: "C10H9AgN4O2S",
    elements: ["C", "H", "Ag", "N", "O", "S"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21/c",
    density: 1.87,
    applications: ["Burn Wound Creams", "Topical Antibiotics"],
  },
  {
    name: "Zinc Oxide (Medical Grade)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "31.7, 60\n34.4, 45\n36.2, 100\n47.5, 25\n56.6, 35\n62.8, 30",
    description: "A vital multi-functional inorganic compound showing local astringent, soothing, and protective properties. It is a fundamental component of calamine lotion and sunscreens.",
    formula: "ZnO",
    elements: ["Zn", "O"],
    crystalSystem: "Hexagonal",
    spaceGroup: "P63mc",
    density: 5.61,
    applications: ["Dermatological Lotions", "Dental Cements", "Sunscreens"],
  },
  {
    name: "Poly(L-Lactic Acid) (PLLA)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "14.8, 50\n16.6, 100\n18.9, 80\n22.3, 40",
    description: "A semi-crystalline, highly biocompatible and biodegradable synthetic polymer used thoroughly in resorbable sutures, orthopedic pins, and soft tissue scaffolds.",
    formula: "(C3H4O2)n",
    elements: ["C", "H", "O"],
    crystalSystem: "Orthorhombic",
    spaceGroup: "P212121",
    density: 1.25,
    applications: ["Dissolvable Sutures", "Implants", "Dermal Fillers"],
  },
  {
    name: "Polyglycolic acid (PGA)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "21.6, 100\n28.8, 60\n32.1, 20",
    description: "The simplest linear aliphatic polyester, possessing high crystallinity and rapid degradation. Widely leveraged in early synthetic absorbable sutures.",
    formula: "(C2H2O2)n",
    elements: ["C", "H", "O"],
    crystalSystem: "Orthorhombic",
    spaceGroup: "Pc21n",
    density: 1.50,
    applications: ["Absorbable Sutures", "Bio-meshes", "Tissue Engineering"],
  },
  {
    name: "Ibuprofen (Form I)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "6.1, 50\n12.2, 60\n16.6, 100\n17.6, 40\n20.1, 70\n22.3, 80",
    description: "The stable, most commonly crystallized and marketed form of the pervasive non-steroidal anti-inflammatory drug (NSAID) Ibuprofen.",
    formula: "C13H18O2",
    elements: ["C", "H", "O"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21/c",
    density: 1.11,
    applications: ["Analgesics", "Anti-inflammatory Medication", "Antipyretics"],
  },
  {
    name: "Paracetamol (Acetaminophen Form I)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "12.1, 25\n15.5, 40\n18.1, 50\n23.4, 60\n24.3, 100\n26.5, 80",
    description: "The highly stable monoclinic polymorph and standard market formulation of the ubiquitous pain-relieving and fever-reducing medication.",
    formula: "C8H9NO2",
    elements: ["C", "H", "N", "O"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21/a",
    density: 1.29,
    applications: ["Pain Relief", "Fever Reduction", "Pharmaceutical Solid Dosage"],
  },
  {
    name: "Aspirin (Acetylsalicylic Acid Form I)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "7.8, 80\n15.6, 100\n20.5, 40\n22.6, 50\n26.8, 60",
    description: "A widely utilized medication to treat pain, fever, and inflammation, famously acting as an antiplatelet to reduce risks of heart attacks.",
    formula: "C9H8O4",
    elements: ["C", "H", "O"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21/c",
    density: 1.40,
    applications: ["Analgesics", "Cardiovascular Therapy", "Anti-inflammatory"],
  },
  {
    name: "Vitamin C (L-Ascorbic Acid)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "10.4, 60\n17.5, 100\n25.2, 80\n27.8, 50\n40.1, 25",
    description: "A strictly essential dietary vitamin acting as a potent antioxidant, playing a pivotal physiological role in collagen synthesis and immune responses.",
    formula: "C6H8O6",
    elements: ["C", "H", "O"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21",
    density: 1.65,
    applications: ["Dietary Supplements", "Scurvy Treatment", "Cosmetics"],
  },
  {
    name: "Bismuth Subsalicylate",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "9.2, 100\n15.4, 40\n27.6, 80\n31.8, 60\n40.5, 30",
    description: "A bismuth-based medication and generic antacid used meticulously to treat temporary discomforts of the stomach and gastrointestinal tract.",
    formula: "C7H5BiO4",
    elements: ["C", "H", "Bi", "O"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21/c",
    density: 3.55,
    applications: ["Antidiarrheals", "Antacids", "GI Tract Coating"],
  },
  {
    name: "Dicalcium Phosphate Dihydrate (Brushite)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "11.6, 100\n20.9, 80\n29.2, 50\n30.5, 40\n34.2, 60",
    description: "A natural calcium phosphate mineral highly biologically relevant as a precursor in bone mineralization and an active component in some specialized toothpastes.",
    formula: "CaHPO4.2H2O",
    elements: ["Ca", "P", "O", "H"],
    crystalSystem: "Monoclinic",
    spaceGroup: "Ia",
    density: 2.32,
    applications: ["Toothpastes", "Calcium Supplements", "Biocement Intermediates"],
  },
  {
    name: "Octacalcium Phosphate (OCP)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "4.7, 100\n9.4, 60\n26.0, 50\n31.5, 80\n32.0, 40",
    description: "A fascinating bioceramic believed to be a vital transient precursor phase in the complex biological mineralization cascade of human bones and teeth.",
    formula: "Ca8H2(PO4)6.5H2O",
    elements: ["Ca", "P", "O", "H"],
    crystalSystem: "Triclinic",
    spaceGroup: "P-1",
    density: 2.61,
    applications: ["Bone Substitutes", "Biomineralization Studies", "Tissue Coatings"],
  },
  {
    name: "Calcium Sulfate Hemihydrate (Plaster of Paris)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "14.7, 100\n25.6, 40\n29.7, 80\n31.9, 60",
    description: "An incredibly fast-setting clinical bioceramic historically ubiquitous for external orthopaedic casts and acting as a degradable internal bone void filler.",
    formula: "CaSO4.0.5H2O",
    elements: ["Ca", "S", "O", "H"],
    crystalSystem: "Monoclinic",
    spaceGroup: "C2",
    density: 2.73,
    applications: ["Orthopedic Casts", "Bone Graft Extenders", "Dental Plaster"],
  },
  {
    name: "Bacterial Cellulose (Type I)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "14.4, 80\n16.8, 60\n22.5, 100\n34.5, 20",
    description: "A remarkably pure nanofibrillar organic material synthesized by bacteria. Cultivated for severe wound dressings due to its soothing hydrophilic properties.",
    formula: "(C6H10O5)n",
    elements: ["C", "H", "O"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21",
    density: 1.58,
    applications: ["Artificial Skin", "Burn Dressings", "Microsurgery Scaffolds"],
  },
  {
    name: "Ciprofloxacin Hydrochloride (Monohydrate)",
    type: "Bioceramics, Biomaterials & Pharma",
    pattern: "8.2, 50\n10.8, 40\n15.6, 60\n19.2, 100\n26.5, 80\n29.4, 30",
    description: "A highly prescribed, broad-spectrum second-generation fluoroquinolone antibiotic targeting various severe bacterial infections.",
    formula: "C17H18FN3O3.HCl.H2O",
    elements: ["C", "H", "F", "N", "O", "Cl"],
    crystalSystem: "Monoclinic",
    spaceGroup: "P21/c",
    density: 1.44,
    applications: ["Antibiotics", "Infection Treatments", "Pharmaceutical Solid Dosage"],
  }
];

const dbPath = 'utils/materialDB.ts';
let code = fs.readFileSync(dbPath, 'utf8');

const lastBracketIndex = code.lastIndexOf('];');

if (lastBracketIndex !== -1) {
  const stringified = materials.map(m => {
    return `  {
    name: "${m.name}",
    type: "${m.type}",
    pattern: "${m.pattern.replace(/\n/g, '\\n')}",
    description: "${m.description}",
    formula: "${m.formula}",
    elements: ${JSON.stringify(m.elements)},
    crystalSystem: "${m.crystalSystem}",
    spaceGroup: "${m.spaceGroup}",
    density: ${m.density},
    applications: ${JSON.stringify(m.applications)},
  }`;
  }).join(',\n');
  
  const before = code.substring(0, lastBracketIndex);
  const after = code.substring(lastBracketIndex);
  
  const lastCharIsComma = before.trim().endsWith(',');
  
  const finalInserted = before + (lastCharIsComma ? "" : ",") + "\n" + stringified + "\n" + after;
  fs.writeFileSync(dbPath, finalInserted);
  console.log('Successfully inserted bioceramic materials');
} else {
  console.error("Could not find end of array '];'");
}
