import React from 'react';
import { 
  Terminal, 
  Copy, 
  Check, 
  FileText, 
  Code2, 
  Download,
  Share2
} from 'lucide-react';
import { LatticeParams, CrystalSystem, fmt } from './metricTensorTypes';

interface MetricTensorPythonTabProps {
  system: CrystalSystem;
  params: LatticeParams;
  metricG: number[][];
  metricGStar: number[][];
  matrixB: number[][];
  h1: number;
  k1: number;
  l1: number;
  copyToClipboard: (text: string, key: string) => void;
  copiedKey: string | null;
}

export const MetricTensorPythonTab: React.FC<MetricTensorPythonTabProps> = ({
  system,
  params,
  metricG,
  metricGStar,
  matrixB,
  h1,
  k1,
  l1,
  copyToClipboard,
  copiedKey
}) => {
  const pythonScript = `"""
Crystallographic Metric Tensor Algebra Script
Generated by XRD Calc Pro
Crystal System: ${system}
Lattice Parameters: a=${params.a} Å, b=${params.b} Å, c=${params.c} Å, α=${params.alpha}°, β=${params.beta}°, γ=${params.gamma}°
"""

import numpy as np

# 1. Direct Metric Tensor G
G = np.array(${JSON.stringify(metricG)}, dtype=np.float64)

# 2. Cell Volume
det_G = np.linalg.det(G)
V = np.sqrt(det_G)

# 3. Reciprocal Metric Tensor G* = G^-1
G_star = np.linalg.inv(G)

# 4. Plane d-spacing calculation (h k l)
h = np.array([${h1}, ${k1}, ${l1}], dtype=np.float64)
inv_d_sq = np.dot(h, np.dot(G_star, h))
d_spacing = 1.0 / np.sqrt(inv_d_sq)

# 5. Busing-Levy Matrix B
B = np.array(${JSON.stringify(matrixB)}, dtype=np.float64)

print(f"=== Crystallographic Results ===")
print(f"Unit Cell Volume V = {V:.4f} Å³")
print(f"Reflection ({h[0]:.0f} {h[1]:.0f} {h[2]:.0f}) d-spacing = {d_spacing:.4f} Å")
print(f"\\nDirect Metric Tensor G:\\n{G}")
print(f"\\nReciprocal Metric Tensor G*:\\n{G_star}")
print(f"\\nBusing-Levy Matrix B:\\n{B}")
`;

  const pymatgenScript = `from pymatgen.core import Lattice

# Create Lattice using direct parameters
lattice = Lattice.from_parameters(
    a=${params.a}, b=${params.b}, c=${params.c},
    alpha=${params.alpha}, beta=${params.beta}, gamma=${params.gamma}
)

# Metric Tensor in PyMatGen
G = lattice.metric_tensor
G_star = lattice.reciprocal_lattice.metric_tensor

# d-spacing of plane (${h1}, ${k1}, ${l1})
d_hkl = lattice.d_hkl((${h1}, ${k1}, ${l1}))

print(f"PyMatGen Cell Volume: {lattice.volume:.4f} Å³")
print(f"d-spacing ({h1} {k1} {l1}): {d_hkl:.4f} Å")
`;

  const latexMatrix = `% LaTeX Crystallographic Metric Tensors
\\documentclass{article}
\\usepackage{amsmath}
\\begin{document}

\\section*{Metric Tensor Analysis for ${system} System}
Unit Cell: $a = ${params.a}\\,\\text{\\AA},\\; b = ${params.b}\\,\\text{\\AA},\\; c = ${params.c}\\,\\text{\\AA},\\; \\alpha = ${params.alpha}^\\circ,\\; \\beta = ${params.beta}^\\circ,\\; \\gamma = ${params.gamma}^\\circ$

\\subsection*{Direct Metric Tensor $[G]$}
\\[
G = \\begin{pmatrix}
${metricG.map(r => r.map(v => fmt(v, 4)).join(' & ')).join(' \\\\\n')}
\\end{pmatrix}
\\quad \\Rightarrow \\quad V = \\sqrt{\\det(G)} = ${fmt(Math.sqrt(Math.max(0, metricG[0][0]*metricG[1][1]*metricG[2][2])), 3)}\\,\\text{\\AA}^3
\\]

\\subsection*{Reciprocal Metric Tensor $[G^*]$}
\\[
G^* = G^{-1} = \\begin{pmatrix}
${metricGStar.map(r => r.map(v => fmt(v, 5)).join(' & ')).join(' \\\\\n')}
\\end{pmatrix}
\\]

\\subsection*{Plane Contraction $d_{(${h1}${k1}${l1})}$}
\\[
\\frac{1}{d^2} = \\mathbf{h}^T G^* \\mathbf{h} = \\begin{pmatrix} ${h1} & ${k1} & ${l1} \\end{pmatrix} G^* \\begin{pmatrix} ${h1} \\\\ ${k1} \\\\ ${l1} \\end{pmatrix}
\\]

\\end{document}
`;

  const handleDownloadPython = () => {
    const blob = new Blob([pythonScript], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `metric_tensor_${system.toLowerCase()}_${Date.now()}.py`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">

      {/* Header Banner */}
      <div className="bg-slate-950 rounded-3xl p-6 border border-slate-800/80 shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div className="space-y-1">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-500/15 border border-emerald-500/30 text-emerald-300 text-xs font-mono font-bold uppercase tracking-wider">
            <Terminal className="w-3.5 h-3.5 text-emerald-400" />
            <span>SCIENTIFIC PYTHON & SCRIPTING EXPORT</span>
          </div>
          <h3 className="text-xl font-bold text-white tracking-tight">
            Python (NumPy / PyMatGen / Gemmi) & Publication LaTeX
          </h3>
          <p className="text-xs text-slate-300 max-w-2xl">
            Export reproducible scripts and publication-ready LaTeX markup for inclusion in crystallographic research papers.
          </p>
        </div>

        <button
          onClick={handleDownloadPython}
          className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-mono font-bold text-xs shadow-lg shadow-emerald-600/30 transition-all cursor-pointer"
        >
          <Download className="w-4 h-4" />
          Download .py
        </button>
      </div>

      {/* Code Export Cards Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

        {/* NumPy Script */}
        <div className="bg-slate-950 p-6 rounded-3xl border border-slate-800/80 space-y-4 shadow-xl flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between border-b border-slate-800 pb-2">
              <span className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider flex items-center gap-2">
                <Code2 className="w-4 h-4 text-cyan-400" />
                NumPy Standalone Script
              </span>
              <button
                onClick={() => copyToClipboard(pythonScript, 'numpy_script')}
                className="flex items-center gap-1 text-[11px] font-mono text-cyan-400 hover:text-cyan-300 cursor-pointer"
              >
                {copiedKey === 'numpy_script' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>Copy Script</span>
              </button>
            </div>
            <pre className="p-4 bg-slate-900 rounded-2xl border border-slate-800 font-mono text-[11px] text-slate-300 overflow-x-auto max-h-[300px] leading-relaxed">
              {pythonScript}
            </pre>
          </div>
        </div>

        {/* PyMatGen Script */}
        <div className="bg-slate-950 p-6 rounded-3xl border border-slate-800/80 space-y-4 shadow-xl flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between border-b border-slate-800 pb-2">
              <span className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider flex items-center gap-2">
                <Terminal className="w-4 h-4 text-violet-400" />
                PyMatGen Integration
              </span>
              <button
                onClick={() => copyToClipboard(pymatgenScript, 'pymatgen_script')}
                className="flex items-center gap-1 text-[11px] font-mono text-violet-400 hover:text-violet-300 cursor-pointer"
              >
                {copiedKey === 'pymatgen_script' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>Copy Code</span>
              </button>
            </div>
            <pre className="p-4 bg-slate-900 rounded-2xl border border-slate-800 font-mono text-[11px] text-slate-300 overflow-x-auto max-h-[300px] leading-relaxed">
              {pymatgenScript}
            </pre>
          </div>
        </div>

        {/* Publication LaTeX */}
        <div className="lg:col-span-2 bg-slate-950 p-6 rounded-3xl border border-slate-800/80 space-y-4 shadow-xl">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2">
            <span className="text-xs font-mono font-bold text-slate-400 uppercase tracking-wider flex items-center gap-2">
              <FileText className="w-4 h-4 text-amber-400" />
              Publication-Ready LaTeX Article Snippet
            </span>
            <button
              onClick={() => copyToClipboard(latexMatrix, 'latex_matrix')}
              className="flex items-center gap-1 text-[11px] font-mono text-amber-400 hover:text-amber-300 cursor-pointer"
            >
              {copiedKey === 'latex_matrix' ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>Copy LaTeX</span>
            </button>
          </div>
          <pre className="p-4 bg-slate-900 rounded-2xl border border-slate-800 font-mono text-[11px] text-slate-300 overflow-x-auto max-h-[220px] leading-relaxed">
            {latexMatrix}
          </pre>
        </div>

      </div>

    </div>
  );
};
