import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Code, Copy, Download, RefreshCw, Terminal, CheckCircle2 } from 'lucide-react';

export const PythonExportModule: React.FC = () => {
  const { t } = useTranslation();
  const [scriptContent, setScriptContent] = useState<string>('');
  const [isCopied, setIsCopied] = useState(false);
  const [selectedLibrary, setSelectedLibrary] = useState<'pysyn' | 'lmfit' | 'xrayutilities'>('pysyn');
  const [userEdited, setUserEdited] = useState(false);

  // Load initial state
  useEffect(() => {
    const saved = localStorage.getItem('xrd_python_export');
    if (saved) {
      try {
        const data = JSON.parse(saved);
        if (data.library) setSelectedLibrary(data.library);
        if (data.content) setScriptContent(data.content);
        if (data.userEdited) setUserEdited(data.userEdited);
      } catch (e) {
        console.error("Error loading saved state", e);
      }
    }
  }, []);

  // Debounced Auto-save
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      localStorage.setItem('xrd_python_export', JSON.stringify({
        library: selectedLibrary,
        content: scriptContent,
        userEdited: userEdited
      }));
    }, 1000);
    return () => clearTimeout(timeoutId);
  }, [scriptContent, selectedLibrary, userEdited]);

  const generateScript = () => {
    try {
      // Pull state from localStorage
      const braggStr = localStorage.getItem('xrd_bragg_current');
      const braggData = braggStr ? JSON.parse(braggStr) : null;
      
      const wavelength = braggData?.wavelength || 1.5406;
      const rawPeaksStr = braggData?.rawPeaks || '28.44, 47.30, 56.12';
      
      const rawPeaks = rawPeaksStr.split(/[,;\s]+/)
                           .map((s: string) => parseFloat(s.split(':')[0]))
                           .filter((n: number) => !isNaN(n) && n > 0).join(', ');

      const rietveldStr = localStorage.getItem('xrd_rietveld_setup');
      const rietveldData = rietveldStr ? JSON.parse(rietveldStr) : null;
      
      const phaseNames = rietveldData?.initial_parameters?.phases?.map(p => p.name) || ['Phase1'];

      let pythonCode = `#!/usr/bin/env python3
"""
Automated XRD Analysis Script generated by XRD-Calc Pro
Target Library: ${selectedLibrary === 'pysyn' ? 'PySyn' : selectedLibrary === 'lmfit' ? 'LMFIT' : 'xrayutilities'}
"""
import numpy as np
import matplotlib.pyplot as plt
`;

      if (selectedLibrary === 'pysyn') {
        pythonCode += `
# Configuration
WAVELENGTH = ${wavelength}  # Angstroms
PEAKS_2THETA = [${rawPeaks}]

print(f"Initializing Analysis for {len(PEAKS_2THETA)} peaks at {WAVELENGTH} Å")

def calculate_d_spacings(two_theta_list, wavelength):
    d_spacings = []
    for two_theta in two_theta_list:
        theta_rad = np.radians(two_theta / 2.0)
        d = wavelength / (2.0 * np.sin(theta_rad))
        d_spacings.append(d)
    return d_spacings

d_vals = calculate_d_spacings(PEAKS_2THETA, WAVELENGTH)
for i, d in enumerate(d_vals):
    print(f"Peak {i+1}: 2θ = {PEAKS_2THETA[i]:.2f}°, d = {d:.4f} Å")
    
# Basic Scherrer Method Calculation
def scherrer_size(two_theta_deg, fwhm_deg, wavelength, k=0.9):
    theta_rad = np.radians(two_theta_deg / 2)
    fwhm_rad = np.radians(fwhm_deg)
    return (k * wavelength) / (fwhm_rad * np.cos(theta_rad)) * 10  # in nm

print("\\nSimulated Scherrer Size for First Peak (FWHM = 0.2°):")
if len(PEAKS_2THETA) > 0:
    size = scherrer_size(PEAKS_2THETA[0], 0.2, WAVELENGTH)
    print(f"Estimated crystallite size: {size:.2f} nm")
`;
      } else if (selectedLibrary === 'lmfit') {
        pythonCode += `
from lmfit import models

# Input Configuration
WAVELENGTH = ${wavelength}
PEAKS_2THETA = [${rawPeaks}]

print("LMFIT - Peak Profiling Template")
print("Provide 'x_data' and 'y_data' representing your diffractogram")

# Example: setting up a pseudo-voigt model for the provided peaks
if len(PEAKS_2THETA) > 0:
    composite_model = None
    params = None
    
    for i, peak in enumerate(PEAKS_2THETA):
        prefix = f'p{i}_'
        model = models.PseudoVoigtModel(prefix=prefix)
        pars = model.make_params(center=peak, amplitude=100, sigma=0.1)
        
        if composite_model is None:
            composite_model = model
            params = pars
        else:
            composite_model += model
            params.update(pars)
            
    print(f"Constructed composite model with {len(PEAKS_2THETA)} Pseudo-Voigt components.")
    # result = composite_model.fit(y_data, params, x=x_data)
    # print(result.fit_report())
`;
      } else if (selectedLibrary === 'xrayutilities') {
        pythonCode += `
import xrayutilities as xu

WAVELENGTH = ${wavelength}
en = xu.en2lam(WAVELENGTH)
print(f"Energy: {en:.2f} keV")

# Experimental setup based on standard diffraction geometry
qconv = xu.experiment.QConversion(['y', 'z-'], ['y', 'x+'], [1, 0, 0])

hxrd = xu.HXRD([1, 0, 0], [0, 0, 1])

# Initialize Materials
print("Materials to analyze: ${phaseNames.join(', ')}")
# e.g., si = xu.materials.Si

# Extracting q vectors for given peaks:
peaks_2theta = [${rawPeaks}]
print("Q-vectors (Angstrom^-1) for peaks:")
for two_theta in peaks_2theta:
    theta_rad = np.radians(two_theta/2)
    q = 4 * np.pi * np.sin(theta_rad) / WAVELENGTH
    print(f"2θ={two_theta:.2f}° -> Q={q:.4f} Å^-1")
`;
      }

      setScriptContent(pythonCode);
    } catch (error) {
      console.error(error);
      setScriptContent('# Error generating script from current state.');
    }
  };

  useEffect(() => {
    if (!userEdited) {
      generateScript();
    }
  }, [selectedLibrary]);

  const handleCopy = () => {
    navigator.clipboard.writeText(scriptContent);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([scriptContent], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'xrd_analysis.py';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleRegenerate = () => {
    setUserEdited(false);
    generateScript();
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
       <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 shadow-xl border border-slate-200 dark:border-white/5 relative overflow-hidden">
         <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 dark:bg-indigo-500/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3 pointer-events-none" />
         
         <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 relative z-10">
           <div>
             <h2 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-cyan-500 flex items-center gap-2">
               <Terminal className="w-6 h-6 text-indigo-500" />
               {t('Python Script Generator', 'Python Script Generator')}
             </h2>
             <p className="text-sm text-slate-500 mt-1">Export computational configurations directly into an automated Python workflow.</p>
           </div>
           
           <div className="flex items-center gap-2">
              <select 
                value={selectedLibrary}
                onChange={(e) => {
                  setSelectedLibrary(e.target.value as any);
                  setUserEdited(false); // Regenerate cleanly on change
                }}
                className="bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-sm rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500/50"
              >
                 <option value="pysyn">Standard (NumPy)</option>
                 <option value="lmfit">LMFIT (Peak Profiling)</option>
                 <option value="xrayutilities">xrayutilities</option>
              </select>
              
              <button 
                onClick={handleRegenerate}
                className="bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 p-2 rounded-lg transition-colors border border-slate-200 dark:border-slate-700"
                title="Regenerate from Current Parameters"
              >
                <RefreshCw className="w-5 h-5" />
              </button>
           </div>
         </div>

         <div className="relative group z-10">
            <div className="absolute right-4 top-4 flex gap-2">
               {userEdited && (
                  <span className="text-[10px] bg-amber-500/10 text-amber-500 px-2 py-1 rounded-md border border-amber-500/20 flex items-center h-[34px]">
                    Edited
                  </span>
               )}
               <button 
                  onClick={handleCopy}
                  className="bg-slate-800 hover:bg-slate-700 text-slate-300 p-2 rounded border border-slate-600 transition-colors shadow-sm focus:outline-none"
                  title="Copy Code"
               >
                 {isCopied ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
               </button>
               <button 
                  onClick={handleDownload}
                  className="bg-slate-800 hover:bg-slate-700 text-slate-300 p-2 rounded border border-slate-600 transition-colors shadow-sm focus:outline-none"
                  title="Download .py"
               >
                 <Download className="w-4 h-4" />
               </button>
            </div>
            <textarea 
               value={scriptContent}
               onChange={(e) => {
                 setScriptContent(e.target.value);
                 setUserEdited(true);
               }}
               spellCheck="false"
               className="w-full bg-[#0D1117] text-[#C9D1D9] p-5 pt-14 rounded-xl border border-slate-800 overflow-y-auto text-sm font-mono leading-relaxed h-[500px] custom-scrollbar shadow-inner focus:outline-none focus:border-indigo-500/50 resize-y"
            />
         </div>
       </div>
    </div>
  );
};
