import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Code, Copy, Download, RefreshCw, Terminal, CheckCircle2 } from 'lucide-react';

export const PythonExportModule: React.FC = () => {
  const { t } = useTranslation();
  const [scriptContent, setScriptContent] = useState<string>('');
  const [isCopied, setIsCopied] = useState(false);
  const [selectedLibrary, setSelectedLibrary] = useState<'pysyn' | 'lmfit' | 'xrayutilities' | 'gsas2'>('pysyn');
  const [userEdited, setUserEdited] = useState(false);

  // Load initial state
  useEffect(() => {
    const saved = localStorage.getItem('xrd_python_export');
    if (saved) {
      try {
        const data = JSON.parse(saved);
        if (data.library) setSelectedLibrary(data.library);
        if (data.content) setScriptContent(data.content);
        if (data.userEdited) setUserEdited(data.userEdited);
      } catch (e) {
        console.error("Error loading saved state", e);
      }
    }
  }, []);

  // Debounced Auto-save
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      localStorage.setItem('xrd_python_export', JSON.stringify({
        library: selectedLibrary,
        content: scriptContent,
        userEdited: userEdited
      }));
    }, 1000);
    return () => clearTimeout(timeoutId);
  }, [scriptContent, selectedLibrary, userEdited]);

  const generateScript = () => {
    try {
      // Pull state from localStorage
      const braggStr = localStorage.getItem('xrd_bragg_current');
      const braggData = braggStr ? JSON.parse(braggStr) : null;
      
      const wavelength = braggData?.wavelength || 1.5406;
      let rawPeaksStr = braggData?.rawPeaks || '28.44, 47.30, 56.12';
      if (typeof rawPeaksStr !== 'string') rawPeaksStr = '28.44, 47.30, 56.12';

      const rawPeaks = rawPeaksStr.split(/[,;\\s]+/)
                           .map((s: string) => parseFloat(s.split(':')[0]))
                           .filter((n: number) => !isNaN(n) && n > 0).join(', ');

      const rietveldStr = localStorage.getItem('xrd_rietveld_current_v2');
      const rietveldData = rietveldStr ? JSON.parse(rietveldStr) : null;
      
      let phaseNames = rietveldData?.simPhases?.map((p: any) => p.name || p.phase);
      if (!phaseNames || phaseNames.length === 0) {
          phaseNames = ['Phase1'];
      }

      let pythonCode = `#!/usr/bin/env python3\n"""\nAutomated XRD Analysis Script generated by XRD-Calc Pro\nTarget Library: ${selectedLibrary === 'pysyn' ? 'SciPy / NumPy' : selectedLibrary === 'lmfit' ? 'LMFIT' : selectedLibrary === 'gsas2' ? 'GSAS-II' : 'xrayutilities'}\n"""\n`;

      if (selectedLibrary === 'pysyn') {
        pythonCode += `import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.signal import find_peaks

# Configuration
WAVELENGTH = ${wavelength}  # Angstroms
EXPECTED_PEAKS = [${rawPeaks}]
DATA_FILE = "data.xy" # replace with your data file path

def calculate_d_spacing(two_theta, wavelength):
    """Calculate d-spacing using Bragg's Law"""
    theta_rad = np.radians(two_theta / 2.0)
    return wavelength / (2.0 * np.sin(theta_rad))

def analyze_xrd_data():
    try:
        # Load Data
        df = pd.read_csv(DATA_FILE, sep=r'\\s+', names=['2theta', 'intensity'], comment='#')
        x = df['2theta'].values
        y = df['intensity'].values
        
        # Background subtraction (simple baseline)
        baseline = np.min(y)
        y_corr = y - baseline
        
        # Peak Finding
        peaks, properties = find_peaks(y_corr, height=np.max(y_corr)*0.05, distance=10)
        found_2theta = x[peaks]
        
        print(f"Found {len(peaks)} peaks.")
        for idx, th in enumerate(found_2theta):
            d = calculate_d_spacing(th, WAVELENGTH)
            print(f"Peak {idx+1}: 2θ = {th:.3f}°, d = {d:.4f} Å")
            
        # Plotting
        plt.figure(figsize=(10, 5))
        plt.plot(x, y, label='Raw Data', color='#1f77b4')
        plt.plot(found_2theta, y[peaks], 'rx', label='Detected Peaks')
        
        for ep in EXPECTED_PEAKS:
            plt.axvline(ep, color='green', linestyle='--', alpha=0.5)
            
        plt.title('XRD Pattern Analysis')
        plt.xlabel('2θ (°)')
        plt.ylabel('Intensity (a.u.)')
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.tight_layout()
        plt.show()
        
    except FileNotFoundError:
        print(f"Error: {DATA_FILE} not found. Please provide a valid .xy or .csv file.")
        
        # Fallback demonstration with Expected Peaks
        print("\\nDemonstrating with theoretical peaks:")
        for ep in EXPECTED_PEAKS:
            print(f"Expected Peak: {ep}°, d = {calculate_d_spacing(ep, WAVELENGTH):.4f} Å")

if __name__ == "__main__":
    analyze_xrd_data()
`;
      } else if (selectedLibrary === 'lmfit') {
        pythonCode += `import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from lmfit import models

# Input Configuration
WAVELENGTH = ${wavelength}
EXPECTED_PEAKS = [${rawPeaks}]
DATA_FILE = "data.xy" 

def fit_xrd_pattern():
    try:
        # Load Data
        df = pd.read_csv(DATA_FILE, sep=r'\\s+', names=['x', 'y'], comment='#')
        x, y = df['x'].values, df['y'].values
        
        # Setup Composite Model
        composite_model = models.ConstantModel(prefix='bkg_')
        params = composite_model.make_params(c=np.min(y))
        
        print(f"Setting up Pseudo-Voigt profiles for {len(EXPECTED_PEAKS)} expected peaks...")
        
        for i, peak in enumerate(EXPECTED_PEAKS):
            prefix = f'p{i}_'
            # PseudoVoigt is common for XRD profiles
            model = models.PseudoVoigtModel(prefix=prefix)
            
            # Initial guesses
            pars = model.make_params()
            pars[f'{prefix}center'].set(value=peak, min=peak-0.5, max=peak+0.5)
            pars[f'{prefix}amplitude'].set(value=np.max(y), min=0)
            pars[f'{prefix}sigma'].set(value=0.1, min=0.01, max=1.0)
            pars[f'{prefix}fraction'].set(value=0.5, min=0, max=1) # Mixing parameter
            
            composite_model += model
            params.update(pars)
            
        # Perform Fit
        print("Starting optimization...")
        result = composite_model.fit(y, params, x=x)
        
        print("\\n-- Fit Results --")
        print(result.fit_report(min_correl=0.5))
        
        # Plot Results
        plt.figure(figsize=(10, 6))
        plt.plot(x, y, 'b.', label='Data', markersize=2)
        plt.plot(x, result.best_fit, 'r-', label='Best Fit')
        plt.plot(x, result.init_fit, 'k--', label='Initial Guess', alpha=0.5)
        
        comps = result.eval_components(x=x)
        for name, comp in comps.items():
            if name != 'bkg_':
                plt.fill_between(x, comps['bkg_'], comp + comps['bkg_'], alpha=0.3)
                
        plt.title('XRD Peak Deconvolution using LMFIT')
        plt.xlabel('2θ (°)')
        plt.ylabel('Intensity (a.u.)')
        plt.legend()
        plt.tight_layout()
        plt.show()
        
    except FileNotFoundError:
        print(f"Error: Could not load {DATA_FILE}. Please ensure the data file exists.")

if __name__ == "__main__":
    fit_xrd_pattern()
`;
      } else if (selectedLibrary === 'gsas2') {
        pythonCode += `import os
import sys

# Change this to your GSAS-II installation path
GSAS2_DIR = os.path.expanduser("~/GSASII/GSASII") 
if GSAS2_DIR not in sys.path:
    sys.path.insert(0, GSAS2_DIR)

try:
    import GSASIIscriptable as G2sc
except ImportError:
    print("Error: Could not import GSAS-II.")
    print(f"Please check your GSAS-II installation at {GSAS2_DIR}")
    sys.exit(1)

# Configuration
WAVELENGTH = ${wavelength}
DATA_FILE = "data.xy"       # Replace with your powder data
PHASES = [${phaseNames.map((p: string) => `"${p}"`).join(', ')}]
CIF_FILES = [f"{p}.cif" for p in PHASES]

def run_rietveld():
    print("Initializing GSAS-II Project...")
    gpx = G2sc.G2Project(newgpx='refinement.gpx')
    
    try:
        # Load Powder Data
        print(f"Loading data from {DATA_FILE}...")
        hist = gpx.add_powder_histogram(DATA_FILE, instrument=None)
        
        # Set Wavelength
        hist.data['Instrument Parameters'][0]['Lam'][1] = WAVELENGTH
        
        # Load Phases
        for i, phase_name in enumerate(PHASES):
            cif_file = CIF_FILES[i]
            print(f"Loading Phase: {phase_name} from {cif_file}")
            if os.path.exists(cif_file):
                phase = gpx.add_phase(cif_file, phaseName=phase_name, histograms=[hist])
                # Enable fraction and unit cell refinement
                gpx.set_refinement({"set": {"Phase": {phase_name: ["Fraction", "Cell"]}}})
            else:
                print(f"  Warning: {cif_file} not found. Skipping phase.")
                
        # Set Background parameters (e.g., 6 terms shift Chebyshev)
        gpx.set_refinement({"set": {"Background": {"no. terms": 6, "refine": True}}})
        
        # Setup Instrument Refinement (Zero shift)
        gpx.set_refinement({"set": {"Instrument": {"Zero": True}}})
        
        # Run Refinement
        print("Starting least-squares refinement...")
        gpx.do_refinements([{"iters": 5}])
        
        # Get R-factors
        r_wR = hist.get_wR()
        print(f"Refinement finished. Cumulative wR: {r_wR:.2%}")
        
        # Save updated project
        gpx.save()
        print("Project saved as refinement.gpx")
        
    except Exception as e:
        print(f"GSAS-II run failed: {e}")

if __name__ == "__main__":
    run_rietveld()
`;
      } else if (selectedLibrary === 'xrayutilities') {
        pythonCode += `import numpy as np
import xrayutilities as xu

WAVELENGTH = ${wavelength}
en = xu.en2lam(WAVELENGTH)
print(f"Energy: {en:.2f} keV")

# Experimental setup based on standard diffraction geometry
qconv = xu.experiment.QConversion(['y', 'z-'], ['y', 'x+'], [1, 0, 0])

hxrd = xu.HXRD([1, 0, 0], [0, 0, 1])

# Initialize Materials
print("Materials to analyze: ${phaseNames.join(', ')}")
# e.g., si = xu.materials.Si

# Extracting q vectors for given peaks:
peaks_2theta = [${rawPeaks}]
print("Q-vectors (Angstrom^-1) for peaks:")
for two_theta in peaks_2theta:
    theta_rad = np.radians(two_theta/2)
    q = 4 * np.pi * np.sin(theta_rad) / WAVELENGTH
    print(f"2θ={two_theta:.2f}° -> Q={q:.4f} Å^-1")
`;
      }

      setScriptContent(pythonCode);
    } catch (error) {
      console.error(error);
      setScriptContent('# Error generating script from current state.');
    }
  };

  useEffect(() => {
    if (!userEdited) {
      generateScript();
    }
  }, [selectedLibrary]);

  const handleCopy = () => {
    navigator.clipboard.writeText(scriptContent);
    setIsCopied(true);
    setTimeout(() => setIsCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([scriptContent], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'xrd_analysis.py';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleRegenerate = () => {
    setUserEdited(false);
    generateScript();
  };

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
       <div className="bg-white dark:bg-slate-900 rounded-2xl p-6 shadow-xl border border-slate-200 dark:border-white/5 relative overflow-hidden">
         <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 dark:bg-indigo-500/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3 pointer-events-none" />
         
         <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6 relative z-10">
           <div>
             <h2 className="text-xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-cyan-500 flex items-center gap-2">
               <Terminal className="w-6 h-6 text-indigo-500" />
               {t('Python Script Generator', 'Python Script Generator')}
             </h2>
             <p className="text-sm text-slate-500 mt-1">Export computational configurations directly into an automated Python workflow.</p>
           </div>
           
           <div className="flex items-center gap-2">
              <select 
                value={selectedLibrary}
                onChange={(e) => {
                  setSelectedLibrary(e.target.value as any);
                  setUserEdited(false); // Regenerate cleanly on change
                }}
                className="bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-sm rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500/50"
              >
                 <option value="pysyn">Standard (SciPy / NumPy)</option>
                 <option value="lmfit">LMFIT (Peak Profiling)</option>
                 <option value="gsas2">GSAS-II (Rietveld API)</option>
                 <option value="xrayutilities">xrayutilities</option>
              </select>
              
              <button 
                onClick={handleRegenerate}
                className="bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 p-2 rounded-lg transition-colors border border-slate-200 dark:border-slate-700"
                title="Regenerate from Current Parameters"
              >
                <RefreshCw className="w-5 h-5" />
              </button>
           </div>
         </div>

         <div className="relative group z-10">
            <div className="absolute right-4 top-4 flex gap-2">
               {userEdited && (
                  <span className="text-[10px] bg-amber-500/10 text-amber-500 px-2 py-1 rounded-md border border-amber-500/20 flex items-center h-[34px]">
                    Edited
                  </span>
               )}
               <button 
                  onClick={handleCopy}
                  className="bg-slate-800 hover:bg-slate-700 text-slate-300 p-2 rounded border border-slate-600 transition-colors shadow-sm focus:outline-none"
                  title="Copy Code"
               >
                 {isCopied ? <CheckCircle2 className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
               </button>
               <button 
                  onClick={handleDownload}
                  className="bg-slate-800 hover:bg-slate-700 text-slate-300 p-2 rounded border border-slate-600 transition-colors shadow-sm focus:outline-none"
                  title="Download .py"
               >
                 <Download className="w-4 h-4" />
               </button>
            </div>
            <textarea 
               value={scriptContent}
               onChange={(e) => {
                 setScriptContent(e.target.value);
                 setUserEdited(true);
               }}
               spellCheck="false"
               className="w-full bg-[#0D1117] text-[#C9D1D9] p-5 pt-14 rounded-xl border border-slate-800 overflow-y-auto text-sm font-mono leading-relaxed h-[500px] custom-scrollbar shadow-inner focus:outline-none focus:border-indigo-500/50 resize-y"
            />
         </div>
       </div>
    </div>
  );
};
