import React, { useState, useMemo } from 'react';
import {
  Code2,
  Copy,
  Check,
  Download,
  Terminal,
  FileCode,
  Sparkles,
  BookOpen,
  Share2,
  CheckCircle2,
  Cpu
} from 'lucide-react';
import { playSynthTone } from '../../utils/sound';
import { RIRMatrixPhase } from './RIRMatrixInspector';

interface RIRScriptExportProps {
  phases: RIRMatrixPhase[];
  amorphousWtPct: number;
  intensityUncertaintyPct: number;
  rirUncertaintyPct: number;
  quantMode?: 'adiabatic' | 'spiking';
  internalStandardPhaseId?: string;
  standardAddedWtPct?: number;
  useBrindley?: boolean;
  particleDiameterUm?: number;
}

export const RIRScriptExport: React.FC<RIRScriptExportProps> = ({
  phases,
  amorphousWtPct,
  intensityUncertaintyPct,
  rirUncertaintyPct,
  quantMode = 'adiabatic',
  internalStandardPhaseId,
  standardAddedWtPct = 10.0,
  useBrindley = false,
  particleDiameterUm = 5.0
}) => {
  const [activeTab, setActiveTab] = useState<'python' | 'jupyter' | 'originlab'>('python');
  const [copiedScript, setCopiedScript] = useState<string | null>(null);

  // Generate Python Script
  const pythonScript = useMemo(() => {
    const phaseData = phases.map(p => ({
      name: p.name,
      hkl: p.hkl || '100',
      twoTheta: p.twoTheta || 30.0,
      intensity: p.intensity || 1000,
      rir: p.rir || 1.0,
      density: p.density || 3.0,
      mac: p.mac || 50.0
    }));

    return `"""
=============================================================================
XRD QUANTITATIVE PHASE ANALYSIS VIA REFERENCE INTENSITY RATIO (RIR) METHOD
=============================================================================
Generated by XRD-Calc Pro
Analytical Covariance Error Propagation, Chung Normalization & Spiking Engine
=============================================================================
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# 1. Experimental Input Data
# ---------------------------------------------------------------------------
phases = ${JSON.stringify(phaseData, null, 4)}

mode = "${quantMode}"  # 'adiabatic' (standardless) or 'spiking' (internal standard)
amorphous_wt_input = ${amorphousWtPct}  # wt% (for adiabatic mode)
intensity_rel_err = ${intensityUncertaintyPct / 100}  # relative std dev (ΔI/I)
rir_rel_err = ${rirUncertaintyPct / 100}  # relative std dev (ΔK/K)
std_phase_id = "${internalStandardPhaseId || (phases[0] ? phases[0].id : '')}"
std_added_wt_pct = ${standardAddedWtPct}  # wt% spiked into mixture
use_brindley = ${useBrindley ? 'True' : 'False'}
particle_diameter_cm = ${particleDiameterUm} * 1e-4  # particle diameter D in cm

names = [p['name'] for p in phases]
raw_intensities = np.array([p['intensity'] for p in phases], dtype=float)
rel_intensities = np.array([p['relInt'] for p in phases], dtype=float) / 100.0
# Normalize secondary reflections to equivalent 100% peak intensity
intensities = raw_intensities / rel_intensities
rirs = np.array([p['rir'] for p in phases], dtype=float)
densities = np.array([p['density'] for p in phases], dtype=float)
macs = np.array([p['mac'] for p in phases], dtype=float)
linear_absorptions = densities * macs  # mu_i = rho_i * MAC_i (cm^-1)

n = len(phases)
print(f"Loaded {n} crystalline phases.")

# ---------------------------------------------------------------------------
# 2. Brindley Microabsorption Particle Size Correction (Optional)
# ---------------------------------------------------------------------------
def brindley_transmission_factor(sigma_i, D):
    """
    Spherical particle Brindley transmission factor:
    tau_i(x) = (3 / (2*x^3)) * [x^2 - 2 + 2*(1+x)*exp(-x)] where x = sigma_i * D
    """
    x = sigma_i * D
    tau = np.ones_like(x)
    for i, val in enumerate(x):
        if abs(val) < 1e-4:
            tau[i] = 1.0 - (9.0/16.0)*val + (1.0/6.0)*(val**2)
        else:
            tau[i] = (3.0 / (2.0 * val**3)) * (val**2 - 2.0 + 2.0 * (1.0 + val) * np.exp(-val))
    return np.clip(tau, 0.01, 10.0)

if use_brindley:
    # Estimate sample average linear absorption
    # Initial rough weight fractions
    w_rough = (intensities / rirs) / np.sum(intensities / rirs)
    mu_bar = np.sum(w_rough * linear_absorptions)
    sigma = linear_absorptions - mu_bar
    tau = brindley_transmission_factor(sigma, particle_diameter_cm)
    corrected_intensities = intensities / tau
    print("\\n[Brindley Microabsorption Correction Applied]")
    for i in range(n):
        print(f"  {names[i]}: mu={linear_absorptions[i]:.1f} cm^-1, sigma={sigma[i]:.1f}, tau={tau[i]:.4f}")
    calc_intensities = corrected_intensities
else:
    calc_intensities = intensities

# ---------------------------------------------------------------------------
# 3. Quantitative Phase Calculations
# ---------------------------------------------------------------------------
reduced_intensities = calc_intensities / rirs  # I_i / RIR_i
total_reduced = np.sum(reduced_intensities)

if mode == "adiabatic":
    # Chung Adiabatic Normalized Method
    cryst_wt_fractions = reduced_intensities / total_reduced * 100.0
    amorphous_factor = (100.0 - amorphous_wt_input) / 100.0
    sample_wt_fractions = cryst_wt_fractions * amorphous_factor
    determined_amorphous_wt = amorphous_wt_input
    
    # Analytical Covariance Matrix for Adiabatic Chung:
    # J_I[i, j] = (delta_ij - w_i) / (S * K_j)
    # J_K[i, j] = -(w_i / K_j) * (delta_ij - w_j)
    w_vec = cryst_wt_fractions / 100.0
    J_I = np.zeros((n, n))
    J_K = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            delta = 1.0 if i == j else 0.0
            J_I[i, j] = (delta - w_vec[i]) / (total_reduced * rirs[j])
            J_K[i, j] = -(w_vec[i] / rirs[j]) * (delta - w_vec[j])
            
    cov_I = np.diag((calc_intensities * intensity_rel_err)**2)
    cov_K = np.diag((rirs * rir_rel_err)**2)
    cov_w = J_I @ cov_I @ J_I.T + J_K @ cov_K @ J_K.T
    std_w = np.sqrt(np.diag(cov_w)) * 100.0 * amorphous_factor
    
else:
    # Spiking Internal Standard Method
    # Identify standard index
    std_idx = 0
    for idx, p in enumerate(phases):
        if p.get('id') == std_phase_id:
            std_idx = idx
            break
            
    ws_spiked = std_added_wt_pct / 100.0
    I_s = calc_intensities[std_idx]
    RIR_s = rirs[std_idx]
    
    # Weight fraction in spiked mixture: w_i = w_s * (I_i / I_s) * (RIR_s / RIR_i)
    w_spiked = ws_spiked * (calc_intensities / I_s) * (RIR_s / rirs)
    # Weight fraction in original unspiked sample: w_orig = w_spiked / (1 - w_s)
    w_orig = w_spiked / (1.0 - ws_spiked) * 100.0
    
    # Sum of all crystalline phases in original sample (excluding standard)
    cryst_sum = 0.0
    for i in range(n):
        if i != std_idx:
            cryst_sum += w_orig[i]
            
    determined_amorphous_wt = max(0.0, 100.0 - cryst_sum)
    sample_wt_fractions = w_orig.copy()
    sample_wt_fractions[std_idx] = 0.0  # standard was not in original sample
    
    # Error propagation for Spiking Method
    std_w = np.zeros(n)
    for i in range(n):
        if i == std_idx:
            continue
        rel_var = (intensity_rel_err**2) + (intensity_rel_err**2) + (rir_rel_err**2) + (0.01**2)
        std_w[i] = sample_wt_fractions[i] * np.sqrt(rel_var)

# Volume Fractions
vol_factors = sample_wt_fractions / densities
total_vol_factor = np.sum(vol_factors) + (determined_amorphous_wt / 2.2 if determined_amorphous_wt > 0 else 0)
vol_fractions = (vol_factors / total_vol_factor) * 100.0

# ---------------------------------------------------------------------------
# 4. Results Presentation
# ---------------------------------------------------------------------------
print("\\n=============================================================================")
print("RIR QUANTITATIVE RESULTS SUMMARY")
print("=============================================================================")
df = pd.DataFrame({
    'Phase': names,
    'Intensity': calc_intensities,
    'RIR': rirs,
    'Weight_%': sample_wt_fractions.round(2),
    'Error_±%': std_w.round(2),
    'Volume_%': vol_fractions.round(2),
    'Density': densities,
    'MAC': macs
})
print(df.to_string(index=False))
print("-----------------------------------------------------------------------------")
if determined_amorphous_wt > 0:
    print(f"Amorphous Matrix Content : {determined_amorphous_wt:.2f} wt%")
print("=============================================================================\\n")

# ---------------------------------------------------------------------------
# 5. Publication Visualization
# ---------------------------------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Donut Chart
plot_labels = list(names)
plot_vals = list(sample_wt_fractions)
if determined_amorphous_wt > 0:
    plot_labels.append('Amorphous')
    plot_vals.append(determined_amorphous_wt)

colors = plt.cm.tab10(np.linspace(0, 1, len(plot_labels)))
wedges, texts, autotexts = ax1.pie(
    plot_vals, labels=plot_labels, autopct='%1.1f%%',
    pctdistance=0.75, startangle=140, colors=colors,
    wedgeprops=dict(width=0.45, edgecolor='white', linewidth=1.5)
)
ax1.set_title("Phase Weight Fractions (wt%)", fontweight='bold')

# Bar Chart with Error Bars
bar_x = np.arange(len(names))
ax2.bar(bar_x, sample_wt_fractions, yerr=std_w, capsize=5, color=colors[:len(names)], edgecolor='black', alpha=0.85)
ax2.set_xticks(bar_x)
ax2.set_xticklabels(names, rotation=30, ha='right')
ax2.set_ylabel("Weight Fraction (wt%)")
ax2.set_title("Phase Fractions with Covariance Error Propagation", fontweight='bold')
ax2.grid(axis='y', linestyle='--', alpha=0.5)

plt.tight_layout()
plt.show()
`;
  }, [phases, amorphousWtPct, intensityUncertaintyPct, rirUncertaintyPct, quantMode, internalStandardPhaseId, standardAddedWtPct, useBrindley, particleDiameterUm]);

  // Generate Jupyter Notebook JSON
  const jupyterNotebook = useMemo(() => {
    const notebook = {
      cells: [
        {
          cell_type: 'markdown',
          metadata: {},
          source: [
            '# Quantitative Phase Analysis via Reference Intensity Ratio (RIR) Method\n',
            '**XRD-Calc Pro Analytical Studio**\n',
            'Calculates phase weight fractions, volumetric proportions, Brindley microabsorption corrections, and analytical covariance matrices.'
          ]
        },
        {
          cell_type: 'code',
          execution_count: null,
          metadata: {},
          outputs: [],
          source: pythonScript.split('\n').map(line => line + '\n')
        }
      ],
      metadata: {
        language_info: {
          name: 'python'
        }
      },
      nbformat: 4,
      nbformat_minor: 2
    };

    return JSON.stringify(notebook, null, 2);
  }, [pythonScript]);

  // Generate OriginPro LabTalk & Python Script
  const originLabScript = useMemo(() => {
    return `// =============================================================================
// OriginLab LabTalk & OriginPro Python Script for RIR Quantitative Analysis
// Paste into OriginPro Script Window or Code Builder
// =============================================================================

// 1. Create a new workbook with Phase Results
newbook name:="RIR_Quant_Results" sheet:=1;
wks.addcol(PhaseName, 1);
wks.addcol(Intensity, 0);
wks.addcol(RIR_val, 0);
wks.addcol(WeightPct, 0);
wks.addcol(WeightErr, 0);
wks.addcol(VolumePct, 0);

// Set column designations
col(WeightErr)[T] = "yEr"; // Mark as error column

// 2. Populate Phase Quantitative Values
${phases.map((p, idx) => {
  const rI = (p.intensity || 0) / (p.rir > 0 ? p.rir : 1.0);
  return `col(PhaseName)[${idx + 1}]$ = "${p.name}";
col(Intensity)[${idx + 1}] = ${p.intensity};
col(RIR_val)[${idx + 1}] = ${p.rir};
`;
}).join('\n')}

// 3. Create Origin Bar Chart with Error Bars
plotxy iy:=[RIR_Quant_Results]1!(1, 4, 5) plot:=203 ogl:=<new: Bar>;
layer.x.label.rotation = 45;
label -s -r -n title "XRD Quantitative Phase Analysis (RIR Method)";
label -s -r -n ylab "Phase Weight Fraction (wt%)";
label -s -r -n xlab "Crystalline Component";

// 4. Create Origin Pie / Donut Chart
plotxy iy:=[RIR_Quant_Results]1!(1, 4) plot:=225 ogl:=<new: Pie>;
label -s -r -n title "Phase Distribution (%)";

type -a "RIR Quantitative Analysis successfully computed and plotted in OriginPro!";
`;
  }, [phases]);

  const currentCode = activeTab === 'python' ? pythonScript : activeTab === 'jupyter' ? jupyterNotebook : originLabScript;

  const copyToClipboard = () => {
    playSynthTone('success');
    navigator.clipboard.writeText(currentCode);
    setCopiedScript(activeTab);
    setTimeout(() => setCopiedScript(null), 2500);
  };

  const downloadFile = () => {
    playSynthTone('success');
    const ext = activeTab === 'python' ? 'py' : activeTab === 'jupyter' ? 'ipynb' : 'ogs';
    const filename = `RIR_Quantitative_Analysis_${new Date().toISOString().slice(0, 10)}.${ext}`;
    const blob = new Blob([currentCode], {
      type: activeTab === 'jupyter' ? 'application/json' : 'text/plain'
    });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-gradient-to-br from-slate-900/90 to-slate-950/90 border border-slate-800/80 rounded-3xl p-6 md:p-8 shadow-2xl backdrop-blur-md flex flex-col gap-6 text-slate-100">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800/80 pb-5">
        <div className="flex items-center gap-3.5">
          <div className="p-3 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-amber-400 shadow-inner">
            <Code2 className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-black text-slate-100 tracking-tight">
              Python, Jupyter & OriginPro Script Exporter
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Production-ready, standalone scripts with analytical Chung matrix algebra, covariance propagation, and publication-grade visualizations.
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={copyToClipboard}
            className="px-3.5 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-bold border border-slate-700 flex items-center gap-2 transition-all shadow-md active:scale-95"
          >
            {copiedScript === activeTab ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
            <span>{copiedScript === activeTab ? 'Copied!' : 'Copy Code'}</span>
          </button>
          <button
            onClick={downloadFile}
            className="px-3.5 py-2 rounded-xl bg-amber-600 hover:bg-amber-500 text-white text-xs font-bold flex items-center gap-2 transition-all shadow-md shadow-amber-500/20 active:scale-95"
          >
            <Download className="w-4 h-4" />
            <span>Download .{activeTab === 'python' ? 'py' : activeTab === 'jupyter' ? 'ipynb' : 'ogs'}</span>
          </button>
        </div>
      </div>

      {/* Nav Tabs */}
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => { playSynthTone('tick'); setActiveTab('python'); }}
          className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
            activeTab === 'python'
              ? 'bg-amber-600 text-white shadow-md shadow-amber-500/20'
              : 'bg-slate-950/70 border border-slate-800 text-slate-400 hover:text-slate-200'
          }`}
        >
          <Terminal className="w-4 h-4" />
          <span>Python Script (NumPy / SciPy / Matplotlib)</span>
        </button>

        <button
          onClick={() => { playSynthTone('tick'); setActiveTab('jupyter'); }}
          className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
            activeTab === 'jupyter'
              ? 'bg-amber-600 text-white shadow-md shadow-amber-500/20'
              : 'bg-slate-950/70 border border-slate-800 text-slate-400 hover:text-slate-200'
          }`}
        >
          <FileCode className="w-4 h-4" />
          <span>Jupyter Notebook (.ipynb)</span>
        </button>

        <button
          onClick={() => { playSynthTone('tick'); setActiveTab('originlab'); }}
          className={`px-4 py-2 rounded-xl text-xs font-bold flex items-center gap-2 transition-all ${
            activeTab === 'originlab'
              ? 'bg-amber-600 text-white shadow-md shadow-amber-500/20'
              : 'bg-slate-950/70 border border-slate-800 text-slate-400 hover:text-slate-200'
          }`}
        >
          <Cpu className="w-4 h-4" />
          <span>OriginLab LabTalk (.ogs)</span>
        </button>
      </div>

      {/* Code Viewer */}
      <div className="relative rounded-2xl border border-slate-800 bg-slate-950/90 overflow-hidden shadow-inner">
        <div className="flex items-center justify-between px-4 py-2.5 bg-slate-900/90 border-b border-slate-800/80 text-[11px] font-mono text-slate-400">
          <span className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500" />
            {activeTab === 'python' ? 'rir_analysis.py' : activeTab === 'jupyter' ? 'rir_analysis.ipynb' : 'rir_originlab.ogs'}
          </span>
          <span>{currentCode.split('\n').length} lines</span>
        </div>
        <pre className="p-4 text-xs font-mono text-slate-300 overflow-x-auto max-h-[500px] scrollbar-thin scrollbar-thumb-slate-700 leading-relaxed">
          <code>{currentCode}</code>
        </pre>
      </div>
    </div>
  );
};
