import React, { useState } from 'react';
import { LatticeParameters } from '../../types';
import { MagneticAtom, MagneticMetrics, MagneticReflection } from '../../utils/magneticDiffractionPhysics';
import { Code2, Copy, Check, Download, FileText, Terminal, FileCode } from 'lucide-react';

interface MagneticCodeExporterProps {
  lattice: LatticeParameters;
  atoms: MagneticAtom[];
  metrics: MagneticMetrics;
  kVector: { x: number; y: number; z: number };
  temperature: number;
  criticalTemp: number;
  reflections: MagneticReflection[];
  wavelength: number;
}

export const MagneticCodeExporter: React.FC<MagneticCodeExporterProps> = ({
  lattice,
  atoms,
  metrics,
  kVector,
  temperature,
  criticalTemp,
  reflections,
  wavelength
}) => {
  const [exportFormat, setExportFormat] = useState<'fullprof' | 'gsas2' | 'topas' | 'mcif' | 'python_mantid'>('fullprof');
  const [copied, setCopied] = useState<boolean>(false);

  const generateFullProfPCR = () => {
    return `COMM FullProf PCR File - Magnetic Diffraction Simulation
COMM Generated by XRD-Calc-Pro Magnetic Crystallography Engine
! ----------------------------------------------------
! Global Conditions
! ----------------------------------------------------
! Natom  Nphase  Rpa  Nsys  Nrefl
    ${atoms.length}       1      0     0      ${reflections.length}
! Wavelength1  Wavelength2  Ratio  Bkpos  Wdt  Cthm
   ${wavelength.toFixed(4)}    ${wavelength.toFixed(4)}   1.0    0.0  0.0  0.90
!
! ----------------------------------------------------
! Phase 1: Magnetic Structure (Order: ${metrics.orderType})
! ----------------------------------------------------
! Propagation Vector k_x k_y k_z
  ${kVector.x.toFixed(4)}  ${kVector.y.toFixed(4)}  ${kVector.z.toFixed(4)}
! Lattice Parameters a, b, c, alpha, beta, gamma
  ${lattice.a.toFixed(4)} ${lattice.b.toFixed(4)} ${lattice.c.toFixed(4)} ${lattice.alpha.toFixed(2)} ${lattice.beta.toFixed(2)} ${lattice.gamma.toFixed(2)}
!
! Magnetic Atoms (Name, Typ, X, Y, Z, Biso, Occ, Mx, My, Mz)
${atoms.map(a => `  ${a.label.padEnd(8)} ${a.element.padEnd(4)} ${(a.ion || a.element).padEnd(6)} ${a.x.toFixed(4)} ${a.y.toFixed(4)} ${a.z.toFixed(4)} ${a.B_iso.toFixed(2)} 1.000 ${(a.mx || 0).toFixed(3)} ${(a.my || 0).toFixed(3)} ${(a.mz || 0).toFixed(3)}`).join('\n')}
!
! END OF PCR
`;
  };

  const generateMCIF = () => {
    return `#\\#CIF_2.0
# Magnetic Crystallographic Information File (mCIF)
# Generated by XRD-Calc-Pro

data_magnetic_phase
_chemical_name_common                   '${metrics.orderType}'
_cell_length_a                          ${lattice.a.toFixed(4)}
_cell_length_b                          ${lattice.b.toFixed(4)}
_cell_length_c                          ${lattice.c.toFixed(4)}
_cell_angle_alpha                       ${lattice.alpha.toFixed(2)}
_cell_angle_beta                        ${lattice.beta.toFixed(2)}
_cell_angle_gamma                       ${lattice.gamma.toFixed(2)}
_cell_volume                            ${metrics.cellVolume.toFixed(3)}

_space_group_magn.number_BNS            '1.1'
_space_group_magn.name_BNS              'P_a 1'

loop_
_space_group_magn_propagation_vector.seq_id
_space_group_magn_propagation_vector.kxkykz
1 '${kVector.x.toFixed(4)}, ${kVector.y.toFixed(4)}, ${kVector.z.toFixed(4)}'

loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_B_iso_or_equiv
_atom_site_moment.label
_atom_site_moment.crystalaxis_x
_atom_site_moment.crystalaxis_y
_atom_site_moment.crystalaxis_z
${atoms.map(a => `${a.label.padEnd(10)} ${a.element.padEnd(4)} ${a.x.toFixed(4)} ${a.y.toFixed(4)} ${a.z.toFixed(4)} ${a.B_iso.toFixed(2)} ${a.label.padEnd(10)} ${(a.mx || 0).toFixed(3)} ${(a.my || 0).toFixed(3)} ${(a.mz || 0).toFixed(3)}`).join('\n')}
`;
  };

  const generateTOPAS = () => {
    return `' TOPAS Magnetic Macro - XRD-Calc-Pro
xdd "neutron_powder_data.raw"
   lam ymin_on_ymax 0.001
   neutron_lambda ${wavelength.toFixed(4)}
   bkg @ 10 0 0 0

str
   space_group "P 1"
   a ${lattice.a.toFixed(4)}
   b ${lattice.b.toFixed(4)}
   c ${lattice.c.toFixed(4)}
   al ${lattice.alpha.toFixed(2)}
   be ${lattice.beta.toFixed(2)}
   ga ${lattice.gamma.toFixed(2)}

   ' Magnetic Propagation Vector
   k_vector ${kVector.x.toFixed(4)} ${kVector.y.toFixed(4)} ${kVector.z.toFixed(4)}

   ' Magnetic Atoms
${atoms.map(a => `   site ${a.label} num_posns 1 x ${a.x.toFixed(4)} y ${a.y.toFixed(4)} z ${a.z.toFixed(4)} beq ${a.B_iso.toFixed(2)} occ ${a.element} 1.0 mx @ ${(a.mx || 0).toFixed(3)} my @ ${(a.my || 0).toFixed(3)} mz @ ${(a.mz || 0).toFixed(3)}`).join('\n')}
`;
  };

  const generatePythonMantid = () => {
    return `# Mantid / McPhase Python Script - Magnetic Neutron Analysis
import numpy as np
import matplotlib.pyplot as plt

# 1. Crystallographic & Magnetic Parameters
wavelength = ${wavelength.toFixed(4)} # Angstroms
lattice = {'a': ${lattice.a}, 'b': ${lattice.b}, 'c': ${lattice.c}}
k_vector = np.array([${kVector.x}, ${kVector.y}, ${kVector.z}])
temperature = ${temperature} # Kelvin
T_critical = ${criticalTemp} # Kelvin

# 2. Magnetic Moments array (in Bohr Magnetons)
moments = {
${atoms.map(a => `    '${a.label}': np.array([${a.mx || 0}, ${a.my || 0}, ${a.mz || 0}])`).join(',\n')}
}

# 3. Calculated Bragg Reflections (Two-Theta, Intensity)
reflections = [
${reflections.slice(0, 15).map(r => `    {'hkl': ${JSON.stringify(r.hkl)}, '2theta': ${r.twoTheta.toFixed(3)}, 'I_nuc': ${r.nuclearIntensity.toFixed(2)}, 'I_mag': ${r.magneticIntensity.toFixed(2)}}`).join(',\n')}
]

print(f"Magnetic Order: ${metrics.orderType}")
print(f"Total Sublattice Moment at {temperature}K: ${metrics.totalSublatticeMomentT.toFixed(3)} mu_B")
print(f"Computed {len(reflections)} magnetic + nuclear reflections.")
`;
  };

  const getExportCode = () => {
    switch (exportFormat) {
      case 'fullprof': return generateFullProfPCR();
      case 'mcif': return generateMCIF();
      case 'topas': return generateTOPAS();
      case 'python_mantid': return generatePythonMantid();
      default: return generateFullProfPCR();
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(getExportCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const code = getExportCode();
    const ext = exportFormat === 'mcif' ? 'mcif' : (exportFormat === 'python_mantid' ? 'py' : (exportFormat === 'fullprof' ? 'pcr' : 'inp'));
    const blob = new Blob([code], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `magnetic_diffraction_${exportFormat}.${ext}`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-slate-900/90 rounded-3xl border border-indigo-500/20 p-5 shadow-2xl relative overflow-hidden text-left backdrop-blur-md">
      <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
        <div className="flex items-center gap-2.5">
          <div className="p-2 bg-gradient-to-br from-blue-500/20 to-indigo-500/20 rounded-xl border border-blue-500/30">
            <Code2 className="w-5 h-5 text-blue-400" />
          </div>
          <div>
            <h3 className="text-xs font-black uppercase tracking-wider text-white">
              Magnetic Exporter (FullProf • mCIF • TOPAS • Python)
            </h3>
            <p className="text-[10px] text-slate-400">
              Export standard input files for Rietveld software and scientific computing
            </p>
          </div>
        </div>

        {/* Format selectors & action buttons */}
        <div className="flex flex-wrap items-center gap-2">
          <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800">
            {(['fullprof', 'mcif', 'topas', 'python_mantid'] as const).map(fmt => (
              <button
                key={fmt}
                onClick={() => setExportFormat(fmt)}
                className={`px-2.5 py-1 rounded-lg text-[10px] font-mono font-bold uppercase transition-all ${
                  exportFormat === fmt ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-white'
                }`}
              >
                {fmt === 'python_mantid' ? 'Python' : fmt}
              </button>
            ))}
          </div>

          <button
            onClick={handleCopy}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-bold transition-all"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied!' : 'Copy'}</span>
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold transition-all shadow-lg shadow-indigo-500/20"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download</span>
          </button>
        </div>
      </div>

      {/* Code viewer */}
      <div className="relative bg-[#060a14] rounded-2xl border border-slate-800 p-4 font-mono text-xs text-slate-300 overflow-x-auto max-h-[260px] shadow-inner">
        <pre>{getExportCode()}</pre>
      </div>
    </div>
  );
};
