// Predefined multi-phase mixture patterns and single-phase search keys for Deep Learning XRD analysis

export interface ExampleMixture {
  data: string;
  searchTerm: string;
}

export const EXAMPLE_MIXTURES: Record<string, ExampleMixture> = {
  "Mixture": {
    data: ``,
    searchTerm: "Mixture (SiO2 + Au)",
  },
  "Complex": {
    data: ``,
    searchTerm: "ICSD-15598: Complex (Quartz + Rutile + Anatase + Ag)",
  },
  "Modern-Ceramic": {
    data: ``,
    searchTerm: "Modern Ceramic (TiC + ZrO2)",
  },
  "Solar-Mix": {
    data: ``,
    searchTerm: "Solar Mix (Hybrid MAPbI3 + Inorganic CsPbI3)",
  },
  "Cathode-Mix": {
    data: ``,
    searchTerm: "Cathode Mix (LCO + NMC-111)",
  },
  "Geological-Suite": {
    data: ``,
    searchTerm: "Geological-Suite",
  },
  "Catalyst-Mix": {
    data: ``,
    searchTerm: "Catalyst Mix (CeO2 + Rutile + Anatase + Ti)",
  },
  "Precious-Metal-Mix": {
    data: ``,
    searchTerm: "Precious Metal Mix (Au + Ag + Cu)",
  },
  "Halide-Mineral-Mix": {
    data: ``,
    searchTerm: "Halide Mineral Mix (Halite + Sylvite + Fluorite)",
  },
  "Iron-Oxide-Mix": {
    data: ``,
    searchTerm: "Iron Oxide Mix (Magnetite + Hematite + Quartz)",
  },
  "Biocoat-Composite-Suite": {
    data: ``,
    searchTerm: "COD-9002220: Implant Suite (HAp + ZrO2)",
  },
  "SOFC-Electrode-Suite": {
    data: ``,
    searchTerm: "ICSD-62295: SOFC (YSZ + SRO)",
  },
  "Aerospace-Armor-Suite": {
    data: ``,
    searchTerm: "ICSD-43221: Aerospace (TiC + Al2O3)",
  },
  "Pharma-Drug-Suite": {
    data: ``,
    searchTerm: "CSD-HXACAN: Pharma (Ibu + Para)",
  },
  "Nuclear-Fuel-Suite": {
    data: ``,
    searchTerm: "ICDD-PDF-4: Nuclear Fuel Suite (UO2 + U3O8)",
  },
  "Battery-Anode-Suite": {
    data: ``,
    searchTerm: "ICSD-76031: Battery (Si + C)",
  },
  "Superconductor-Suite": {
    data: ``,
    searchTerm: "ICSD-65546: Superconductor (YBCO + CuO)",
  },
  "Zeolite-Catalyst-Suite": {
    data: ``,
    searchTerm: "IZA-ZSM5: Zeolite (ZSM-5 + LTA)",
  },
  "Cantor-Alloy-Suite": {
    data: ``,
    searchTerm: "COD-9014004: Cantor Alloy (Fe + Cr + Ni)",
  },
  "Carbon-Steel-Suite": {
    data: ``,
    searchTerm: "ICSD-64795: Steel (Ferrite + Austenite + Fe3C)",
  },
  "Superalloy-Carbide-Suite": {
    data: ``,
    searchTerm: "COD-9011620: Superalloy (Inconel + WC)",
  },
  "Multiferroic-Ceramic-Suite": {
    data: ``,
    searchTerm: "ICSD-188686: Multiferroic (BaTiO3 + CoFe2O4)",
  },
  "Photocatalyst-TiO2-WO3-Suite": {
    data: ``,
    searchTerm: "COD-9004144: Photocatalytic (TiO2 + WO3)",
  },
  "Nanocomposite-2D-Energy-Suite": {
    data: ``,
    searchTerm: "COD-4513689: 2D Composite (MXene + MoS2 + GO)",
  },
  "Carbon-Allotropes-Hybrid-Suite": {
    data: ``,
    searchTerm: "COD-9012290: Carbon Allotropes (Diamond + Graphite + GO)",
  },
  "Carbon-Carbide-Refractory-Suite": {
    data: ``,
    searchTerm: "ICSD-16997: Refractory (Graphite + SiC + B4C)",
  },
  "Biomineral-Carbonate-Suite": {
    data: ``,
    searchTerm: "RRUFF-R050512: Biomineral (HAp + CaCO3)",
  },
  "Drug-Carrier-Suite": {
    data: `0.9, 80\\n1.6, 25\\n1.8, 20\\n2.1, 100\\n3.6, 12\\n4.2, 8`,
    searchTerm: "ICDD-PDF-4: Drug Carrier (SBA-15 + MCM-41)",
  },
  "Dental-Implant-Composite": {
    data: ``,
    searchTerm: "RRUFF-R060180: Dental Ceramic (ZrO2 + Al2O3 + HAp)",
  },
  "HEA-Brass-Suite": {
    data: ``,
    searchTerm: "ICSD-108343: HEA Brass (Cu-Zn + Fe + Ni)",
  },
  "Cement-Clinker-Suite": {
    data: ``,
    searchTerm: "COD-9011942: Cement Clinker (Alite + Calcite)",
  },
  "Clay-Mineral-Suite": {
    data: ``,
    searchTerm: "Clay-Mineral-Suite",
  },
  "Battery-Cathode-Suite": {
    data: `18.6, 100\\n36.6, 40\\n44.4, 60\\n64.8, 30`,
    searchTerm: "ICSD-181156: NMC Cathode (LiNiMnCoO2 + LiCoO2)",
  },
  "Archaeological-Pigment-Suite": {
    data: ``,
    searchTerm: "COD-9015949: Ancient Pigment (Egyptian Blue + Malachite)",
  },
  "Zeolite-Adsorbent-Suite": {
    data: ``,
    searchTerm: "Zeolite-Adsorbent-Suite",
  },
  "Lunar-Regolith-Simulant": {
    data: ``,
    searchTerm: "Lunar-Regolith-Simulant",
  },
  "Pharmaceutical-Polymorph-Mixture": {
    data: ``,
    searchTerm: "CSD-ACSALA: Pharma Polymorphs (Paracetamol Form I + Form II)",
  },
  "Bone-Scaffold-Bioactive": {
    data: ``,
    searchTerm: "COD-9010050: Bone Scaffold (HAp + beta-TCP)",
  },
  "Dental-Calcium-Phosphate-Cement": {
    data: ``,
    searchTerm: "COD-3001020: Dental CPC Cement (TTCP + Brushite DCPD)",
  },
  "Bioglass-45S5-Bone-Graft": {
    data: ``,
    searchTerm: "AMS-000451: Bioglass 45S5 + Hydroxyapatite HCA Graft",
  },
  "Pharma-Solid-Tablet-Formulation": {
    data: ``,
    searchTerm: "CSD-LAKTOS01: Solid Tablet (Paracetamol API + Lactose + MCC)",
  },
  "Meteorite-Chondrite-Suite": {
    data: ``,
    searchTerm: "RRUFF-R040026: Meteorite Minerals (Olivine + Kamacite)",
  },
  "Solid-State-Electrolyte-Suite": {
    data: ``,
    searchTerm: "ICSD-185799: Solid State Electrolyte (LLZO + ZrO2)",
  },
  "Earth-Mantle-Assemblage": {
    data: ``,
    searchTerm: "Earth-Mantle-Assemblage",
  },
  "Semiconductor-Hetero-Suite": {
    data: ``,
    searchTerm: "ICSD-151025: III-V Semiconductor GaAs-GaN-AlN",
  },
  "Nuclear-Waste-Pyrochlore": {
    data: ``,
    searchTerm: "COD-9000185: Nuclear Waste Pyrochlore Refractory",
  },
  "Superconducting-Tape-HTS": {
    data: ``,
    searchTerm: "ICSD-65546: HTS Tape (YBCO + CeO2 + SrTiO3)",
  },
  "Mars-Soil-Curiosity": {
    data: ``,
    searchTerm: "RRUFF-R040031: Mars Regolith (Plagioclase + Olivine)",
  },
  "Corrosion-Rust-Scale": {
    data: ``,
    searchTerm: "COD-1011267: Corrosion Rust Scale (Hematite + Goethite)",
  },
  "Asbestos-Mineralogy": {
    data: ``,
    searchTerm: "RRUFF-R060166: Asbestos Hazard (Chrysotile + Amosite)",
  },
  "Volcanic-Ash-Tephra": {
    data: `22.1, 40\\n27.8, 100\\n29.4, 45\\n35.6, 60\\n42.1, 20`,
    searchTerm: "RRUFF-R050013: Volcanic Ash (Plagioclase + Augite)",
  },
  "Fly-Ash-Geopolymer": {
    data: `16.2, 35\\n26.64, 100\\n33.2, 50\\n35.6, 70\\n40.8, 30`,
    searchTerm: "COD-9001569: Geopolymer Fly Ash (Mullite + Hematite)",
  },
  "Solar-Cell-Perovskite-Degradation": {
    data: ``,
    searchTerm: "COD-4336146: Perovskite Degradation (MAPbI3 + PbI2)",
  },
  "Kidney-Stone-Urolithiasis": {
    data: ``,
    searchTerm: "COD-1011110: Kidney Stone (Whewellite + Weddellite)",
  },
  "ASR-Cement-Suite": {
    data: ``,
    searchTerm: "ASR-Cement-Suite",
  },
  "Li-S-Battery-Suite": {
    data: ``,
    searchTerm: "Li-S-Battery-Suite",
  },
  "MXene-Supercap-Suite": {
    data: ``,
    searchTerm: "MXene-Supercap-Suite",
  },
  "Greenschist-Facies-Suite": {
    data: ``,
    searchTerm: "Greenschist-Facies-Suite",
  },
  "Atmospheric-Aerosol-Dust": {
    data: ``,
    searchTerm: "Atmospheric-Aerosol-Dust",
  },
  "Deep-Ocean-Manganese-Nodule": {
    data: ``,
    searchTerm: "Deep-Ocean-Manganese-Nodule",
  },
  "Hydrothermal-Vent-Precipitate": {
    data: ``,
    searchTerm: "Hydrothermal-Vent-Precipitate",
  },
  "Banded-Iron-Formation": {
    data: ``,
    searchTerm: "Banded-Iron-Formation",
  },
  "Portland-Cement-Hydration": {
    data: `18.1, 100\\n34.2, 60\\n47.2, 35\\n50.8, 20\\n54.4, 10`,
    searchTerm: "Portland-Cement-Hydration",
  },
  "Lithium-Ion-SEI-Layer": {
    data: ``,
    searchTerm: "COD-SEI: Li-Ion SEI Layer (Li2CO3 + LiF + PEDOT)",
  },
  "Solid-Oxide-Electrolysis-Cell": {
    data: ``,
    searchTerm: "ICSD-SOEC: SOEC Cathode (LSCF + GDC + YSZ)",
  },
  "Heavy-Mineral-Sand": {
    data: ``,
    searchTerm: "Heavy-Mineral-Sand",
  },
  "Geothermal-Pipe-Scaling": {
    data: ``,
    searchTerm: "COD-GEO: Geothermal Scale (Silica + Calcite + Stibnite)",
  },
  "Bauxite-Al-Ore": {
    data: ``,
    searchTerm: "RRUFF-BAUX: Bauxite Ore (Gibbsite + Boehmite + Hematite)",
  },
  "Copper-Porphyry-Ore": {
    data: ``,
    searchTerm: "Copper-Porphyry-Ore",
  },
  "Superalloy-Oxidation-Scale": {
    data: ``,
    searchTerm: "COD-SCALE: Superalloy Scale (Cr2O3 + NiO + Spinel)",
  },
  "Tribological-Wear-Debris": {
    data: `35.6, 50\\n43.2, 30\\n44.5, 100\\n65.2, 15\\n82.1, 10`,
    searchTerm: "COD-WEAR: Wear Debris (Alpha-Fe + Fe3O4 + Graphite)",
  },
  "High-Entropy-Alloy-Oxidation": {
    data: `35.8, 100\\n43.8, 50\\n44.4, 80\\n51.6, 30\\n75.2, 20`,
    searchTerm: "ICSD-HEA: HEA Scale (AlCoCrFeNi + Al2O3 + Cr2O3)",
  },
  "Hypersonic-Ablation-Layer": {
    data: ``,
    searchTerm: "COD-UHTC: Ablation Layer (HfB2 + SiC + m-ZrO2)",
  },
  "Fusion-Reactor-First-Wall": {
    data: `26.5, 30\\n40.2, 100\\n44.6, 45\\n54.2, 25\\n58.3, 80`,
    searchTerm: "ICSD-FW: Fusion First Wall (W + Be + Graphite)",
  },
  "Solder-Joint-Intermetallic": {
    data: ``,
    searchTerm: "COD-IMC: Solder Interface (Cu6Sn5 + Cu3Sn + Ag3Sn)",
  },
  "Bronze-Disease-Corrosion": {
    data: ``,
    searchTerm: "Bronze-Disease-Corrosion",
  },
  "Geopolymer-Binder-Phase": {
    data: ``,
    searchTerm: "COD-GEO: Geopolymer Binder (N-A-S-H + Sodalite + Quartz)",
  },
};

export const EXAMPLE_MATERIAL_SEARCH_MAP: Record<string, string> = {
  "HAP-Sintered": "Hydroxyapatite (Sintered)",
  "HAP-Nano": "Hydroxyapatite (Nano)",
  "Carbonated-HAP": "Carbonated Hydroxyapatite",
  "Dental-HAP": "Hydroxyapatite (Dental Enamel)",
  "Dentin-HAP": "Hydroxyapatite (Human Dentin)",
  "Mg-HAP": "Magnesium-Doped HAp",
  "Si-HAP": "Silicon-substituted HAp",
  "Pb-HAP": "Lead-doped HAp",
  "Cd-HAP": "Cadmium-doped HAp",
  "Magnetite-Hyper": "Magnetite (Hyperthermia)",
  "Cobalt-Ferrite": "Cobalt Ferrite",
  "Maghemite": "Maghemite",
  "Zn-Ferrite": "Zinc-doped Ferrite",
  "LMO": "Lithium Manganese Oxide",
  "HfO2": "Hafnium Oxide",
  "SAC305": "Lead-Free Solder",
  "Ta2O5": "Tantalum Pentoxide",
  "SWCNT": "Single-Walled Carbon Nanotubes",
  "Phosphorene": "Black Phosphorus",
  "IGZO": "Indium Gallium Zinc Oxide",
  "SPIONs": "Superparamagnetic Iron Oxide Nanoparticles",
  "MSN": "Mesoporous Silica Nanoparticles",
  "AgNPs": "Silver Nanoparticles",
  "Mo": "Molybdenum",
  "Ir": "Iridium",
  "Os": "Osmium",
  "Rh": "Rhodium",
  "PuDelta": "Plutonium (Delta Phase)",
  "PuAlpha": "Plutonium (Alpha Phase)",
  "PuO2": "Plutonium Dioxide (PuO2)",
  "BNNT": "BNNT (Boron Nitride Nanotubes)",
  "GdYSZ": "Gd-YSZ (Gadolinia-doped Zirconia)",
  "U3Si5": "U3Si5 Fuel",
  "TritiumScavenger": "Tritium Scavenger (ZrCo)",
  "HypersonicAblator": "Hypersonic Ablator (HfB2)",
  "VitrifiedNuclearWaste": "Vitrified Nuclear Waste (Borosilicate)",
  "AramidBodyArmor": "Aramid Body Armor (Kevlar)",
  "ReactiveArmorExplosive": "Reactive Armor Explosive (RDX)",
  "DepletedUraniumAlloy": "Depleted Uranium Alloy (DU-0.75Ti)",
  "SiCSiC": "SiC-SiC Composite",
  "LaBr3Ce": "LaBr3:Ce Scintillator",
  "TiCN": "TiCN Defensive Armor",
  "UO2": "Uranium Dioxide",
  "U3O8": "Triuranium Octoxide",
  "UO3": "Uranium Trioxide",
  "U-Metal": "Alpha-Uranium Metal",
  "LiTaO3": "Lithium Tantalate",
  "LiNbO3": "Lithium Niobate",
  "PbS": "Lead Sulphide",
  "ZnTe": "Zinc Telluride",
  "LaAlO3": "Lanthanum Aluminate",
  "Cu2O": "Cuprite",
  "CdSe": "Cadmium Selenide",
  "SiO": "Silicon Monoxide",
  "Y2O3": "Yttrium Oxide",
  "BaZrO3": "Barium Zirconate",
  "NASICON": "NASICON",
  "TiS2": "Titanium Disulfide",
  "ACP": "Amorphous Calcium Phosphate",
  "Bio-Glass-1393": "Bioactive Glass (13-93)",
  "Bio-Glass-S53P4": "Bioactive Glass (S53P4)",
  "Bioactive Glass": "Bioactive Glass (45S5)",
  "Fluorapatite": "Fluorapatite",
  "Sr-HAP": "Strontium-Apatite",
  "Chlorapatite": "Chlorapatite",
  "PbTiO3": "Lead Titanate",
  "LTA": "Zeolite A",
  "YAG": "Yttrium Aluminum Garnet",
  "SrTiO3": "Strontium Titanate",
  "LFP": "Lithium Iron Phosphate",
  "GaN": "Gallium Nitride",
  "Au": "Gold",
  "Fe": "Iron - Alpha",
  "Ni": "Nickel",
  "WC": "Tungsten Carbide",
  "Fe3O4": "Magnetite",
  "MAPbI3": "Methylammonium Lead Iodide",
  "SiC": "Silicon Carbide",
  "GaAs": "Gallium Arsenide",
  "BFO": "Bismuth Ferrite",
  "B4C": "Boron Carbide (B4C)",
  "ZrB2": "Zirconium Diboride (ZrB2)",
  "HfB2": "Hafnium Diboride (HfB2)",
  "TiB2": "Titanium Diboride (TiB2)",
  "U3Si2": "Uranium Silicide (U3Si2)",
  "Gd2O3": "Gadolinium Oxide (Gd2O3)",
  "Er2O3": "Erbium Oxide (Er2O3)",
  "AgInCd": "Ag-In-Cd Alloy (80-15-5)",
  "Kevlar": "Kevlar (PPTA)",
  "UHMWPE": "UHMWPE (Dyneema/Spectra)",
  "ALON": "Aluminum Oxynitride (ALON)",
  "Spinel": "Magnesium Aluminate Spinel",
  "Sm2O3": "Samarium Oxide (Sm2O3)",
  "PbWO4": "Lead Tungstate (PbWO4)",
  "CdWO4": "Cadmium Tungstate (CdWO4)",
  "BeO": "Beryllium Oxide (BeO)",
  "ZrC": "Zirconium Carbide (ZrC)",
  "BGO": "Bismuth Germanate (BGO)",
  "NaITl": "Sodium Iodide doped with Thallium (NaI:Tl)",
  "ZrH2": "Zirconium Hydride (ZrH2)",
  "ITO": "Indium Tin Oxide",
  "FeS2": "Pyrite",
  "Cr": "Chromium",
  "Ga2O3": "Gallium Oxide",
  "CdTe": "Cadmium Telluride",
  "Bi2Te3": "Bismuth Telluride",
  "SnO2": "Tin Oxide",
  "LCO": "Lithium Cobalt Oxide",
  "Si3N4": "Silicon Nitride",
  "AlN": "Aluminum Nitride",
  "hBN": "Boron Nitride",
  "GaP": "Gallium Phosphide",
  "ZnSe": "Zinc Selenide",
  "Ta": "Tantalum",
  "V2O5": "Vanadium Pentoxide",
  "AgCl": "Silver Chloride",
  "MnO2": "Manganese Oxide",
  "PTFE": "Polytetrafluoroethylene",
  "PbO": "Lead(II) Oxide (Litharge)",
  "Bi2O3": "Bismuth(III) Oxide",
  "Sb2O3": "Antimony Trioxide",
  "TeO2": "Tellurium Dioxide",
  "GeO2": "Germanium Dioxide",
  "Sc2O3": "Scandium(III) Oxide",
  "Lu2O3": "Lutetium(III) Oxide",
  "Nb2O5": "Niobium Pentoxide",
  "FeO": "Wüstite (FeO)",
  "LiF": "Lithium Fluoride",
  "NaF": "Sodium Fluoride",
  "MgF2": "Magnesium Fluoride",
  "AlF3": "Aluminum Fluoride",
  "KBr": "Potassium Bromide",
  "KI": "Potassium Iodide",
  "CsI": "Cesium Iodide",
  "CsCl": "Cesium Chloride",
  "AgBr": "Silver Bromide",
  "CuI": "Copper(I) Iodide",
  "PbI2": "Lead(II) Iodide",
  "NaBr": "Sodium Bromide",
  "NaI": "Sodium Iodide",
  "CuCl": "Copper(I) Chloride",
  "LiCl": "Lithium Chloride",
  "MgCl2": "Magnesium Chloride",
  "CaCl2": "Calcium Chloride",
  "BaO": "Barium Oxide",
  "SrO": "Strontium Oxide",
  "NaCl": "Halite",
  "KCl": "Sylvite",
  "CaF2": "Calcium Fluoride",
  "In2O3": "Indium(III) Oxide (In2O3)",
  "PbF2": "Lead(II) Fluoride (PbF2)",
  "TlBr": "Thallium(I) Bromide (TlBr)",
  "ZrO2": "Zirconia",
  "Graphite": "Graphite",
  "Hematite": "Hematite",
  "MgO": "Magnesium Oxide",
  "CeO2": "Cerium Oxide",
  "Calcite": "Calcite",
  "Tungsten": "Tungsten",
  "Quartz": "Quartz",
  "Beta-Quartz": "Beta-Quartz (High Quartz, SiO2)",
  "Alpha-Cristobalite": "Alpha-Cristobalite (Low Cristobalite, SiO2)",
  "Beta-Cristobalite": "Beta-Cristobalite (High Cristobalite, SiO2)",
  "Alpha-Tridymite": "Alpha-Tridymite (Low Tridymite, SiO2)",
  "Beta-Tridymite": "Beta-Tridymite (High Tridymite, SiO2)",
  "Keatite": "Keatite (SiO2 Synthetic Polymorph)",
  "Moganite": "Moganite (SiO2 Monoclinic Polymorph)",
  "Stishovite": "Stishovite (SiO2 High-Pressure Polymorph)",
  "Seifertite": "Seifertite (SiO2 Ultra-High-Pressure)",
  "Diamond": "Diamond",
  "Rutile": "Rutile",
  "Anatase": "Anatase",
  "BaTiO3": "Barium Titanate",
  "MoS2": "Molybdenum Disulfide",
  "Corundum": "Corundum",
  "TTCP": "Tetracalcium Phosphate",
  "PZT": "Lead Zirconate Titanate",
  "ZnS": "Zinc Sulfide",
  "BaFe12O19": "Barium Ferrite",
  "WO3": "Tungsten Trioxide",
  "VO2": "Vanadium Dioxide",
  "Ag2O": "Silver(I) Oxide",
  "CuO": "Copper(II) Oxide",
  "NiO": "Nickel Oxide",
  "Co3O4": "Cobalt(II,III) Oxide",
  "LTO": "Lithium Titanate",
  "YBCO": "YBCO Superconductor",
  "ZSM5": "Zeolite ZSM-5",
  "MOF5": "Metal-Organic Framework-5",
  "Pt": "Platinum",
  "Pd": "Palladium",
  "NMC": "NMC-111",
  "YSZ": "Yttria-Stabilized Zirconia",
  "SRO": "Strontium Ruthenate",
  "GO": "Graphene Oxide",
  "OCP": "Octacalcium Phosphate",
  "Cellulose": "Cellulose",
  "Chitosan": "Chitosan",
  "Silk": "Silk Fibroin",
  "Whewellite": "Calcium Oxalate",
  "PLA": "Polylactic Acid",
  "PEEK": "Polyether ether ketone",
  "Collagen": "Collagen Type I",
  "ThO2": "Thorium Dioxide",
  "Zircaloy": "Zircaloy-4",
  "NuclearGraphite": "Nuclear Graphite",
  "Nd2Fe14B": "Neodymium Magnet",
  "TiC": "Titanium Carbide",
  "Cr2O3": "Chromium(III) Oxide",
  "CoFe2O4": "Cobalt Ferrite",
  "BiOCl": "Bismuth Oxychloride",
  "CsPbI3": "Cesium Lead Iodide",
  "Ti3C2": "Titanium MXene",
  "UiO66": "UiO-66",
  "HKUST1": "HKUST-1",
  "MoO3": "Molybdenum Trioxide",
  "V2O3": "Vanadium(III) Oxide",
  "PerovskiteCat": "Perovskite (CaTiO3)",
  "Feldspar": "Feldspar (Orthoclase)",
  "SS316L": "Stainless Steel 316L",
  "SS304": "Stainless Steel 304",
  "SS310": "Stainless Steel 310",
  "SS430": "Stainless Steel 430",
  "SS174PH": "Stainless Steel 17-4PH",
  "Duplex2205": "Duplex Stainless Steel 2205",
  "HastelloyC276": "Hastelloy C-276",
  "ToolSteelH13": "Tool Steel H13",
  "FeCrAlKanthal": "FeCrAl Alloy (Kanthal APM)",
  "AlCoCrFeNiHEA": "High-Entropy Alloy (AlCoCrFeNi)",
  "Ti64": "Ti-6Al-4V (Grade 5)",
  "Brass": "Brass (C26000)",
  "TiGrade2": "Titanium (Ti)",
  "AZ31B": "Magnesium Alloy (AZ31B)",
  "Al7075": "Aluminum Alloy (7075-T6)",
  "CoCrMo": "Cobalt-Chrome (CoCrMo)",
  "Nitinol": "Nitinol (NiTi Shape Memory)",
  "Zircaloy2": "Zircaloy-2",
  "HastelloyX": "Hastelloy X",
  "Monel400": "Monel 400",
  "Maraging300": "Maraging Steel (Grade 300)",
  "Beryllium": "Beryllium (Be)",
  "Vanadium": "Vanadium (V)",
  "Niobium": "Niobium (Nb)",
  "Zirconium": "Zirconium (Zr)",
  "Magnesium": "Magnesium (Mg)",
  "Tin": "Tin (Sn)",
  "Zinc": "Zinc (Zn)",
  "Lead": "Lead (Pb)",
  "PoloniumEl": "Polonium (Po)",
  "CastIron": "Cast Iron (Grey)",
  "A36Steel": "A36 Structural Steel",
  "O1ToolSteel": "O1 Tool Steel",
  "Constantan": "Constantan",
  "Kovar": "Kovar",
  "Nichrome": "Nichrome",
  "BabbittMetal": "Babbitt Metal",
  "Duralumin": "Duralumin",
  "Dexamethasone": "Dexamethasone",
  "Metformin Hydrochloride": "Metformin Hydrochloride",
  "Omeprazole": "Omeprazole",
  "Ciprofloxacin": "Ciprofloxacin",
  "Azithromycin (Dihydrate)": "Azithromycin (Dihydrate)",
  "Amlodipine Besylate": "Amlodipine Besylate",
  "Simvastatin": "Simvastatin",
  "Losartan Potassium": "Losartan Potassium",
  "Cetirizine Hydrochloride": "Cetirizine Hydrochloride",
  "Fluconazole": "Fluconazole",
  "Ampicillin Trihydrate": "Ampicillin Trihydrate",
  "Pantoprazole Sodium": "Pantoprazole Sodium",
  "Valsartan": "Valsartan",
  "Loratadine": "Loratadine",
  "Glipizide": "Glipizide",
  "Erythromycin": "Erythromycin",
  "Tetracycline Hydrochloride": "Tetracycline Hydrochloride",
  "Rosuvastatin Calcium": "Rosuvastatin Calcium",
  "Ranitidine Hydrochloride": "Ranitidine Hydrochloride",
  "Prednisolone": "Prednisolone",
  "Hydrocortisone": "Hydrocortisone",
  "AlSb": "AlSb Semiconductor",
  "MoTe2": "MoTe2 Monolayer",
  "BaSnO3": "Barium Stannate Perovskite",
  "Sb2Se3": "Sb2Se3 Photovoltaic Absorber",
  "CZTS": "CZTS Kesterite",
  "Fe3GeTe2": "Fe3GeTe2 Layered Ferromagnet",
  "LLZO": "LLZO (Li7La3Zr2O12)",
  "LGPS": "LGPS (Li10GeP2S12)",
  "LATP": "LATP (Li1.3Al0.3Ti1.7(PO4)3)",
  "FAPbI3": "FAPbI3 Perovskite",
  "PrussianBlueNa": "Prussian Blue Na-Cathode",
  "MgH2": "Magnesium Hydride",
  "Inconel": "Inconel 718",
  "SBA15": "SBA-15",
  "MCM41": "MCM-41",
  "ZIF8": "ZIF-8",
  "Ibuprofen": "Ibuprofen",
  "Paracetamol": "Paracetamol",
  "ZTA": "Zirconia Toughened Alumina (ZTA)",
  "YTZP": "Y-TZP (Yttria-stabilized Zirconia)",
  "Alginate": "Alginate",
  "HyaluronicAcid": "Hyaluronic Acid (HA)",
  "Caffeine": "Caffeine (Anhydrous)",
  "AscorbicAcid": "Ascorbic Acid (Vitamin C)",
  "Sucrose": "Sucrose (Sugar)",
  "Cholesterol": "Cholesterol",
  "Carbamazepine": "Carbamazepine (Form III)",
  "Theophylline": "Theophylline (Anhydrous)",
  "Naproxen": "Naproxen (S-Naproxen)",
  "Diclofenac": "Diclofenac Sodium",
  "Aspirin": "Aspirin (Acetylsalicylic Acid)",
  "Amoxicillin": "Amoxicillin Trihydrate",
  "MgTCP": "Mg-Substituted beta-TCP (Mg-TCP)",
  "SrTCP": "Sr-Substituted beta-TCP (Sr-TCP)",
  "ZnHAp": "Zn-Substituted HAp (Zn-HAp)",
  "BariumSulfate": "Barium Sulfate",
  "PMMA": "Polymethyl Methacrylate (PMMA)",
  "PCL": "Polycaprolactone (PCL)",
  "PLGA": "Poly(lactic-co-glycolic acid) (PLGA)",
  "TiO2Nano": "TiO2 Nanotubes (Biomedical)",
  "CaSO4Hemi": "Calcium Sulfate Hemihydrate",
  "CaSO4Di": "Calcium Sulfate Dihydrate",
  "Whitlockite": "Whitlockite",
  "Meloxicam": "Meloxicam",
  "Curcumin": "Curcumin",
  "CoralAragoniteScaffold": "Coral Aragonite Scaffold",
  "PyrolyticCarbon": "Pyrolytic Carbon",
  "AkermaniteCeramic": "Akermanite Ceramic",
  "AWGlassCeramic": "A-W Glass-ceramic",
  "AtorvastatinCalcium": "Atorvastatin Calcium",
  "BiphasicCalciumPhosphate": "Biphasic Calcium Phosphate (HAp/beta-TCP)",
  "PaclitaxelTaxol": "Paclitaxel Crystalline Form I (Taxol)",
  "GelMABioInk": "Gelatin Methacryloyl (GelMA) Bio-Ink",
  "BetaChitin": "Beta-Chitin Diatomaceous Biomaterial",
  "BaghdaditeCeramic": "Baghdadite Ceramic",
  "StruviteCement": "Struvite Bone Cement (MgNH4PO4·6H2O)",
  "PiroxicamFormI": "Piroxicam Crystalline Form I",
  "GOBioNanosheet": "Graphene Oxide Bio-Nanosheet",
  "CBDCrystalline": "Cannabidiol Crystalline Polymorph",
  "UO2F2": "Uranyl Fluoride (UO2F2)",
  "Ag2F": "Silver Subfluoride (Ag2F)",
  "YbOF": "Ytterbium(III) Oxyfluoride (YbOF)",
  "NIST1976": "NIST SRM 1976 (Corundum / α-Al2O3)",
  "NIST640": "NIST SRM 640 (Silicon Profile Standard)",
  "NIST660": "NIST SRM 660 (Lanthanum Hexaboride, LaB6)",
  "NIST676": "NIST SRM 676 (Alumina Phase Quant Standard)",
  "NIST674": "NIST SRM 674b (TiO2/ZnO/Cr2O3/CeO2)",
  "BiOI": "Bismuth Oxyiodide (BiOI)",
  "ReO3": "Rhenium Trioxide (ReO3)",
  "SS904L": "Stainless Steel 904L",
  "Ti15Mo": "Ti-15Mo High-Beta Alloy",
  "Invar36": "Invar 36 Low-Expansion Alloy",
  "Stellite6": "Stellite 6 Cobalt-Base Alloy",
  "ElectricalSteel": "Electrical Steel (Fe-Si)",
  "Permalloy": "Permalloy (Ni-Fe)",
  "PhosphorBronze": "Bronze (Phosphor Bronze)",
  "BerylliumCopper": "Beryllium Copper (C17200)",
  "MgWE43": "Magnesium Alloy WE43",
  "Ta10W": "Tantalum-10W Alloy",
  "Nb3Sn": "Niobium-Tin (Nb3Sn)",
  "Cuprite": "Cuprite (Cu2O)",
  "Chalcocite": "Chalcocite (Cu2S)",
  "CartridgeBrass": "Cartridge Brass C2600",
  "Cupronickel7030": "Cupronickel 70-30",
  "ZTAFemoralJoint": "ZTA Femoral Joint",
  "Magnetite": "Magnetite (Fe3O4)",
  "PE": "Polyethylene (PE)",
  "Cement": "Portland Cement (Alite)",
  "Olivine": "Olivine (Forsterite)",
  "Pyroxene": "Pyroxene (Enstatite)",
  "Biotite": "Biotite",
  "Muscovite": "Muscovite",
  "Kaolinite": "Kaolinite",
  "Moissanite": "Moissanite (SiC)",
  "Diopside": "Diopside",
  "Lonsdaleite": "Lonsdaleite (Hex. Diamond)",
  "Shungite": "Shungite",
  "AndraditeGarnet": "Andradite Garnet (Ca3Fe2(SiO4)3)",
  "Coesite": "Coesite (SiO2 High-Pressure Polymorph)",
  "Chaoite": "Chaoite (White Carbon Allotrope)",
  "Wurtzite": "Wurtzite (Hexagonal ZnS)",
  "Crocidolite": "Crocidolite (Blue Asbestos Amphibole)",
  "Montmorillonite": "Montmorillonite",
  "Illite": "Illite",
  "Dolomite": "Dolomite",
  "Aragonite": "Aragonite",
  "Ilmenite": "Ilmenite",
  "Apatite": "Apatite (Fluorapatite)",
  "Zircon": "Zircon",
  "Tourmaline": "Tourmaline (Schorl)",
  "Beryl": "Beryl",
  "Almandine": "Almandine (Garnet)",
  "Fullerene": "Fullerene (C60)",
  "MWCNT": "Multi-walled Carbon Nanotubes (MWCNT)",
  "HardCarbon": "Hard Carbon",
  "GlassyCarbon": "Glassy Carbon",
  "Anthracite": "Anthracite",
};
