/**
 * Comprehensive Crystallographic & Elemental Metrology Database
 * Contains atomic properties, periodic classifications, electron configurations,
 * Pauling electronegativities, Shannon ionic / covalent radii,
 * and X-ray absorption edges & characteristic emission lines for XRD/XRF metrology.
 */

export interface ElementMetrology {
  symbol: string;
  name: string;
  z: number;
  atomicWeight: number;
  period: number;
  group: number;
  block: 's' | 'p' | 'd' | 'f';
  category:
    | 'Alkali Metal'
    | 'Alkaline Earth'
    | 'Transition Metal'
    | 'Post-Transition Metal'
    | 'Metalloid'
    | 'Reactive Nonmetal'
    | 'Noble Gas'
    | 'Lanthanide'
    | 'Actinide'
    | 'Halogen';
  electronConfig: string;
  valenceElectrons: number;
  electronegativity: number; // Pauling scale
  covalentRadiusPm: number;
  ionicRadiusPm: number; // standard coordination
  commonOxidationStates: number[];
  pureCrystalStructure: string;
  densityGcm3?: number;
  meltingPointK?: number;
  // X-ray Metrology (in keV)
  kEdgeKeV?: number;
  l1EdgeKeV?: number;
  l3EdgeKeV?: number;
  kAlpha1KeV?: number;
  kBeta1KeV?: number;
  // Mass absorption coefficients (cm^2/g) for typical lab wavelengths
  muOverRhoCu?: number; // Cu-Ka (8.048 keV)
  muOverRhoMo?: number; // Mo-Ka (17.48 keV)
  muOverRhoCo?: number; // Co-Ka (6.93 keV)
}

export const ELEMENT_METROLOGY_DB: Record<string, ElementMetrology> = {
  H: {
    symbol: 'H',
    name: 'Hydrogen',
    z: 1,
    atomicWeight: 1.008,
    period: 1,
    group: 1,
    block: 's',
    category: 'Reactive Nonmetal',
    electronConfig: '1s¹',
    valenceElectrons: 1,
    electronegativity: 2.20,
    covalentRadiusPm: 31,
    ionicRadiusPm: -140, // H- (hydride)
    commonOxidationStates: [1, -1],
    pureCrystalStructure: 'Hexagonal (Solid)',
    densityGcm3: 0.00008988,
    meltingPointK: 14.01,
    muOverRhoCu: 0.40,
    muOverRhoMo: 0.38,
    muOverRhoCo: 0.42
  },
  He: {
    symbol: 'He',
    name: 'Helium',
    z: 2,
    atomicWeight: 4.0026,
    period: 1,
    group: 18,
    block: 's',
    category: 'Noble Gas',
    electronConfig: '1s²',
    valenceElectrons: 2,
    electronegativity: 0,
    covalentRadiusPm: 28,
    ionicRadiusPm: 0,
    commonOxidationStates: [0],
    pureCrystalStructure: 'HCP',
    densityGcm3: 0.0001785,
    meltingPointK: 0.95
  },
  Li: {
    symbol: 'Li',
    name: 'Lithium',
    z: 3,
    atomicWeight: 6.94,
    period: 2,
    group: 1,
    block: 's',
    category: 'Alkali Metal',
    electronConfig: '[He] 2s¹',
    valenceElectrons: 1,
    electronegativity: 0.98,
    covalentRadiusPm: 128,
    ionicRadiusPm: 76, // Li+ (VI)
    commonOxidationStates: [1],
    pureCrystalStructure: 'BCC',
    densityGcm3: 0.534,
    meltingPointK: 453.65,
    kEdgeKeV: 0.055,
    muOverRhoCu: 0.65,
    muOverRhoMo: 0.25,
    muOverRhoCo: 0.85
  },
  Be: {
    symbol: 'Be',
    name: 'Beryllium',
    z: 4,
    atomicWeight: 9.0122,
    period: 2,
    group: 2,
    block: 's',
    category: 'Alkaline Earth',
    electronConfig: '[He] 2s²',
    valenceElectrons: 2,
    electronegativity: 1.57,
    covalentRadiusPm: 96,
    ionicRadiusPm: 45, // Be2+ (IV)
    commonOxidationStates: [2],
    pureCrystalStructure: 'HCP',
    densityGcm3: 1.85,
    meltingPointK: 1560,
    kEdgeKeV: 0.111,
    muOverRhoCu: 1.50,
    muOverRhoMo: 0.45,
    muOverRhoCo: 2.10
  },
  B: {
    symbol: 'B',
    name: 'Boron',
    z: 5,
    atomicWeight: 10.81,
    period: 2,
    group: 13,
    block: 'p',
    category: 'Metalloid',
    electronConfig: '[He] 2s² 2p¹',
    valenceElectrons: 3,
    electronegativity: 2.04,
    covalentRadiusPm: 84,
    ionicRadiusPm: 27, // B3+ (IV)
    commonOxidationStates: [3],
    pureCrystalStructure: 'Rhombohedral',
    densityGcm3: 2.34,
    meltingPointK: 2349,
    kEdgeKeV: 0.188,
    muOverRhoCu: 2.45,
    muOverRhoMo: 0.70,
    muOverRhoCo: 3.40
  },
  C: {
    symbol: 'C',
    name: 'Carbon',
    z: 6,
    atomicWeight: 12.011,
    period: 2,
    group: 14,
    block: 'p',
    category: 'Reactive Nonmetal',
    electronConfig: '[He] 2s² 2p²',
    valenceElectrons: 4,
    electronegativity: 2.55,
    covalentRadiusPm: 76,
    ionicRadiusPm: 16, // C4+
    commonOxidationStates: [4, 2, -4],
    pureCrystalStructure: 'Diamond / Hexagonal (Graphite)',
    densityGcm3: 2.267,
    meltingPointK: 3823,
    kEdgeKeV: 0.284,
    muOverRhoCu: 4.60,
    muOverRhoMo: 1.15,
    muOverRhoCo: 6.20
  },
  N: {
    symbol: 'N',
    name: 'Nitrogen',
    z: 7,
    atomicWeight: 14.007,
    period: 2,
    group: 15,
    block: 'p',
    category: 'Reactive Nonmetal',
    electronConfig: '[He] 2s² 2p³',
    valenceElectrons: 5,
    electronegativity: 3.04,
    covalentRadiusPm: 71,
    ionicRadiusPm: 146, // N3-
    commonOxidationStates: [-3, 3, 5],
    pureCrystalStructure: 'Hexagonal (Solid)',
    densityGcm3: 0.00125,
    meltingPointK: 63.15,
    kEdgeKeV: 0.409,
    muOverRhoCu: 7.50,
    muOverRhoMo: 1.70,
    muOverRhoCo: 10.2
  },
  O: {
    symbol: 'O',
    name: 'Oxygen',
    z: 8,
    atomicWeight: 15.999,
    period: 2,
    group: 16,
    block: 'p',
    category: 'Reactive Nonmetal',
    electronConfig: '[He] 2s² 2p⁴',
    valenceElectrons: 6,
    electronegativity: 3.44,
    covalentRadiusPm: 66,
    ionicRadiusPm: 140, // O2- (VI)
    commonOxidationStates: [-2, -1],
    pureCrystalStructure: 'Cubic / Monoclinic (Solid)',
    densityGcm3: 0.001429,
    meltingPointK: 54.36,
    kEdgeKeV: 0.543,
    muOverRhoCu: 11.5,
    muOverRhoMo: 2.50,
    muOverRhoCo: 15.8
  },
  F: {
    symbol: 'F',
    name: 'Fluorine',
    z: 9,
    atomicWeight: 18.998,
    period: 2,
    group: 17,
    block: 'p',
    category: 'Halogen',
    electronConfig: '[He] 2s² 2p⁵',
    valenceElectrons: 7,
    electronegativity: 3.98,
    covalentRadiusPm: 57,
    ionicRadiusPm: 133, // F- (VI)
    commonOxidationStates: [-1],
    pureCrystalStructure: 'Monoclinic',
    densityGcm3: 0.001696,
    meltingPointK: 53.53,
    kEdgeKeV: 0.697,
    muOverRhoCu: 16.5,
    muOverRhoMo: 3.50,
    muOverRhoCo: 22.4
  },
  Ne: {
    symbol: 'Ne',
    name: 'Neon',
    z: 10,
    atomicWeight: 20.180,
    period: 2,
    group: 18,
    block: 'p',
    category: 'Noble Gas',
    electronConfig: '[He] 2s² 2p⁶',
    valenceElectrons: 8,
    electronegativity: 0,
    covalentRadiusPm: 58,
    ionicRadiusPm: 0,
    commonOxidationStates: [0],
    pureCrystalStructure: 'FCC',
    densityGcm3: 0.0009,
    meltingPointK: 24.56,
    kEdgeKeV: 0.870
  },
  Na: {
    symbol: 'Na',
    name: 'Sodium',
    z: 11,
    atomicWeight: 22.990,
    period: 3,
    group: 1,
    block: 's',
    category: 'Alkali Metal',
    electronConfig: '[Ne] 3s¹',
    valenceElectrons: 1,
    electronegativity: 0.93,
    covalentRadiusPm: 166,
    ionicRadiusPm: 102, // Na+ (VI)
    commonOxidationStates: [1],
    pureCrystalStructure: 'BCC',
    densityGcm3: 0.968,
    meltingPointK: 370.94,
    kEdgeKeV: 1.072,
    muOverRhoCu: 30.5,
    muOverRhoMo: 6.20,
    muOverRhoCo: 41.0
  },
  Mg: {
    symbol: 'Mg',
    name: 'Magnesium',
    z: 12,
    atomicWeight: 24.305,
    period: 3,
    group: 2,
    block: 's',
    category: 'Alkaline Earth',
    electronConfig: '[Ne] 3s²',
    valenceElectrons: 2,
    electronegativity: 1.31,
    covalentRadiusPm: 141,
    ionicRadiusPm: 72, // Mg2+ (VI)
    commonOxidationStates: [2],
    pureCrystalStructure: 'HCP',
    densityGcm3: 1.738,
    meltingPointK: 923,
    kEdgeKeV: 1.303,
    muOverRhoCu: 39.5,
    muOverRhoMo: 8.0,
    muOverRhoCo: 53.0
  },
  Al: {
    symbol: 'Al',
    name: 'Aluminium',
    z: 13,
    atomicWeight: 26.982,
    period: 3,
    group: 13,
    block: 'p',
    category: 'Post-Transition Metal',
    electronConfig: '[Ne] 3s² 3p¹',
    valenceElectrons: 3,
    electronegativity: 1.61,
    covalentRadiusPm: 121,
    ionicRadiusPm: 53.5, // Al3+ (VI)
    commonOxidationStates: [3],
    pureCrystalStructure: 'FCC',
    densityGcm3: 2.70,
    meltingPointK: 933.47,
    kEdgeKeV: 1.560,
    kAlpha1KeV: 1.486,
    muOverRhoCu: 49.6,
    muOverRhoMo: 9.95,
    muOverRhoCo: 66.8
  },
  Si: {
    symbol: 'Si',
    name: 'Silicon',
    z: 14,
    atomicWeight: 28.085,
    period: 3,
    group: 14,
    block: 'p',
    category: 'Metalloid',
    electronConfig: '[Ne] 3s² 3p²',
    valenceElectrons: 4,
    electronegativity: 1.90,
    covalentRadiusPm: 111,
    ionicRadiusPm: 40, // Si4+ (VI)
    commonOxidationStates: [4, -4],
    pureCrystalStructure: 'Diamond Cubic',
    densityGcm3: 2.329,
    meltingPointK: 1687,
    kEdgeKeV: 1.839,
    kAlpha1KeV: 1.740,
    muOverRhoCu: 64.1,
    muOverRhoMo: 12.8,
    muOverRhoCo: 86.5
  },
  P: {
    symbol: 'P',
    name: 'Phosphorus',
    z: 15,
    atomicWeight: 30.974,
    period: 3,
    group: 15,
    block: 'p',
    category: 'Reactive Nonmetal',
    electronConfig: '[Ne] 3s² 3p³',
    valenceElectrons: 5,
    electronegativity: 2.19,
    covalentRadiusPm: 107,
    ionicRadiusPm: 38, // P5+ (VI)
    commonOxidationStates: [5, 3, -3],
    pureCrystalStructure: 'Orthorhombic (Black) / Monoclinic',
    densityGcm3: 1.823,
    meltingPointK: 317.3,
    kEdgeKeV: 2.146,
    kAlpha1KeV: 2.013,
    muOverRhoCu: 76.5,
    muOverRhoMo: 15.3,
    muOverRhoCo: 103.0
  },
  S: {
    symbol: 'S',
    name: 'Sulfur',
    z: 16,
    atomicWeight: 32.06,
    period: 3,
    group: 16,
    block: 'p',
    category: 'Reactive Nonmetal',
    electronConfig: '[Ne] 3s² 3p⁴',
    valenceElectrons: 6,
    electronegativity: 2.58,
    covalentRadiusPm: 105,
    ionicRadiusPm: 184, // S2-
    commonOxidationStates: [6, 4, 2, -2],
    pureCrystalStructure: 'Orthorhombic',
    densityGcm3: 2.07,
    meltingPointK: 388.36,
    kEdgeKeV: 2.472,
    kAlpha1KeV: 2.307,
    muOverRhoCu: 92.5,
    muOverRhoMo: 18.7,
    muOverRhoCo: 124.0
  },
  Cl: {
    symbol: 'Cl',
    name: 'Chlorine',
    z: 17,
    atomicWeight: 35.45,
    period: 3,
    group: 17,
    block: 'p',
    category: 'Halogen',
    electronConfig: '[Ne] 3s² 3p⁵',
    valenceElectrons: 7,
    electronegativity: 3.16,
    covalentRadiusPm: 102,
    ionicRadiusPm: 181, // Cl- (VI)
    commonOxidationStates: [-1, 1, 3, 5, 7],
    pureCrystalStructure: 'Orthorhombic (Solid)',
    densityGcm3: 0.003214,
    meltingPointK: 171.6,
    kEdgeKeV: 2.822,
    kAlpha1KeV: 2.622,
    muOverRhoCu: 106.0,
    muOverRhoMo: 21.5,
    muOverRhoCo: 142.0
  },
  Ar: {
    symbol: 'Ar',
    name: 'Argon',
    z: 18,
    atomicWeight: 39.95,
    period: 3,
    group: 18,
    block: 'p',
    category: 'Noble Gas',
    electronConfig: '[Ne] 3s² 3p⁶',
    valenceElectrons: 8,
    electronegativity: 0,
    covalentRadiusPm: 106,
    ionicRadiusPm: 0,
    commonOxidationStates: [0],
    pureCrystalStructure: 'FCC',
    densityGcm3: 0.001784,
    meltingPointK: 83.8,
    kEdgeKeV: 3.206
  },
  K: {
    symbol: 'K',
    name: 'Potassium',
    z: 19,
    atomicWeight: 39.098,
    period: 4,
    group: 1,
    block: 's',
    category: 'Alkali Metal',
    electronConfig: '[Ar] 4s¹',
    valenceElectrons: 1,
    electronegativity: 0.82,
    covalentRadiusPm: 203,
    ionicRadiusPm: 138, // K+ (VI)
    commonOxidationStates: [1],
    pureCrystalStructure: 'BCC',
    densityGcm3: 0.862,
    meltingPointK: 336.53,
    kEdgeKeV: 3.608,
    kAlpha1KeV: 3.314,
    muOverRhoCu: 145.0,
    muOverRhoMo: 29.5,
    muOverRhoCo: 194.0
  },
  Ca: {
    symbol: 'Ca',
    name: 'Calcium',
    z: 20,
    atomicWeight: 40.078,
    period: 4,
    group: 2,
    block: 's',
    category: 'Alkaline Earth',
    electronConfig: '[Ar] 4s²',
    valenceElectrons: 2,
    electronegativity: 1.00,
    covalentRadiusPm: 176,
    ionicRadiusPm: 100, // Ca2+ (VI)
    commonOxidationStates: [2],
    pureCrystalStructure: 'FCC',
    densityGcm3: 1.55,
    meltingPointK: 1115,
    kEdgeKeV: 4.038,
    kAlpha1KeV: 3.692,
    muOverRhoCu: 169.0,
    muOverRhoMo: 34.2,
    muOverRhoCo: 226.0
  },
  Sc: {
    symbol: 'Sc',
    name: 'Scandium',
    z: 21,
    atomicWeight: 44.956,
    period: 4,
    group: 3,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d¹ 4s²',
    valenceElectrons: 3,
    electronegativity: 1.36,
    covalentRadiusPm: 170,
    ionicRadiusPm: 74.5, // Sc3+ (VI)
    commonOxidationStates: [3],
    pureCrystalStructure: 'HCP',
    densityGcm3: 2.985,
    meltingPointK: 1814,
    kEdgeKeV: 4.493,
    kAlpha1KeV: 4.091,
    muOverRhoCu: 195.0,
    muOverRhoMo: 39.5,
    muOverRhoCo: 260.0
  },
  Ti: {
    symbol: 'Ti',
    name: 'Titanium',
    z: 22,
    atomicWeight: 47.867,
    period: 4,
    group: 4,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d² 4s²',
    valenceElectrons: 4,
    electronegativity: 1.54,
    covalentRadiusPm: 160,
    ionicRadiusPm: 60.5, // Ti4+ (VI)
    commonOxidationStates: [4, 3, 2],
    pureCrystalStructure: 'HCP (alpha) / BCC (beta)',
    densityGcm3: 4.506,
    meltingPointK: 1941,
    kEdgeKeV: 4.966,
    kAlpha1KeV: 4.511,
    kBeta1KeV: 4.931,
    muOverRhoCu: 204.0,
    muOverRhoMo: 41.5,
    muOverRhoCo: 275.0
  },
  V: {
    symbol: 'V',
    name: 'Vanadium',
    z: 23,
    atomicWeight: 50.942,
    period: 4,
    group: 5,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d³ 4s²',
    valenceElectrons: 5,
    electronegativity: 1.63,
    covalentRadiusPm: 153,
    ionicRadiusPm: 54, // V5+ (VI)
    commonOxidationStates: [5, 4, 3, 2],
    pureCrystalStructure: 'BCC',
    densityGcm3: 6.11,
    meltingPointK: 2183,
    kEdgeKeV: 5.465,
    kAlpha1KeV: 4.952,
    kBeta1KeV: 5.427,
    muOverRhoCu: 232.0,
    muOverRhoMo: 47.0,
    muOverRhoCo: 312.0
  },
  Cr: {
    symbol: 'Cr',
    name: 'Chromium',
    z: 24,
    atomicWeight: 51.996,
    period: 4,
    group: 6,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d⁵ 4s¹',
    valenceElectrons: 6,
    electronegativity: 1.66,
    covalentRadiusPm: 139,
    ionicRadiusPm: 61.5, // Cr3+ (VI)
    commonOxidationStates: [6, 3, 2],
    pureCrystalStructure: 'BCC',
    densityGcm3: 7.19,
    meltingPointK: 2180,
    kEdgeKeV: 5.989,
    kAlpha1KeV: 5.415,
    kBeta1KeV: 5.947,
    muOverRhoCu: 251.0,
    muOverRhoMo: 51.0,
    muOverRhoCo: 340.0
  },
  Mn: {
    symbol: 'Mn',
    name: 'Manganese',
    z: 25,
    atomicWeight: 54.938,
    period: 4,
    group: 7,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d⁵ 4s²',
    valenceElectrons: 7,
    electronegativity: 1.55,
    covalentRadiusPm: 139,
    ionicRadiusPm: 64.5, // Mn3+ / Mn4+: 53
    commonOxidationStates: [7, 4, 3, 2],
    pureCrystalStructure: 'Cubic (alpha-Mn)',
    densityGcm3: 7.21,
    meltingPointK: 1519,
    kEdgeKeV: 6.539,
    kAlpha1KeV: 5.899,
    kBeta1KeV: 6.490,
    muOverRhoCu: 278.0,
    muOverRhoMo: 57.0,
    muOverRhoCo: 375.0
  },
  Fe: {
    symbol: 'Fe',
    name: 'Iron',
    z: 26,
    atomicWeight: 55.845,
    period: 4,
    group: 8,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d⁶ 4s²',
    valenceElectrons: 8,
    electronegativity: 1.83,
    covalentRadiusPm: 132,
    ionicRadiusPm: 64.5, // Fe3+ (HS VI), Fe2+: 78
    commonOxidationStates: [3, 2],
    pureCrystalStructure: 'BCC (alpha-ferrite) / FCC (gamma-austenite)',
    densityGcm3: 7.874,
    meltingPointK: 1811,
    kEdgeKeV: 7.112, // NOTE: BELOW Cu-Ka (8.048 keV) -> CAUSES SEVERE CU FLUORESCENCE!
    kAlpha1KeV: 6.404,
    kBeta1KeV: 7.058,
    muOverRhoCu: 304.0, // High attenuation
    muOverRhoMo: 37.6,
    muOverRhoCo: 55.0 // LOW under Co-Ka -> Co tube ideal for Fe!
  },
  Co: {
    symbol: 'Co',
    name: 'Cobalt',
    z: 27,
    atomicWeight: 58.933,
    period: 4,
    group: 9,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d⁷ 4s²',
    valenceElectrons: 9,
    electronegativity: 1.88,
    covalentRadiusPm: 126,
    ionicRadiusPm: 65, // Co2+ (VI HS: 74.5, LS: 65)
    commonOxidationStates: [2, 3],
    pureCrystalStructure: 'HCP (epsilon) / FCC',
    densityGcm3: 8.90,
    meltingPointK: 1768,
    kEdgeKeV: 7.709, // BELOW Cu-Ka -> Severe Cu fluorescence!
    kAlpha1KeV: 6.930,
    kBeta1KeV: 7.649,
    muOverRhoCu: 313.0,
    muOverRhoMo: 44.0,
    muOverRhoCo: 68.0
  },
  Ni: {
    symbol: 'Ni',
    name: 'Nickel',
    z: 28,
    atomicWeight: 58.693,
    period: 4,
    group: 10,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d⁸ 4s²',
    valenceElectrons: 10,
    electronegativity: 1.91,
    covalentRadiusPm: 124,
    ionicRadiusPm: 69, // Ni2+ (VI)
    commonOxidationStates: [2, 3],
    pureCrystalStructure: 'FCC',
    densityGcm3: 8.908,
    meltingPointK: 1728,
    kEdgeKeV: 8.333, // ABOVE Cu-Ka (8.048 keV) -> No Cu-Ka K-fluorescence!
    kAlpha1KeV: 7.478,
    kBeta1KeV: 8.265,
    muOverRhoCu: 45.7, // Low under Cu-Ka (since below K-edge)
    muOverRhoMo: 50.5,
    muOverRhoCo: 62.0
  },
  Cu: {
    symbol: 'Cu',
    name: 'Copper',
    z: 29,
    atomicWeight: 63.546,
    period: 4,
    group: 11,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d¹⁰ 4s¹',
    valenceElectrons: 11,
    electronegativity: 1.90,
    covalentRadiusPm: 132,
    ionicRadiusPm: 73, // Cu2+ (VI), Cu+: 77
    commonOxidationStates: [2, 1],
    pureCrystalStructure: 'FCC',
    densityGcm3: 8.96,
    meltingPointK: 1357.77,
    kEdgeKeV: 8.979,
    kAlpha1KeV: 8.048,
    kBeta1KeV: 8.905,
    muOverRhoCu: 52.6,
    muOverRhoMo: 58.0,
    muOverRhoCo: 73.0
  },
  Zn: {
    symbol: 'Zn',
    name: 'Zinc',
    z: 30,
    atomicWeight: 65.38,
    period: 4,
    group: 12,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Ar] 3d¹⁰ 4s²',
    valenceElectrons: 12,
    electronegativity: 1.65,
    covalentRadiusPm: 122,
    ionicRadiusPm: 74, // Zn2+ (VI)
    commonOxidationStates: [2],
    pureCrystalStructure: 'HCP',
    densityGcm3: 7.14,
    meltingPointK: 692.68,
    kEdgeKeV: 9.659,
    kAlpha1KeV: 8.639,
    kBeta1KeV: 9.572,
    muOverRhoCu: 59.8,
    muOverRhoMo: 66.5,
    muOverRhoCo: 83.5
  },
  Ga: {
    symbol: 'Ga',
    name: 'Gallium',
    z: 31,
    atomicWeight: 69.723,
    period: 4,
    group: 13,
    block: 'p',
    category: 'Post-Transition Metal',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p¹',
    valenceElectrons: 3,
    electronegativity: 1.81,
    covalentRadiusPm: 122,
    ionicRadiusPm: 62, // Ga3+ (VI)
    commonOxidationStates: [3],
    pureCrystalStructure: 'Orthorhombic',
    densityGcm3: 5.91,
    meltingPointK: 302.91,
    kEdgeKeV: 10.367,
    kAlpha1KeV: 9.252,
    muOverRhoCu: 67.5,
    muOverRhoMo: 75.0,
    muOverRhoCo: 95.0
  },
  Ge: {
    symbol: 'Ge',
    name: 'Germanium',
    z: 32,
    atomicWeight: 72.630,
    period: 4,
    group: 14,
    block: 'p',
    category: 'Metalloid',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p²',
    valenceElectrons: 4,
    electronegativity: 2.01,
    covalentRadiusPm: 120,
    ionicRadiusPm: 53, // Ge4+ (VI)
    commonOxidationStates: [4, 2],
    pureCrystalStructure: 'Diamond Cubic',
    densityGcm3: 5.323,
    meltingPointK: 1211.4,
    kEdgeKeV: 11.103,
    kAlpha1KeV: 9.886,
    muOverRhoCu: 75.8,
    muOverRhoMo: 84.0,
    muOverRhoCo: 106.0
  },
  As: {
    symbol: 'As',
    name: 'Arsenic',
    z: 33,
    atomicWeight: 74.922,
    period: 4,
    group: 15,
    block: 'p',
    category: 'Metalloid',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p³',
    valenceElectrons: 5,
    electronegativity: 2.18,
    covalentRadiusPm: 119,
    ionicRadiusPm: 58, // As3+
    commonOxidationStates: [5, 3, -3],
    pureCrystalStructure: 'Rhombohedral',
    densityGcm3: 5.727,
    meltingPointK: 1090,
    kEdgeKeV: 11.867,
    kAlpha1KeV: 10.544,
    muOverRhoCu: 84.0,
    muOverRhoMo: 94.0,
    muOverRhoCo: 118.0
  },
  Se: {
    symbol: 'Se',
    name: 'Selenium',
    z: 34,
    atomicWeight: 78.971,
    period: 4,
    group: 16,
    block: 'p',
    category: 'Reactive Nonmetal',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁴',
    valenceElectrons: 6,
    electronegativity: 2.55,
    covalentRadiusPm: 120,
    ionicRadiusPm: 198, // Se2-
    commonOxidationStates: [6, 4, -2],
    pureCrystalStructure: 'Hexagonal',
    densityGcm3: 4.819,
    meltingPointK: 494,
    kEdgeKeV: 12.658,
    kAlpha1KeV: 11.222,
    muOverRhoCu: 93.0,
    muOverRhoMo: 104.0,
    muOverRhoCo: 130.0
  },
  Br: {
    symbol: 'Br',
    name: 'Bromine',
    z: 35,
    atomicWeight: 79.904,
    period: 4,
    group: 17,
    block: 'p',
    category: 'Halogen',
    electronConfig: '[Ar] 3d¹⁰ 4s² 4p⁵',
    valenceElectrons: 7,
    electronegativity: 2.96,
    covalentRadiusPm: 120,
    ionicRadiusPm: 196, // Br-
    commonOxidationStates: [-1, 1, 5],
    pureCrystalStructure: 'Orthorhombic',
    densityGcm3: 3.1028,
    meltingPointK: 265.8,
    kEdgeKeV: 13.474,
    kAlpha1KeV: 11.924,
    muOverRhoCu: 102.0,
    muOverRhoMo: 115.0,
    muOverRhoCo: 144.0
  },
  Rb: {
    symbol: 'Rb',
    name: 'Rubidium',
    z: 37,
    atomicWeight: 85.468,
    period: 5,
    group: 1,
    block: 's',
    category: 'Alkali Metal',
    electronConfig: '[Kr] 5s¹',
    valenceElectrons: 1,
    electronegativity: 0.82,
    covalentRadiusPm: 220,
    ionicRadiusPm: 152, // Rb+ (VI)
    commonOxidationStates: [1],
    pureCrystalStructure: 'BCC',
    densityGcm3: 1.532,
    meltingPointK: 312.45,
    kEdgeKeV: 15.200,
    muOverRhoCu: 122.0,
    muOverRhoMo: 138.0
  },
  Sr: {
    symbol: 'Sr',
    name: 'Strontium',
    z: 38,
    atomicWeight: 87.62,
    period: 5,
    group: 2,
    block: 's',
    category: 'Alkaline Earth',
    electronConfig: '[Kr] 5s²',
    valenceElectrons: 2,
    electronegativity: 0.95,
    covalentRadiusPm: 195,
    ionicRadiusPm: 118, // Sr2+ (VI)
    commonOxidationStates: [2],
    pureCrystalStructure: 'FCC',
    densityGcm3: 2.64,
    meltingPointK: 1050,
    kEdgeKeV: 16.105,
    kAlpha1KeV: 14.165,
    muOverRhoCu: 133.0,
    muOverRhoMo: 151.0
  },
  Y: {
    symbol: 'Y',
    name: 'Yttrium',
    z: 39,
    atomicWeight: 88.906,
    period: 5,
    group: 3,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d¹ 5s²',
    valenceElectrons: 3,
    electronegativity: 1.22,
    covalentRadiusPm: 190,
    ionicRadiusPm: 90, // Y3+ (VI)
    commonOxidationStates: [3],
    pureCrystalStructure: 'HCP',
    densityGcm3: 4.472,
    meltingPointK: 1799,
    kEdgeKeV: 17.038,
    kAlpha1KeV: 14.958,
    muOverRhoCu: 144.0,
    muOverRhoMo: 165.0
  },
  Zr: {
    symbol: 'Zr',
    name: 'Zirconium',
    z: 40,
    atomicWeight: 91.224,
    period: 5,
    group: 4,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d² 5s²',
    valenceElectrons: 4,
    electronegativity: 1.33,
    covalentRadiusPm: 175,
    ionicRadiusPm: 72, // Zr4+ (VI)
    commonOxidationStates: [4],
    pureCrystalStructure: 'HCP (alpha) / BCC (beta)',
    densityGcm3: 6.52,
    meltingPointK: 2128,
    kEdgeKeV: 17.998,
    kAlpha1KeV: 15.775,
    muOverRhoCu: 157.0,
    muOverRhoMo: 21.0 // Below Mo K-edge!
  },
  Nb: {
    symbol: 'Nb',
    name: 'Niobium',
    z: 41,
    atomicWeight: 92.906,
    period: 5,
    group: 5,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d⁴ 5s¹',
    valenceElectrons: 5,
    electronegativity: 1.60,
    covalentRadiusPm: 164,
    ionicRadiusPm: 64, // Nb5+ (VI)
    commonOxidationStates: [5, 3],
    pureCrystalStructure: 'BCC',
    densityGcm3: 8.57,
    meltingPointK: 2750,
    kEdgeKeV: 18.986,
    kAlpha1KeV: 16.615,
    muOverRhoCu: 170.0,
    muOverRhoMo: 23.5
  },
  Mo: {
    symbol: 'Mo',
    name: 'Molybdenum',
    z: 42,
    atomicWeight: 95.95,
    period: 5,
    group: 6,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d⁵ 5s¹',
    valenceElectrons: 6,
    electronegativity: 2.16,
    covalentRadiusPm: 154,
    ionicRadiusPm: 59, // Mo6+ (VI)
    commonOxidationStates: [6, 4, 3],
    pureCrystalStructure: 'BCC',
    densityGcm3: 10.28,
    meltingPointK: 2896,
    kEdgeKeV: 20.000,
    kAlpha1KeV: 17.479,
    kBeta1KeV: 19.608,
    muOverRhoCu: 183.0,
    muOverRhoMo: 26.0
  },
  Ru: {
    symbol: 'Ru',
    name: 'Ruthenium',
    z: 44,
    atomicWeight: 101.07,
    period: 5,
    group: 8,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d⁷ 5s¹',
    valenceElectrons: 8,
    electronegativity: 2.20,
    covalentRadiusPm: 146,
    ionicRadiusPm: 62, // Ru4+ (VI)
    commonOxidationStates: [4, 3, 8],
    pureCrystalStructure: 'HCP',
    densityGcm3: 12.45,
    meltingPointK: 2607,
    kEdgeKeV: 22.117,
    kAlpha1KeV: 19.279
  },
  Rh: {
    symbol: 'Rh',
    name: 'Rhodium',
    z: 45,
    atomicWeight: 102.91,
    period: 5,
    group: 9,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d⁸ 5s¹',
    valenceElectrons: 9,
    electronegativity: 2.28,
    covalentRadiusPm: 142,
    ionicRadiusPm: 66.5, // Rh3+ (VI)
    commonOxidationStates: [3],
    pureCrystalStructure: 'FCC',
    densityGcm3: 12.41,
    meltingPointK: 2237,
    kEdgeKeV: 23.220,
    kAlpha1KeV: 20.216
  },
  Pd: {
    symbol: 'Pd',
    name: 'Palladium',
    z: 46,
    atomicWeight: 106.42,
    period: 5,
    group: 10,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d¹⁰',
    valenceElectrons: 10,
    electronegativity: 2.20,
    covalentRadiusPm: 139,
    ionicRadiusPm: 86, // Pd2+ (VI)
    commonOxidationStates: [2, 4],
    pureCrystalStructure: 'FCC',
    densityGcm3: 12.023,
    meltingPointK: 1828.05,
    kEdgeKeV: 24.350,
    kAlpha1KeV: 21.177,
    muOverRhoCu: 236.0,
    muOverRhoMo: 34.0
  },
  Ag: {
    symbol: 'Ag',
    name: 'Silver',
    z: 47,
    atomicWeight: 107.87,
    period: 5,
    group: 11,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d¹⁰ 5s¹',
    valenceElectrons: 11,
    electronegativity: 1.93,
    covalentRadiusPm: 145,
    ionicRadiusPm: 115, // Ag+ (VI)
    commonOxidationStates: [1],
    pureCrystalStructure: 'FCC',
    densityGcm3: 10.49,
    meltingPointK: 1234.93,
    kEdgeKeV: 25.514,
    kAlpha1KeV: 22.163,
    kBeta1KeV: 24.942,
    muOverRhoCu: 252.0,
    muOverRhoMo: 37.0
  },
  Cd: {
    symbol: 'Cd',
    name: 'Cadmium',
    z: 48,
    atomicWeight: 112.41,
    period: 5,
    group: 12,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Kr] 4d¹⁰ 5s²',
    valenceElectrons: 12,
    electronegativity: 1.69,
    covalentRadiusPm: 144,
    ionicRadiusPm: 95, // Cd2+ (VI)
    commonOxidationStates: [2],
    pureCrystalStructure: 'HCP',
    densityGcm3: 8.65,
    meltingPointK: 594.22,
    kEdgeKeV: 26.711,
    kAlpha1KeV: 23.174,
    muOverRhoCu: 269.0,
    muOverRhoMo: 40.0
  },
  In: {
    symbol: 'In',
    name: 'Indium',
    z: 49,
    atomicWeight: 114.82,
    period: 5,
    group: 13,
    block: 'p',
    category: 'Post-Transition Metal',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p¹',
    valenceElectrons: 3,
    electronegativity: 1.78,
    covalentRadiusPm: 142,
    ionicRadiusPm: 80, // In3+ (VI)
    commonOxidationStates: [3],
    pureCrystalStructure: 'Tetragonal',
    densityGcm3: 7.31,
    meltingPointK: 429.75,
    kEdgeKeV: 27.940,
    kAlpha1KeV: 24.210
  },
  Sn: {
    symbol: 'Sn',
    name: 'Tin',
    z: 50,
    atomicWeight: 118.71,
    period: 5,
    group: 14,
    block: 'p',
    category: 'Post-Transition Metal',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p²',
    valenceElectrons: 4,
    electronegativity: 1.96,
    covalentRadiusPm: 139,
    ionicRadiusPm: 69, // Sn4+ (VI)
    commonOxidationStates: [4, 2],
    pureCrystalStructure: 'Tetragonal (beta-white tin) / Diamond (alpha-grey)',
    densityGcm3: 7.265,
    meltingPointK: 505.08,
    kEdgeKeV: 29.200,
    kAlpha1KeV: 25.271,
    muOverRhoCu: 300.0,
    muOverRhoMo: 46.5
  },
  Sb: {
    symbol: 'Sb',
    name: 'Antimony',
    z: 51,
    atomicWeight: 121.76,
    period: 5,
    group: 15,
    block: 'p',
    category: 'Metalloid',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p³',
    valenceElectrons: 5,
    electronegativity: 2.05,
    covalentRadiusPm: 139,
    ionicRadiusPm: 60, // Sb5+ (VI)
    commonOxidationStates: [5, 3, -3],
    pureCrystalStructure: 'Rhombohedral',
    densityGcm3: 6.697,
    meltingPointK: 903.78,
    kEdgeKeV: 30.491,
    kAlpha1KeV: 26.359
  },
  Te: {
    symbol: 'Te',
    name: 'Tellurium',
    z: 52,
    atomicWeight: 127.60,
    period: 5,
    group: 16,
    block: 'p',
    category: 'Metalloid',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁴',
    valenceElectrons: 6,
    electronegativity: 2.10,
    covalentRadiusPm: 138,
    ionicRadiusPm: 221, // Te2-
    commonOxidationStates: [6, 4, -2],
    pureCrystalStructure: 'Hexagonal',
    densityGcm3: 6.24,
    meltingPointK: 722.66,
    kEdgeKeV: 31.814,
    kAlpha1KeV: 27.472
  },
  I: {
    symbol: 'I',
    name: 'Iodine',
    z: 53,
    atomicWeight: 126.90,
    period: 5,
    group: 17,
    block: 'p',
    category: 'Halogen',
    electronConfig: '[Kr] 4d¹⁰ 5s² 5p⁵',
    valenceElectrons: 7,
    electronegativity: 2.66,
    covalentRadiusPm: 139,
    ionicRadiusPm: 220, // I-
    commonOxidationStates: [-1, 1, 5, 7],
    pureCrystalStructure: 'Orthorhombic',
    densityGcm3: 4.933,
    meltingPointK: 386.85,
    kEdgeKeV: 33.169,
    kAlpha1KeV: 28.612
  },
  Cs: {
    symbol: 'Cs',
    name: 'Caesium',
    z: 55,
    atomicWeight: 132.91,
    period: 6,
    group: 1,
    block: 's',
    category: 'Alkali Metal',
    electronConfig: '[Xe] 6s¹',
    valenceElectrons: 1,
    electronegativity: 0.79,
    covalentRadiusPm: 244,
    ionicRadiusPm: 167, // Cs+ (VI)
    commonOxidationStates: [1],
    pureCrystalStructure: 'BCC',
    densityGcm3: 1.93,
    meltingPointK: 301.59,
    kEdgeKeV: 35.985,
    kAlpha1KeV: 30.973
  },
  Ba: {
    symbol: 'Ba',
    name: 'Barium',
    z: 56,
    atomicWeight: 137.33,
    period: 6,
    group: 2,
    block: 's',
    category: 'Alkaline Earth',
    electronConfig: '[Xe] 6s²',
    valenceElectrons: 2,
    electronegativity: 0.89,
    covalentRadiusPm: 215,
    ionicRadiusPm: 135, // Ba2+ (VI)
    commonOxidationStates: [2],
    pureCrystalStructure: 'BCC',
    densityGcm3: 3.51,
    meltingPointK: 1000,
    kEdgeKeV: 37.441,
    kAlpha1KeV: 32.194,
    muOverRhoCu: 350.0,
    muOverRhoMo: 58.0
  },
  La: {
    symbol: 'La',
    name: 'Lanthanum',
    z: 57,
    atomicWeight: 138.91,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 5d¹ 6s²',
    valenceElectrons: 3,
    electronegativity: 1.10,
    covalentRadiusPm: 207,
    ionicRadiusPm: 103.2, // La3+ (VI)
    commonOxidationStates: [3],
    pureCrystalStructure: 'DHCP',
    densityGcm3: 6.162,
    meltingPointK: 1193,
    kEdgeKeV: 38.925,
    kAlpha1KeV: 33.442,
    muOverRhoCu: 365.0,
    muOverRhoMo: 61.5
  },
  Ce: {
    symbol: 'Ce',
    name: 'Cerium',
    z: 58,
    atomicWeight: 140.12,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 4f¹ 5d¹ 6s²',
    valenceElectrons: 4,
    electronegativity: 1.12,
    covalentRadiusPm: 204,
    ionicRadiusPm: 87, // Ce4+ (VI), Ce3+: 101
    commonOxidationStates: [4, 3],
    pureCrystalStructure: 'FCC (gamma) / DHCP',
    densityGcm3: 6.77,
    meltingPointK: 1068,
    kEdgeKeV: 40.443,
    kAlpha1KeV: 34.720,
    muOverRhoCu: 380.0,
    muOverRhoMo: 64.0
  },
  Pr: {
    symbol: 'Pr',
    name: 'Praseodymium',
    z: 59,
    atomicWeight: 140.91,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 4f³ 6s²',
    valenceElectrons: 3,
    electronegativity: 1.13,
    covalentRadiusPm: 203,
    ionicRadiusPm: 99,
    commonOxidationStates: [3, 4],
    pureCrystalStructure: 'DHCP',
    densityGcm3: 6.77,
    meltingPointK: 1208
  },
  Nd: {
    symbol: 'Nd',
    name: 'Neodymium',
    z: 60,
    atomicWeight: 144.24,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 4f⁴ 6s²',
    valenceElectrons: 3,
    electronegativity: 1.14,
    covalentRadiusPm: 201,
    ionicRadiusPm: 98.3,
    commonOxidationStates: [3],
    pureCrystalStructure: 'DHCP',
    densityGcm3: 7.01,
    meltingPointK: 1297,
    kEdgeKeV: 43.569,
    kAlpha1KeV: 37.361
  },
  Sm: {
    symbol: 'Sm',
    name: 'Samarium',
    z: 62,
    atomicWeight: 150.36,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 4f⁶ 6s²',
    valenceElectrons: 3,
    electronegativity: 1.17,
    covalentRadiusPm: 198,
    ionicRadiusPm: 95.8,
    commonOxidationStates: [3, 2],
    pureCrystalStructure: 'Rhombohedral',
    densityGcm3: 7.52,
    meltingPointK: 1345,
    kEdgeKeV: 46.834,
    kAlpha1KeV: 40.118
  },
  Eu: {
    symbol: 'Eu',
    name: 'Europium',
    z: 63,
    atomicWeight: 151.96,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 4f⁷ 6s²',
    valenceElectrons: 2,
    electronegativity: 1.20,
    covalentRadiusPm: 198,
    ionicRadiusPm: 117, // Eu2+
    commonOxidationStates: [3, 2],
    pureCrystalStructure: 'BCC',
    densityGcm3: 5.244,
    meltingPointK: 1099
  },
  Gd: {
    symbol: 'Gd',
    name: 'Gadolinium',
    z: 64,
    atomicWeight: 157.25,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 4f⁷ 5d¹ 6s²',
    valenceElectrons: 3,
    electronegativity: 1.20,
    covalentRadiusPm: 196,
    ionicRadiusPm: 93.8,
    commonOxidationStates: [3],
    pureCrystalStructure: 'HCP',
    densityGcm3: 7.90,
    meltingPointK: 1585,
    kEdgeKeV: 50.239,
    kAlpha1KeV: 42.996
  },
  Dy: {
    symbol: 'Dy',
    name: 'Dysprosium',
    z: 66,
    atomicWeight: 162.50,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 4f¹⁰ 6s²',
    valenceElectrons: 3,
    electronegativity: 1.22,
    covalentRadiusPm: 192,
    ionicRadiusPm: 91.2,
    commonOxidationStates: [3],
    pureCrystalStructure: 'HCP',
    densityGcm3: 8.54,
    meltingPointK: 1680
  },
  Er: {
    symbol: 'Er',
    name: 'Erbium',
    z: 68,
    atomicWeight: 167.26,
    period: 6,
    group: 3,
    block: 'f',
    category: 'Lanthanide',
    electronConfig: '[Xe] 4f¹² 6s²',
    valenceElectrons: 3,
    electronegativity: 1.24,
    covalentRadiusPm: 189,
    ionicRadiusPm: 89,
    commonOxidationStates: [3],
    pureCrystalStructure: 'HCP',
    densityGcm3: 9.066,
    meltingPointK: 1802
  },
  Hf: {
    symbol: 'Hf',
    name: 'Hafnium',
    z: 72,
    atomicWeight: 178.49,
    period: 6,
    group: 4,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d² 6s²',
    valenceElectrons: 4,
    electronegativity: 1.30,
    covalentRadiusPm: 175,
    ionicRadiusPm: 71, // Hf4+ (VI)
    commonOxidationStates: [4],
    pureCrystalStructure: 'HCP',
    densityGcm3: 13.31,
    meltingPointK: 2506,
    kEdgeKeV: 65.351,
    l3EdgeKeV: 9.561,
    muOverRhoCu: 162.0,
    muOverRhoMo: 95.0
  },
  Ta: {
    symbol: 'Ta',
    name: 'Tantalum',
    z: 73,
    atomicWeight: 180.95,
    period: 6,
    group: 5,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d³ 6s²',
    valenceElectrons: 5,
    electronegativity: 1.50,
    covalentRadiusPm: 170,
    ionicRadiusPm: 64, // Ta5+ (VI)
    commonOxidationStates: [5],
    pureCrystalStructure: 'BCC',
    densityGcm3: 16.69,
    meltingPointK: 3290,
    kEdgeKeV: 67.416,
    l3EdgeKeV: 9.881,
    muOverRhoCu: 172.0,
    muOverRhoMo: 101.0
  },
  W: {
    symbol: 'W',
    name: 'Tungsten',
    z: 74,
    atomicWeight: 183.84,
    period: 6,
    group: 6,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    valenceElectrons: 6,
    electronegativity: 2.36,
    covalentRadiusPm: 162,
    ionicRadiusPm: 60, // W6+ (VI)
    commonOxidationStates: [6, 4],
    pureCrystalStructure: 'BCC',
    densityGcm3: 19.25,
    meltingPointK: 3695,
    kEdgeKeV: 69.525,
    l3EdgeKeV: 10.207,
    kAlpha1KeV: 59.318,
    muOverRhoCu: 182.0,
    muOverRhoMo: 108.0
  },
  Re: {
    symbol: 'Re',
    name: 'Rhenium',
    z: 75,
    atomicWeight: 186.21,
    period: 6,
    group: 7,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    valenceElectrons: 7,
    electronegativity: 1.90,
    covalentRadiusPm: 151,
    ionicRadiusPm: 55,
    commonOxidationStates: [7, 4],
    pureCrystalStructure: 'HCP',
    densityGcm3: 21.02,
    meltingPointK: 3459
  },
  Os: {
    symbol: 'Os',
    name: 'Osmium',
    z: 76,
    atomicWeight: 190.23,
    period: 6,
    group: 8,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    valenceElectrons: 8,
    electronegativity: 2.20,
    covalentRadiusPm: 144,
    ionicRadiusPm: 63,
    commonOxidationStates: [4, 8],
    pureCrystalStructure: 'HCP',
    densityGcm3: 22.59,
    meltingPointK: 3306
  },
  Ir: {
    symbol: 'Ir',
    name: 'Iridium',
    z: 77,
    atomicWeight: 192.22,
    period: 6,
    group: 9,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    valenceElectrons: 9,
    electronegativity: 2.20,
    covalentRadiusPm: 141,
    ionicRadiusPm: 68,
    commonOxidationStates: [4, 3],
    pureCrystalStructure: 'FCC',
    densityGcm3: 22.56,
    meltingPointK: 2719
  },
  Pt: {
    symbol: 'Pt',
    name: 'Platinum',
    z: 78,
    atomicWeight: 195.08,
    period: 6,
    group: 10,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    valenceElectrons: 10,
    electronegativity: 2.28,
    covalentRadiusPm: 136,
    ionicRadiusPm: 80, // Pt2+ (VI: 80, Pt4+: 62.5)
    commonOxidationStates: [4, 2],
    pureCrystalStructure: 'FCC',
    densityGcm3: 21.45,
    meltingPointK: 2041.4,
    kEdgeKeV: 78.395,
    l3EdgeKeV: 11.564,
    muOverRhoCu: 202.0,
    muOverRhoMo: 118.0
  },
  Au: {
    symbol: 'Au',
    name: 'Gold',
    z: 79,
    atomicWeight: 196.97,
    period: 6,
    group: 11,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    valenceElectrons: 11,
    electronegativity: 2.54,
    covalentRadiusPm: 136,
    ionicRadiusPm: 85, // Au3+ (VI: 85, Au+: 137)
    commonOxidationStates: [3, 1],
    pureCrystalStructure: 'FCC',
    densityGcm3: 19.30,
    meltingPointK: 1337.33,
    kEdgeKeV: 80.725,
    l3EdgeKeV: 11.919,
    kAlpha1KeV: 68.804,
    muOverRhoCu: 210.0,
    muOverRhoMo: 125.0
  },
  Hg: {
    symbol: 'Hg',
    name: 'Mercury',
    z: 80,
    atomicWeight: 200.59,
    period: 6,
    group: 12,
    block: 'd',
    category: 'Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    valenceElectrons: 12,
    electronegativity: 2.00,
    covalentRadiusPm: 132,
    ionicRadiusPm: 102, // Hg2+ (VI)
    commonOxidationStates: [2, 1],
    pureCrystalStructure: 'Rhombohedral',
    densityGcm3: 13.534,
    meltingPointK: 234.32,
    kEdgeKeV: 83.102,
    l3EdgeKeV: 12.284
  },
  Tl: {
    symbol: 'Tl',
    name: 'Thallium',
    z: 81,
    atomicWeight: 204.38,
    period: 6,
    group: 13,
    block: 'p',
    category: 'Post-Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    valenceElectrons: 3,
    electronegativity: 1.62,
    covalentRadiusPm: 145,
    ionicRadiusPm: 150, // Tl+ (VI)
    commonOxidationStates: [1, 3],
    pureCrystalStructure: 'HCP',
    densityGcm3: 11.85,
    meltingPointK: 577
  },
  Pb: {
    symbol: 'Pb',
    name: 'Lead',
    z: 82,
    atomicWeight: 207.2,
    period: 6,
    group: 14,
    block: 'p',
    category: 'Post-Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    valenceElectrons: 4,
    electronegativity: 2.33,
    covalentRadiusPm: 146,
    ionicRadiusPm: 119, // Pb2+ (VI)
    commonOxidationStates: [2, 4],
    pureCrystalStructure: 'FCC',
    densityGcm3: 11.34,
    meltingPointK: 600.61,
    kEdgeKeV: 88.005,
    l3EdgeKeV: 13.035,
    kAlpha1KeV: 74.969,
    muOverRhoCu: 242.0,
    muOverRhoMo: 141.0
  },
  Bi: {
    symbol: 'Bi',
    name: 'Bismuth',
    z: 83,
    atomicWeight: 208.98,
    period: 6,
    group: 15,
    block: 'p',
    category: 'Post-Transition Metal',
    electronConfig: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    valenceElectrons: 5,
    electronegativity: 2.02,
    covalentRadiusPm: 148,
    ionicRadiusPm: 103, // Bi3+ (VI)
    commonOxidationStates: [3, 5],
    pureCrystalStructure: 'Rhombohedral',
    densityGcm3: 9.78,
    meltingPointK: 544.7,
    kEdgeKeV: 90.526,
    l3EdgeKeV: 13.419,
    kAlpha1KeV: 77.108,
    muOverRhoCu: 254.0,
    muOverRhoMo: 149.0
  },
  Th: {
    symbol: 'Th',
    name: 'Thorium',
    z: 90,
    atomicWeight: 232.04,
    period: 7,
    group: 3,
    block: 'f',
    category: 'Actinide',
    electronConfig: '[Rn] 6d² 7s²',
    valenceElectrons: 4,
    electronegativity: 1.30,
    covalentRadiusPm: 179,
    ionicRadiusPm: 94, // Th4+ (VI)
    commonOxidationStates: [4],
    pureCrystalStructure: 'FCC',
    densityGcm3: 11.72,
    meltingPointK: 2115,
    kEdgeKeV: 109.651,
    l3EdgeKeV: 16.300
  },
  U: {
    symbol: 'U',
    name: 'Uranium',
    z: 92,
    atomicWeight: 238.03,
    period: 7,
    group: 3,
    block: 'f',
    category: 'Actinide',
    electronConfig: '[Rn] 5f³ 6d¹ 7s²',
    valenceElectrons: 6,
    electronegativity: 1.38,
    covalentRadiusPm: 175,
    ionicRadiusPm: 73, // U6+ (VI: 73, U4+: 89)
    commonOxidationStates: [6, 4, 3],
    pureCrystalStructure: 'Orthorhombic (alpha)',
    densityGcm3: 19.1,
    meltingPointK: 1405.3,
    kEdgeKeV: 115.606,
    l3EdgeKeV: 17.166
  }
};

/**
 * Returns complete metrology details for an element symbol with safe fallbacks
 */
export function getElementMetrology(symbol: string): ElementMetrology {
  const sym = (symbol || '').trim();
  if (sym && ELEMENT_METROLOGY_DB[sym]) {
    return ELEMENT_METROLOGY_DB[sym];
  }
  return {
    symbol: sym || 'X',
    name: sym || 'Unknown',
    z: 0,
    atomicWeight: 1.0,
    period: 1,
    group: 1,
    block: 's',
    category: 'Reactive Nonmetal',
    electronConfig: 'Unknown',
    valenceElectrons: 1,
    electronegativity: 1.0,
    covalentRadiusPm: 100,
    ionicRadiusPm: 100,
    commonOxidationStates: [1],
    pureCrystalStructure: 'Amorphous'
  };
}

/**
 * Evaluates XRD Tube Fluorescence Risk for an element
 */
export interface FluorescenceRisk {
  anode: string;
  anodeEnergyKeV: number;
  isExcited: boolean;
  severity: 'none' | 'severe' | 'moderate' | 'safe';
  explanation: string;
  recommendedAnodes: string[];
}

export function evaluateFluorescenceRisk(
  elementSym: string,
  tubeAnode: string = 'Cu-Ka'
): FluorescenceRisk {
  const el = getElementMetrology(elementSym);
  const anodeEnergies: Record<string, { name: string; energyKeV: number }> = {
    'Cu-Ka': { name: 'Cu-Kα (8.048 keV)', energyKeV: 8.048 },
    'Co-Ka': { name: 'Co-Kα (6.930 keV)', energyKeV: 6.930 },
    'Mo-Ka': { name: 'Mo-Kα (17.48 keV)', energyKeV: 17.479 },
    'Cr-Ka': { name: 'Cr-Kα (5.415 keV)', energyKeV: 5.415 },
    'Fe-Ka': { name: 'Fe-Kα (6.404 keV)', energyKeV: 6.404 },
    'Ag-Ka': { name: 'Ag-Kα (22.16 keV)', energyKeV: 22.163 }
  };

  const selected = anodeEnergies[tubeAnode] || anodeEnergies['Cu-Ka'];
  const kEdge = el.kEdgeKeV;

  if (!kEdge) {
    return {
      anode: selected.name,
      anodeEnergyKeV: selected.energyKeV,
      isExcited: false,
      severity: 'none',
      explanation: 'No high-energy K-edge fluorescence concerns.',
      recommendedAnodes: ['Cu-Kα', 'Co-Kα', 'Mo-Kα']
    };
  }

  // If incident X-ray energy > K-edge energy, K-shell fluorescence will be excited!
  // Especially problematic if incident energy is just slightly above the K-edge (within 2-3 keV)
  const isExcited = selected.energyKeV > kEdge;
  const delta = selected.energyKeV - kEdge;

  if (isExcited && delta >= 0 && delta <= 1.5) {
    // Extreme fluorescence (like Cu-Ka on Fe (7.11 keV) or Co (7.71 keV))
    const rec = tubeAnode.startsWith('Cu')
      ? ['Co-Kα', 'Mo-Kα', 'Cr-Kα']
      : ['Mo-Kα', 'Ag-Kα'];
    return {
      anode: selected.name,
      anodeEnergyKeV: selected.energyKeV,
      isExcited: true,
      severity: 'severe',
      explanation: `${el.name} (K-edge = ${kEdge.toFixed(3)} keV) strongly fluoresces under ${selected.name}, yielding elevated continuous background noise in raw diffractograms.`,
      recommendedAnodes: rec
    };
  }

  if (isExcited) {
    return {
      anode: selected.name,
      anodeEnergyKeV: selected.energyKeV,
      isExcited: true,
      severity: 'moderate',
      explanation: `${el.name} K-edge (${kEdge.toFixed(3)} keV) is excited by ${selected.name}. Standard secondary monochromator or energy-dispersive detector filter recommended.`,
      recommendedAnodes: ['Co-Kα', 'Mo-Kα']
    };
  }

  return {
    anode: selected.name,
    anodeEnergyKeV: selected.energyKeV,
    isExcited: false,
    severity: 'safe',
    explanation: `${selected.name} (${selected.energyKeV.toFixed(3)} keV) is safely below the ${el.name} K-edge (${kEdge.toFixed(3)} keV). Zero K-fluorescence interference.`,
    recommendedAnodes: [tubeAnode]
  };
}

/**
 * Calculates Hannay-Smyth and Pauling bond ionicity percentage from electronegativity difference
 */
export function calculateIonicityPercentage(deltaChi: number): number {
  if (deltaChi <= 0) return 0;
  // Hannay-Smyth formula: % Ionic = 16 * |deltaChi| + 3.5 * (deltaChi)^2
  const hs = 16 * deltaChi + 3.5 * Math.pow(deltaChi, 2);
  // Pauling formula: 1 - exp(-0.25 * deltaChi^2)
  const pauling = (1 - Math.exp(-0.25 * Math.pow(deltaChi, 2))) * 100;
  return Math.min(100, Math.max(0, (hs + pauling) / 2));
}
