export const MATERIAL_DB = [
  { 
    name: 'Silicon (Si)', 
    type: 'Semiconductor', 
    pattern: '28.44, 100\n47.30, 55\n56.12, 30\n69.13, 6\n76.38, 11\n88.03, 12',
    description: 'A hard, brittle crystalline solid with a blue-grey metallic lustre.',
    formula: 'Si',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fd-3m',
    density: 2.33,
    applications: ['Electronics', 'Solar Cells', 'Semiconductors'],
    molecularWeight: 28.085,
    bandGap: 1.11,
    elasticModulus: 130,
    magneticProperties: 'Diamagnetic',
    opticalProperties: 'Opaque in visible light, transparent to IR'
  },
  { 
    name: 'Zirconia (ZrO2)', 
    type: 'Ceramic', 
    pattern: '30.27, 100\n35.25, 25\n50.37, 60\n60.20, 30', 
    description: 'Zirconium dioxide is a white crystalline oxide of zirconium.',
    formula: 'ZrO2',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P42/nmc',
    density: 5.68,
    applications: ['Ceramics', 'Dental', 'Refractories'],
    molecularWeight: 123.22,
    bandGap: 5.0,
    elasticModulus: 210,
    opticalProperties: 'High refractive index, transparent in thin films',
    hazards: ['Respiratory irritant (dust)']
  },
  { 
    name: 'Hydroxyapatite (Sintered)', 
    type: 'Bioceramic', 
    pattern: '25.87, 45\n31.77, 100\n32.19, 98\n32.90, 65\n34.04, 50\n39.81, 30\n46.71, 40\n49.46, 35\n50.49, 30',
    description: 'Highly crystalline synthetic hydroxyapatite sintered at 1000°C. Characterized by sharp, well-defined Bragg reflections.',
    formula: 'Ca10(PO4)6(OH)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.16,
    applications: ['Standard Reference', 'Bio-coating', 'Thermal Spray Powder'],
    molecularWeight: 1004.6,
    elasticModulus: 120
  },
  { 
    name: 'Hydroxyapatite (Nano)', 
    type: 'Bioceramic', 
    pattern: '25.9, 30\n31.8, 100\n32.2, 90\n32.9, 50\n34.0, 40\n39.8, 20',
    description: 'Poorly crystalline nano-meter sized hydroxyapatite synthesized via low-temperature precipitation. Exhibits significant peak broadening.',
    formula: 'Ca10(PO4)6(OH)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.05,
    applications: ['Bone Filling', 'Drug Delivery', 'Gene Transfection'],
    molecularWeight: 1004.6,
    elasticModulus: 80,
    opticalProperties: 'White nano-powder'
  },
  { 
    name: 'Carbonated Hydroxyapatite', 
    type: 'Bioceramic', 
    pattern: '25.75, 40\n31.65, 100\n32.08, 95\n32.75, 60\n33.85, 45\n39.65, 25',
    description: 'Type-B carbonated hydroxyapatite where carbonate ions substitute for phosphate ions, similar to biological bone mineral.',
    formula: 'Ca10(PO4)6-x(CO3)x(OH)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.10,
    applications: ['Biomimetic Scaffolds', 'Bioactive Coatings'],
    molecularWeight: 1020.0
  },
  { 
    name: 'Fluorapatite', 
    type: 'Bioceramic/Mineral', 
    pattern: '25.81, 40\n31.85, 100\n32.12, 95\n32.95, 60\n34.12, 45\n40.05, 25',
    description: 'The end-member of the apatite series where fluoride replaces hydroxyl groups, increasing acid resistance.',
    formula: 'Ca10(PO4)6F2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.20,
    applications: ['Tooth Enamel Protection', 'Lasers', 'Phosphors'],
    molecularWeight: 1008.6
  },
  { 
    name: 'Strontium-Apatite', 
    type: 'Bioceramic', 
    pattern: '25.21, 35\n30.95, 100\n31.32, 90\n32.05, 55\n33.15, 40\n38.85, 20',
    description: 'Strontium-substituted hydroxyapatite used for treating osteoporosis and enhancing bone formation.',
    formula: '(Ca,Sr)10(PO4)6(OH)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.45,
    applications: ['Osteoporosis Treatment', 'Bone Cements'],
    molecularWeight: 1200.0
  },
  { 
    name: 'Chlorapatite', 
    type: 'Mineral', 
    pattern: '25.68, 30\n31.55, 100\n31.92, 85\n32.78, 55\n33.95, 50\n40.15, 20',
    description: 'Rare apatite mineral where chloride replaces hydroxyl groups.',
    formula: 'Ca10(PO4)6Cl2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.18,
    applications: ['Geology Research'],
    molecularWeight: 1041.5
  },
  { 
    name: 'Hydroxyapatite (Dental Enamel)', 
    type: 'Biological', 
    pattern: '25.8, 40\n31.7, 100\n32.2, 95\n32.9, 60\n34.0, 50\n39.8, 30',
    description: 'Human dental enamel, primarily composed of carbonated hydroxyapatite with specific orientation and crystallite size. Key to tooth structure.',
    formula: 'Ca10(PO4,CO3)6(OH,F)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 2.95,
    applications: ['Dental Research', 'Remineralization Studies'],
    molecularWeight: 1000.0,
    elasticModulus: 85
  },
  { 
    name: 'Magnesium-Doped HAp', 
    type: 'Bioceramic', 
    pattern: '25.95, 35\n31.85, 100\n32.30, 90\n33.05, 55\n34.15, 45\n39.95, 20',
    description: 'Hydroxyapatite where a fraction of calcium is replaced by magnesium, reflecting the composition of early-stage mineralization in bone.',
    formula: 'Ca10-xMgx(PO4)6(OH)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.12,
    applications: ['Bone Regeneration', 'Bioactive Materials'],
    molecularWeight: 980.0
  },
  { 
    name: 'Silicon-substituted HAp', 
    type: 'Bioceramic', 
    pattern: '25.82, 40\n31.68, 100\n32.05, 95\n32.85, 60\n33.95, 50\n39.75, 25',
    description: 'Silicate ions substitute for phosphate groups to enhance the bioactivity and bone bonding rate of hydroxyapatite.',
    formula: 'Ca10(PO4)6-x(SiO4)x(OH)2-x',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.15,
    applications: ['Advanced Bone Grafts', 'Rapid Healing Implants'],
    molecularWeight: 1010.5
  },
  { 
    name: 'Amorphous Calcium Phosphate', 
    type: 'Precursor', 
    pattern: '30.0, 100 (broad)',
    description: 'A non-crystalline precursor to hydroxyapatite. XRD pattern shows a broad "halo" rather than sharp peaks, characteristic of amorphous states.',
    formula: 'CaxHy(PO4)z·nH2O',
    crystalSystem: 'Amorphous',
    spaceGroup: 'N/A',
    density: 2.30,
    applications: ['Remineralizing agents', 'Cements', 'Biological precursors'],
    molecularWeight: 0
  },
  { 
    name: 'Hydroxyapatite (Human Dentin)', 
    type: 'Biological', 
    pattern: '25.85, 35\n31.75, 100\n32.25, 92\n32.95, 58\n34.10, 48\n39.90, 25',
    description: 'Human dentin, slightly more carbonated and less crystalline than enamel. Found under the tooth enamel.',
    formula: 'Ca10(PO4,CO3)6(OH)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 2.10,
    applications: ['Dental Materials Testing', 'Biomedical Research'],
    molecularWeight: 1000.0
  },
  { 
    name: 'Lead-doped HAp', 
    type: 'Environmental/Mineral', 
    pattern: '25.2, 35\n31.1, 100\n31.5, 95\n32.2, 60\n33.4, 50\n39.2, 25',
    description: 'Hydroxyapatite used for heavy metal remediation. Lead ions substitute for calcium, significantly shifting lattice parameters.',
    formula: '(Ca,Pb)10(PO4)6(OH)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 4.10,
    applications: ['Soil Remediation', 'Waste Treatment'],
    molecularWeight: 1500.0
  },
  { 
    name: 'Cadmium-doped HAp', 
    type: 'Environmental', 
    pattern: '26.1, 35\n32.0, 100\n32.4, 90\n33.1, 55\n34.2, 45\n40.1, 20',
    description: 'Apatite structure containing cadmium, often studied in the context of toxic metal uptake from the environment.',
    formula: '(Ca,Cd)10(PO4)6(OH)2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.55,
    applications: ['Toxin Removal', 'Environmental Sensors'],
    molecularWeight: 1100.0
  },
  { 
    name: 'Magnetite (Hyperthermia)', 
    type: 'Magnetic Ceramic', 
    pattern: '30.1, 40\n35.4, 100\n43.1, 20\n53.4, 15\n57.0, 30\n62.6, 40',
    description: 'Superparamagnetic iron oxide nanoparticles (SPIONs) used for magnetic fluid hyperthermia.',
    formula: 'Fe3O4',
    crystalSystem: 'Cubic (Spinel)',
    spaceGroup: 'Fd-3m',
    density: 5.17,
    applications: ['Magnetic Hyperthermia', 'MRI Contrast Agent', 'Targeted Drug Delivery'],
    molecularWeight: 231.5
  },
  { 
    name: 'Cobalt Ferrite', 
    type: 'Magnetic Ceramic', 
    pattern: '30.3, 35\n35.6, 100\n37.3, 15\n43.3, 25\n53.8, 12\n57.4, 28\n63.1, 38',
    description: 'High magnetocrystalline anisotropy ferrite, used to increase the heating efficiency in hyperthermia.',
    formula: 'CoFe2O4',
    crystalSystem: 'Cubic (Spinel)',
    spaceGroup: 'Fd-3m',
    density: 5.29,
    applications: ['Advanced Hyperthermia', 'Magnetic Recording', 'Separation'],
    molecularWeight: 234.6
  },
  { 
    name: 'Maghemite', 
    type: 'Magnetic Ceramic', 
    pattern: '30.2, 35\n35.7, 100\n43.2, 22\n53.5, 18\n57.2, 25\n62.8, 35',
    description: 'The fully oxidized form of magnetite, often the active phase in clinical hyperthermia agents.',
    formula: 'γ-Fe2O3',
    crystalSystem: 'Cubic',
    spaceGroup: 'P4332',
    density: 4.87,
    applications: ['Biomedical Imaging', 'Hyperthermia Therapy'],
    molecularWeight: 159.7
  },
  { 
    name: 'Zinc-doped Ferrite', 
    type: 'Magnetic Ceramic', 
    pattern: '29.9, 45\n35.2, 100\n42.9, 25\n53.1, 15\n56.7, 28\n62.3, 42',
    description: 'Zinc-substituted magnetite used to tune the Curie temperature for self-regulated hyperthermia.',
    formula: 'Zn0.5Fe2.5O4',
    crystalSystem: 'Cubic (Spinel)',
    spaceGroup: 'Fd-3m',
    density: 5.25,
    applications: ['Self-Regulated Hyperthermia', 'Soft Magnetic Devices'],
    molecularWeight: 238.2
  },
  { 
    name: 'Zinc Oxide (ZnO)', 
    type: 'Semiconductor', 
    pattern: '31.77, 57\n34.42, 44\n36.25, 100\n47.54, 23\n56.60, 32\n62.86, 29',
    description: 'An inorganic compound used as an additive in numerous materials and products.',
    formula: 'ZnO',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63mc',
    density: 5.61,
    applications: ['Rubber', 'Plastics', 'Ceramics', 'Glass']
  },
  {
    name: 'Polytetrafluoroethylene (PTFE)',
    type: 'Polymer',
    pattern: '18.07, 100\n31.55, 25\n36.60, 10\n41.20, 5',
    description: 'A synthetic fluoropolymer of tetrafluoroethylene.',
    formula: '(C2F4)n',
    crystalSystem: 'Hexagonal', 
    spaceGroup: 'P',
    density: 2.2,
    applications: ['Non-stick coatings', 'Lubricants']
  },
  {
    name: 'Polyethylene (HDPE)',
    type: 'Polymer',
    pattern: '21.5, 100\n24.0, 45\n30.1, 12\n36.3, 8',
    description: 'High-density polyethylene, a versatile thermoplastic polymer.',
    formula: '(C2H4)n',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pnam',
    density: 0.95,
    applications: ['Plastic bottles', 'Pipes', 'Geomembranes']
  },
  {
    name: 'Polypropylene (iPP)',
    type: 'Polymer',
    pattern: '14.1, 100\n16.9, 85\n18.6, 75\n21.2, 40\n21.8, 45',
    description: 'Isotactic polypropylene, alpha-form semi-crystalline structure.',
    formula: '(C3H6)n',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21/c',
    density: 0.90,
    applications: ['Packaging', 'Textiles', 'Automotive parts']
  },
  {
    name: 'Nylon 6 (Polyamide)',
    type: 'Polymer',
    pattern: '20.3, 100\n23.7, 90',
    description: 'A semi-crystalline polyamide synthesized via ring-opening polymerization.',
    formula: '(C6H11NO)n',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21/a',
    density: 1.13,
    applications: ['Fibers', 'Mechanical parts', 'Musical strings']
  },
  {
    name: 'Quartz (SiO2)',
    type: 'Ceramic/Mineral',
    pattern: '20.86, 35\n26.64, 100\n36.54, 12\n39.47, 9\n40.29, 8\n42.45, 8\n45.79, 9\n50.14, 14\n59.95, 9\n67.74, 7\n68.14, 8',
    description: 'A hard, crystalline mineral composed of silica (silicon dioxide).',
    formula: 'SiO2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P3221',
    density: 2.65,
    applications: ['Glass', 'Electronics', 'Construction', 'Jewelry'],
    molecularWeight: 60.08,
    bandGap: 8.9,
    elasticModulus: 71.7,
    magneticProperties: 'Diamagnetic',
    opticalProperties: 'Transparent, Uniaxial birefringent',
    hazards: ['Silicosis (inhalation)']
  },
  {
    name: 'Halite (NaCl)',
    type: 'Salt/Mineral',
    pattern: '27.37, 10\n31.69, 100\n45.43, 55\n56.45, 15\n66.20, 5\n75.26, 10',
    description: 'Commonly known as rock salt, it is the mineral form of sodium chloride.',
    formula: 'NaCl',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 2.16,
    applications: ['Food', 'De-icing', 'Chemical Industry']
  },
  {
    name: 'Sylvite (KCl)',
    type: 'Salt/Mineral',
    pattern: '28.35, 100\n40.50, 50\n50.15, 15\n58.60, 5\n66.35, 10\n73.70, 5',
    description: 'Potassium chloride is a metal halide salt composed of potassium and chlorine.',
    formula: 'KCl',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 1.98,
    applications: ['Fertilizer', 'Medicine', 'Food Processing']
  },
  {
    name: 'Hematite (Fe2O3)',
    type: 'Mineral/Ore',
    pattern: '24.14, 30\n33.15, 100\n35.61, 70\n40.85, 20\n49.48, 40\n54.09, 45\n62.45, 30\n64.02, 30',
    description: 'One of the most abundant minerals on Earth\'s surface and an important ore of iron.',
    formula: 'Fe2O3',
    crystalSystem: 'Trigonal',
    spaceGroup: 'R-3c',
    density: 5.26,
    applications: ['Iron Ore', 'Pigments', 'Radiation Shielding']
  },
  {
    name: 'Aluminum (Al)',
    type: 'Metal',
    pattern: '38.47, 100\n44.74, 47\n65.13, 22\n78.23, 24\n82.44, 7',
    description: 'A silvery-white, soft, non-magnetic and ductile metal.',
    formula: 'Al',
    crystalSystem: 'Face-Centered Cubic',
    spaceGroup: 'Fm-3m',
    density: 2.70,
    applications: ['Aerospace', 'Packaging', 'Construction']
  },
  {
    name: 'Copper (Cu)',
    type: 'Metal',
    pattern: '43.30, 100\n50.43, 46\n74.13, 20\n89.93, 17\n95.14, 5',
    description: 'A soft, malleable, and ductile metal with very high thermal and electrical conductivity.',
    formula: 'Cu',
    crystalSystem: 'Face-Centered Cubic',
    spaceGroup: 'Fm-3m',
    density: 8.96,
    applications: ['Wiring', 'Motors', 'Coinage']
  },
  {
    name: 'Magnesium Oxide (MgO)',
    type: 'Ceramic',
    pattern: '36.94, 10\n42.91, 100\n62.30, 52\n74.65, 4\n78.61, 12',
    description: 'A white hygroscopic solid mineral that occurs naturally as periclase.',
    formula: 'MgO',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 3.58,
    applications: ['Refractories', 'Medicine', 'Insulation']
  },
  {
    name: 'Titanium (Ti)',
    type: 'Metal',
    pattern: '35.09, 30\n38.42, 30\n40.17, 100\n53.00, 15\n62.94, 15\n70.66, 15',
    description: 'A lustrous transition metal with a silver color, low density, and high strength.',
    formula: 'Ti',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/mmc',
    density: 4.50,
    applications: ['Aerospace', 'Implants', 'Pigments']
  },
  {
    name: 'Cerium Oxide (CeO2)',
    type: 'Ceramic/Catalyst',
    pattern: '28.55, 100\n33.08, 30\n47.48, 55\n56.34, 45\n59.09, 10\n69.41, 20',
    description: 'A pale yellow-white powder, highly used as a catalyst and in glass polishing.',
    formula: 'CeO2',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 7.21,
    applications: ['Catalysts', 'Fuel Cells', 'Glass Polishing']
  },
  {
    name: 'Calcite (CaCO3)',
    type: 'Mineral',
    pattern: '23.06, 15\n29.40, 100\n35.96, 15\n39.40, 20\n43.16, 20\n47.50, 25\n48.50, 25\n57.40, 10',
    description: 'A carbonate mineral and the most stable polymorph of calcium carbonate.',
    formula: 'CaCO3',
    crystalSystem: 'Trigonal',
    spaceGroup: 'R-3c',
    density: 2.71,
    applications: ['Construction', 'Agriculture', 'Pharmaceuticals']
  },
  {
    name: 'Tungsten (W)',
    type: 'Metal',
    pattern: '40.26, 100\n58.27, 20\n73.19, 30\n87.01, 15',
    description: 'A rare metal known for its robustness and the highest melting point of all elements.',
    formula: 'W',
    crystalSystem: 'Body-Centered Cubic',
    spaceGroup: 'Im-3m',
    density: 19.25,
    applications: ['Heating elements', 'X-ray tubes', 'Alloys']
  },
  {
    name: 'Diamond (C)',
    type: 'Mineral/Gemstone',
    pattern: '43.92, 100\n75.30, 25\n91.50, 16\n119.52, 7',
    description: 'The hardest natural material known, a metastable allotrope of carbon.',
    formula: 'C',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fd-3m',
    density: 3.51,
    applications: ['Cutting tools', 'Jewelry', 'Heat sinks']
  },
  {
    name: 'Corundum (Al2O3)',
    type: 'Ceramic/Mineral',
    pattern: '25.58, 45\n35.15, 100\n37.78, 40\n43.36, 85\n52.55, 45\n57.50, 90\n61.30, 10\n66.52, 45\n68.21, 60',
    description: 'A crystalline form of aluminum oxide typically containing traces of iron, titanium, vanadium and chromium.',
    formula: 'Al2O3',
    crystalSystem: 'Trigonal',
    spaceGroup: 'R-3c',
    density: 3.98,
    applications: ['Abrasives', 'Refractories', 'Laser host crystals']
  },
  {
    name: 'Rutile (TiO2)',
    type: 'Ceramic/Oxide',
    pattern: '27.44, 100\n36.08, 50\n39.18, 8\n41.22, 25\n44.05, 10\n54.31, 60\n56.62, 20\n62.73, 10\n64.03, 10\n68.99, 20',
    description: 'The most common natural form of TiO2, a major ore of titanium.',
    formula: 'TiO2',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P42/mnm',
    density: 4.23,
    applications: ['Pigments', 'UV filters', 'Optical coatings']
  },
  {
    name: 'Anatase (TiO2)',
    type: 'Ceramic/Oxide',
    pattern: '25.28, 100\n37.80, 20\n48.05, 35\n53.89, 20\n55.06, 20\n62.69, 15',
    description: 'A metastable mineral form of titanium dioxide.',
    formula: 'TiO2',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'I41/amd',
    density: 3.79,
    applications: ['Photocatalysis', 'Solar cells', 'Gas sensors']
  },
  {
    name: 'Barium Titanate (BaTiO3)',
    type: 'Ferroelectric Ceramic',
    pattern: '22.20, 25\n31.50, 100\n38.90, 22\n45.30, 42\n50.90, 18\n56.20, 15\n65.80, 22',
    description: 'A dielectric ceramic used for its high dielectric constant and piezoelectric properties.',
    formula: 'BaTiO3',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P4mm',
    density: 6.02,
    applications: ['Capacitors', 'Transducers', 'Thermistors']
  },
  {
    name: 'Molybdenum Disulfide (MoS2)',
    type: '2D Material/Lubricant',
    pattern: '14.38, 100\n32.67, 12\n33.51, 10\n39.54, 7\n44.15, 6\n49.79, 12\n58.34, 15',
    description: 'A layered transition metal dichalcogenide used as a dry lubricant and in nanoelectronics.',
    formula: 'MoS2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/mmc',
    density: 5.06,
    applications: ['Lubrication', 'Transistors', 'Photodetectors']
  },
  {
    name: 'Lead Titanate (PbTiO3)',
    type: 'Ferroelectric Ceramic',
    pattern: '21.5, 20\n22.8, 25\n31.5, 100\n32.5, 95\n39.0, 15\n44.3, 35\n45.2, 40',
    description: 'A yellow solid that is insoluble in water. It is a classic ferroelectric material.',
    formula: 'PbTiO3',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P4mm',
    density: 7.52,
    applications: ['Transducers', 'Thermal Sensors']
  },
  {
    name: 'Zeolite A (LTA)',
    type: 'Zeolite/Microporous',
    pattern: '7.2, 100\n10.2, 50\n12.5, 60\n16.1, 20\n21.7, 35\n24.0, 45\n27.1, 30\n29.9, 40\n34.2, 25',
    description: 'A synthetic zeolite with a pore size of about 4 Ångströms.',
    formula: 'Na12Al12Si12O48·27H2O',
    crystalSystem: 'Cubic',
    spaceGroup: 'Pm-3m',
    density: 1.55,
    applications: ['Water Softening', 'Catalysis', 'Gas Separation']
  },
  {
    name: 'Silver (Ag)',
    type: 'Metal',
    pattern: '38.12, 100\n44.30, 40\n64.44, 25\n77.40, 26\n81.54, 15',
    description: 'A lustrous, white, soft, very ductile, and malleable transition metal.',
    formula: 'Ag',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 10.49,
    applications: ['Jewelry', 'Electronics', 'Photography']
  },
  {
    name: 'Yttrium Aluminum Garnet (YAG)',
    type: 'Ceramic/Laser Host',
    pattern: '18.1, 15\n27.8, 30\n29.8, 35\n33.3, 100\n36.6, 25\n41.1, 40\n46.6, 35\n55.2, 45\n57.5, 20',
    description: 'A synthetic crystalline material of the garnet group.',
    formula: 'Y3Al5O12',
    crystalSystem: 'Cubic',
    spaceGroup: 'Ia-3d',
    density: 4.55,
    applications: ['Solid-state Lasers', 'Phosphors']
  },
  {
    name: 'Strontium Titanate (SrTiO3)',
    type: 'Perovskite Ceramic',
    pattern: '22.8, 25\n32.4, 100\n39.9, 20\n46.5, 45\n52.4, 10\n57.8, 30\n67.8, 30',
    description: 'An oxide of strontium and titanium. It is a centrosymmetric cubic perovskite.',
    formula: 'SrTiO3',
    crystalSystem: 'Cubic',
    spaceGroup: 'Pm-3m',
    density: 5.11,
    applications: ['Substrates', 'Varistors', 'Optics']
  },
  {
    name: 'Lithium Iron Phosphate (LiFePO4)',
    type: 'Battery Material',
    pattern: '17.1, 40\n20.8, 35\n25.6, 100\n29.7, 45\n32.1, 30\n35.6, 75\n42.1, 15',
    description: 'An olivine-structured compound used as a cathode material for LIBs.',
    formula: 'LiFePO4',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pnma',
    density: 3.6,
    applications: ['EV Batteries', 'Power Tools']
  },
  {
    name: 'Gallium Nitride (GaN)',
    type: 'Semiconductor',
    pattern: '32.39, 100\n34.56, 95\n36.84, 85\n48.12, 20\n57.78, 45\n63.45, 30\n67.82, 35',
    description: 'A binary III/V direct bandgap semiconductor commonly used in bright light-emitting diodes.',
    formula: 'GaN',
    crystalSystem: 'Hexagonal (Wurtzite)',
    spaceGroup: 'P63mc',
    density: 6.1,
    applications: ['LEDs', 'Power Electronics', 'RF Amplifiers']
  },
  {
    name: 'Gold (Au)',
    type: 'Metal',
    pattern: '38.18, 100\n44.39, 52\n64.57, 32\n77.54, 36\n81.72, 10',
    description: 'A transition metal and a group 11 element. It is one of the least reactive chemical elements.',
    formula: 'Au',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 19.3,
    applications: ['Jewelry', 'Electronics', 'Economic Standard']
  },
  {
    name: 'Iron - Alpha (Fe)',
    type: 'Metal',
    pattern: '44.67, 100\n65.02, 20\n82.33, 30\n98.94, 10',
    description: 'The BCC allotrope of iron, stable at room temperature.',
    formula: 'Fe',
    crystalSystem: 'Cubic (BCC)',
    spaceGroup: 'Im-3m',
    density: 7.87,
    applications: ['Structural Steel', 'Magnetic Cores']
  },
  {
    name: 'Zirconia (ZrO2)',
    type: 'Ceramic',
    pattern: '28.17, 100\n31.47, 65\n34.15, 25\n50.12, 35\n50.55, 30\n60.05, 20',
    description: 'Monoclinic zirconia (baddeleyite), a tough ceramic used in structural applications.',
    formula: 'ZrO2',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21/c',
    density: 5.68,
    applications: ['Ceramic Knives', 'Dental Implants', 'Fuel Cells']
  },
  {
    name: 'Graphite',
    type: 'Carbon Allotrope',
    pattern: '26.54, 100\n42.39, 5\n44.59, 15\n54.67, 10\n77.54, 5',
    description: 'A crystalline form of the element carbon with its atoms arranged in a hexagonal structure.',
    formula: 'C',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/mmc',
    density: 2.26,
    applications: ['Lubrication', 'Battery Anodes', 'Pencil Lead']
  },
  {
    name: 'Calcium Fluoride (CaF2)',
    type: 'Haliide Ceramic',
    pattern: '28.27, 100\n46.68, 85\n55.35, 35\n68.17, 15\n75.64, 10\n87.35, 12',
    description: 'The mineral fluorite, used extensively in optics due to its wide transparency range.',
    formula: 'CaF2',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 3.18,
    applications: ['Camera Lenses', 'Flux in Smelting']
  },
  {
    name: 'Nickel (Ni)',
    type: 'Metal',
    pattern: '44.51, 100\n51.85, 45\n76.38, 25\n92.95, 20\n98.45, 10',
    description: 'A silvery-white lustrous metal with a slight golden tinge. It is hard and ductile.',
    formula: 'Ni',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 8.91,
    applications: ['Superalloys', 'Stainless Steel', 'Rechargeable Batteries']
  },
  {
    name: 'Tungsten Carbide (WC)',
    type: 'Hard Ceramic',
    pattern: '31.51, 100\n35.64, 90\n48.30, 80\n64.06, 35\n73.11, 40\n75.48, 25\n77.16, 20',
    description: 'An extremely hard chemical compound containing tungsten and carbon atoms.',
    formula: 'WC',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P-6m2',
    density: 15.63,
    applications: ['Cutting Tools', 'Abrasives', 'Armor-piercing rounds']
  },
  {
    name: 'Magnetite (Fe3O4)',
    type: 'Iron Oxide / Magnetic',
    pattern: '30.1, 40\n35.4, 100\n43.1, 25\n53.4, 20\n57.0, 35\n62.6, 45',
    description: 'A rock-forming mineral and one of the main iron ores, one of the oxides of iron.',
    formula: 'Fe3O4',
    crystalSystem: 'Cubic (Spinel)',
    spaceGroup: 'Fd-3m',
    density: 5.17,
    applications: ['Magnetic Storage', 'Biomedicine', 'Pigments']
  },
  {
    name: 'Methylammonium Lead Iodide (MAPbI3)',
    type: 'Solar Perovskite',
    pattern: '14.1, 100\n24.5, 45\n28.4, 55\n31.8, 30\n40.6, 20\n43.2, 15',
    description: 'A primary material used in high-efficiency perovskite solar cells.',
    formula: 'CH3NH3PbI3',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'I4/mcm',
    density: 4.16,
    applications: ['Photovoltaics', 'Photodetectors']
  },
  {
    name: 'Silicon Carbide (SiC)',
    type: 'Semiconductor/Hard Ceramic',
    pattern: '33.6, 20\n35.6, 100\n38.1, 5\n41.4, 25\n54.5, 10\n60.0, 45\n65.6, 15\n71.8, 35',
    description: 'A hard chemical compound of silicon and carbon. Moissanite is its rare mineral form.',
    formula: '6H-SiC',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63mc',
    density: 3.21,
    applications: ['Power Electronics', 'Abrasives', 'Telescope Mirrors']
  },
  {
    name: 'Gallium Arsenide (GaAs)',
    type: 'Semiconductor',
    pattern: '27.3, 100\n45.3, 45\n53.7, 30\n66.0, 10\n72.8, 15\n83.6, 5',
    description: 'A III-V direct bandgap semiconductor used in integrated circuits and solar cells.',
    formula: 'GaAs',
    crystalSystem: 'Cubic',
    spaceGroup: 'F-43m',
    density: 5.32,
    applications: ['Microwave circuits', 'Solar cells', 'Laser diodes']
  },
  {
    name: 'Bismuth Ferrite (BiFeO3)',
    type: 'Multiferroic Ceramic',
    pattern: '22.4, 20\n31.8, 100\n32.1, 95\n39.0, 15\n39.5, 15\n45.8, 40\n46.2, 35\n51.4, 10\n51.7, 10\n56.5, 20\n57.1, 20',
    description: 'One of the few multiferroic materials that is both ferroelectric and antiferromagnetic at room temp.',
    formula: 'BiFeO3',
    crystalSystem: 'Rhombohedral',
    spaceGroup: 'R3c',
    density: 8.34,
    applications: ['Spintronics', 'Memory storage', 'Photocatalysis']
  },
  {
    name: 'Indium Tin Oxide (ITO)',
    type: 'Transparent Conductor',
    pattern: '21.5, 15\n30.6, 100\n35.4, 30\n37.7, 10\n41.8, 15\n45.7, 15\n51.0, 45\n60.7, 35',
    description: 'A ternary composition of indium, tin and oxygen. It is transparent and conductive.',
    formula: 'In2O3:Sn',
    crystalSystem: 'Cubic',
    spaceGroup: 'Ia-3',
    density: 7.12,
    applications: ['Touchscreens', 'LCDs', 'Smart windows']
  },
  {
    name: 'Pyrite (FeS2)',
    type: 'Mineral/Sulfide',
    pattern: '28.5, 35\n33.0, 100\n37.1, 55\n40.8, 45\n47.4, 45\n56.3, 65\n59.0, 20\n64.3, 25',
    description: 'Known as fool\'s gold, it is an iron sulfide mineral.',
    formula: 'FeS2',
    crystalSystem: 'Cubic',
    spaceGroup: 'Pa-3',
    density: 5.01,
    applications: ['Sulfur production', 'Solar PV research']
  },
  {
    name: 'Chromium (Cr)',
    type: 'Metal',
    pattern: '44.39, 100\n64.58, 18\n81.72, 25\n98.05, 10',
    description: 'A steely-gray, lustrous, hard and brittle transition metal.',
    formula: 'Cr',
    crystalSystem: 'Cubic (BCC)',
    spaceGroup: 'Im-3m',
    density: 7.19,
    applications: ['Stainless Steel', 'Electroplating']
  },
  {
    name: 'Gallium Oxide (Ga2O3)',
    type: 'Semiconductor',
    pattern: '18.9, 35\n30.1, 45\n31.7, 55\n35.2, 100\n38.4, 60\n45.8, 30\n59.1, 25',
    description: 'An inorganic compound and ultra-wide-bandgap semiconductor.',
    formula: 'β-Ga2O3',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'C2/m',
    density: 5.88,
    applications: ['Power Electronics', 'Solar-blind Photodetectors']
  },
  {
    name: 'Cadmium Telluride (CdTe)',
    type: 'Solar Material',
    pattern: '23.8, 100\n39.3, 60\n46.4, 45\n56.8, 15\n62.4, 20\n71.2, 15',
    description: 'A crystalline compound used as an infrared optical window and a solar cell material.',
    formula: 'CdTe',
    crystalSystem: 'Cubic',
    spaceGroup: 'F-43m',
    density: 5.85,
    applications: ['Thin-film Solar Cells', 'Radiation Detectors']
  },
  {
    name: 'Bismuth Telluride (Bi2Te3)',
    type: 'Thermoelectric',
    pattern: '17.4, 45\n27.6, 100\n38.2, 40\n41.1, 35\n44.6, 25\n50.3, 15\n54.1, 15',
    description: 'A gray powder that is a compound of bismuth and tellurium. It is a semiconductor and thermoelectric material.',
    formula: 'Bi2Te3',
    crystalSystem: 'Trigonal',
    spaceGroup: 'R-3m',
    density: 7.74,
    applications: ['Thermoelectric Cooling', 'Power Generation']
  },
  {
    name: 'Tin Oxide (SnO2)',
    type: 'Ceramic/Sensor',
    pattern: '26.6, 100\n33.9, 75\n37.9, 25\n38.9, 20\n51.8, 65\n54.7, 15\n61.9, 20',
    description: 'The mineral cassiterite, the main ore of tin. Used as a gas sensor material.',
    formula: 'SnO2',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P42/mnm',
    density: 6.95,
    applications: ['Gas Sensors', 'Opacifiers', 'TCOs']
  },
  {
    name: 'Lithium Cobalt Oxide (LiCoO2)',
    type: 'Battery Material',
    pattern: '18.9, 100\n36.7, 45\n37.3, 50\n38.4, 35\n45.2, 40\n49.3, 10\n59.2, 25',
    description: 'A chemical compound used as a positive electrode in lithium-ion batteries.',
    formula: 'LiCoO2',
    crystalSystem: 'Rhombohedral',
    spaceGroup: 'R-3m',
    density: 5.06,
    applications: ['LCO Batteries', 'Mobile Electronics']
  },
  {
    name: 'Silicon Nitride (Si3N4)',
    type: 'Hard Ceramic',
    pattern: '20.6, 25\n23.4, 45\n26.5, 35\n30.9, 100\n34.6, 65\n35.3, 60\n38.8, 30\n41.5, 20',
    description: 'A hard, solid ceramic used in high-strength and high-temperature applications.',
    formula: 'β-Si3N4',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/m',
    density: 3.17,
    applications: ['Bearings', 'Turbine Blades', 'Cutting Tools']
  },
  {
    name: 'Aluminum Nitride (AlN)',
    type: 'Ceramic/Semiconductor',
    pattern: '33.2, 100\n36.0, 95\n37.9, 85\n49.8, 25\n59.3, 50\n66.0, 35\n69.7, 30',
    description: 'A technical ceramic with an unusual combination of high thermal conductivity and electrical insulation.',
    formula: 'AlN',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63mc',
    density: 3.26,
    applications: ['Heat Sinks', 'Power Electronics', 'Substrates']
  },
  {
    name: 'Boron Nitride (h-BN)',
    type: 'Hexagonal Ceramic',
    pattern: '26.7, 100\n41.6, 12\n43.8, 15\n50.1, 10\n55.1, 25\n75.9, 5',
    description: 'Often referred to as "white graphite" because of its lubricity and hexagonal structure.',
    formula: 'h-BN',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/mmc',
    density: 2.10,
    applications: ['Solid Lubricants', 'Cosmetics', 'Thermal Management']
  },
  {
    name: 'Gallium Phosphide (GaP)',
    type: 'Semiconductor',
    pattern: '28.3, 100\n32.8, 10\n47.1, 60\n55.8, 45\n68.8, 15\n76.0, 15\n88.0, 10',
    description: 'A phosphide of gallium, an indirect bandgap semiconductor used in some LED devices.',
    formula: 'GaP',
    crystalSystem: 'Cubic',
    spaceGroup: 'F-43m',
    density: 4.14,
    applications: ['LEDs', 'Optical Sensors']
  },
  {
    name: 'Zinc Selenide (ZnSe)',
    type: 'Optical Semiconductor',
    pattern: '27.2, 100\n31.5, 10\n45.3, 85\n53.6, 45\n66.0, 20\n72.7, 25\n83.4, 15',
    description: 'A light-yellow, solid binary compound. It is an intrinsic semiconductor and optical material.',
    formula: 'ZnSe',
    crystalSystem: 'Cubic',
    spaceGroup: 'F-43m',
    density: 5.27,
    applications: ['Infrared Optics', 'CO2 Lasers', 'X-ray Detectors']
  },
  {
    name: 'Tantalum (Ta)',
    type: 'Refractory Metal',
    pattern: '38.4, 100\n55.5, 15\n69.6, 25\n82.4, 10\n94.9, 15',
    description: 'A rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant.',
    formula: 'Ta',
    crystalSystem: 'Cubic (BCC)',
    spaceGroup: 'Im-3m',
    density: 16.69,
    applications: ['Capacitors', 'Surgical Implants', 'Chemical Equipment']
  },
  {
    name: 'Vanadium Pentoxide (V2O5)',
    type: 'Metal Oxide/Catalyst',
    pattern: '15.3, 100\n20.3, 90\n21.7, 45\n26.1, 75\n31.0, 40\n32.4, 35\n34.3, 30\n47.3, 25',
    description: 'The chemical compound with the formula V2O5. It is a poisonous yellow/orange solid.',
    formula: 'V2O5',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pmmn',
    density: 3.36,
    applications: ['Catalysis', 'Battery Cathodes', 'Ferrovanadium Production']
  },
  {
    name: 'Silver Chloride (AgCl)',
    type: 'Haliide Mineral',
    pattern: '27.8, 45\n32.2, 100\n46.2, 65\n54.8, 15\n57.5, 10\n67.5, 15\n74.5, 10\n76.8, 12',
    description: 'A chemical compound with the chemical formula AgCl. It occurs naturally as the mineral chlorargyrite.',
    formula: 'AgCl',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 5.56,
    applications: ['Electrodes', 'Photography', 'Optical Windows']
  },
  {
    name: 'Manganese Oxide (MnO2)',
    type: 'Mineral/Battery',
    pattern: '28.6, 100\n37.3, 90\n42.8, 35\n56.7, 65\n67.3, 25\n72.3, 15',
    description: 'The inorganic compound with the formula MnO2, also known as pyrolusite.',
    formula: 'MnO2',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P42/mnm',
    density: 5.03,
    applications: ['Dry Batteries', 'Oxidizing Agent', 'Pigment']
  },
  {
    name: 'Nickel Oxide (NiO)',
    type: 'Metal Oxide/Semiconductor',
    pattern: '37.3, 85\n43.3, 100\n62.9, 65\n75.4, 15\n79.4, 10',
    description: 'The mineral bunsenite, an antiferromagnetic semiconductor.',
    formula: 'NiO',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 6.67,
    applications: ['Fuel Cells', 'Catalysts', 'Electrochromic Devices']
  },
  {
    name: 'Cobalt(II,III) Oxide (Co3O4)',
    type: 'Spinel Ceramic',
    pattern: '19.0, 20\n31.3, 45\n36.9, 100\n38.6, 15\n44.9, 25\n55.7, 10\n59.4, 30\n65.3, 55',
    description: 'Black antiferromagnetic solid, a mixed-valence compound containing both Co(II) and Co(III).',
    formula: 'Co3O4',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fd-3m',
    density: 6.11,
    applications: ['Gas Sensors', 'Catalysis', 'LCO Production']
  },
  {
    name: 'Lead Zirconate Titanate (PZT)',
    type: 'Piezoelectric Ceramic',
    pattern: '21.6, 25\n31.1, 100\n38.3, 20\n44.5, 40\n45.3, 40\n50.3, 15\n55.3, 15\n65.6, 20',
    description: 'A ceramic perovskite material that shows a marked piezoelectric effect.',
    formula: 'Pb[ZrxTi1-x]O3',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P4mm',
    density: 7.7,
    applications: ['Ultrasound transceivers', 'Actuators', 'SONAR']
  },
  {
    name: 'Barium Ferrite (BaFe12O19)',
    type: 'Permanent Magnet',
    pattern: '30.3, 35\n32.2, 55\n34.1, 100\n37.1, 40\n40.4, 25\n55.1, 20\n63.1, 25',
    description: 'A highly magnetic material, also called barium hexaferrite.',
    formula: 'BaFe12O19',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/mmc',
    density: 5.28,
    applications: ['Magnetic Storage Media', 'Speakers', 'Microwave components']
  },
  {
    name: 'Vanadium Dioxide (VO2)',
    type: 'Phase Change Material',
    pattern: '27.9, 100\n37.1, 35\n42.3, 25\n55.6, 45\n57.7, 30',
    description: 'Known for its reversible metal-insulator transition at 68°C.',
    formula: 'VO2',
    crystalSystem: 'Monoclinic (M1)',
    spaceGroup: 'P21/c',
    density: 4.57,
    applications: ['Smart Windows', 'Optical Switches', 'Thermochemistry']
  },
  {
    name: 'Tungsten Trioxide (WO3)',
    type: 'Metal Oxide/Semiconductor',
    pattern: '23.1, 100\n23.6, 95\n24.4, 95\n26.6, 25\n28.9, 20\n33.3, 45\n34.1, 50\n41.8, 15\n50.0, 15',
    description: 'A transition metal oxide used for its electrochromic and gas sensing properties.',
    formula: 'WO3',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21/n',
    density: 7.16,
    applications: ['Electrochromic Windows', 'Gas Sensors', 'Photocatalysis']
  },
  {
    name: 'Austenite (γ-Fe)',
    type: 'High-Temp Metal',
    pattern: '43.6, 100\n50.7, 45\n74.7, 25\n90.7, 20',
    description: 'The FCC allotrope of iron, typically stable above 912°C or in stainless steels.',
    formula: 'Fe',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 7.9,
    applications: ['Stainless Steel', 'Tooling', 'Aeronautics']
  },
  {
    name: 'Silver(I) Oxide (Ag2O)',
    type: 'Oxide Ceramic',
    pattern: '32.8, 100\n38.1, 40\n55.0, 55\n65.5, 15\n68.8, 18',
    description: 'A chemical compound used in silver-oxide batteries.',
    formula: 'Ag2O',
    crystalSystem: 'Cubic',
    spaceGroup: 'Pn-3m',
    density: 7.14,
    applications: ['Silver Oxide Batteries', 'Antibacterial finish', 'Catalysis']
  },
  {
    name: 'Copper(II) Oxide (CuO)',
    type: 'Semiconductor/Mineral',
    pattern: '32.5, 30\n35.5, 95\n38.7, 100\n48.7, 35\n53.5, 15\n58.3, 20\n61.5, 25\n66.2, 20\n68.1, 20',
    description: 'The mineral tenorite, a black solid and p-type semiconductor.',
    formula: 'CuO',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'C2/c',
    density: 6.31,
    applications: ['Superconductors', 'Pigments', 'Solid Waste disposal']
  },
  {
    name: 'Zinc Sulfide (ZnS)',
    type: 'Semiconductor/Phosphor',
    pattern: '28.5, 100\n47.5, 60\n56.4, 45\n69.4, 15\n76.8, 18',
    description: 'A versatile material used as a white pigment and in electroluminescence.',
    formula: 'ZnS (Sphalerite)',
    crystalSystem: 'Cubic',
    spaceGroup: 'F-43m',
    density: 4.09,
    applications: ['Phosphors', 'Optical Windows', 'Infrared Lenses']
  },
  {
    name: 'beta-Tricalcium Phosphate (beta-TCP)',
    type: 'Biomaterial/Ceramic',
    pattern: '25.8, 15\n27.8, 45\n29.6, 65\n31.0, 100\n34.3, 55\n46.9, 15',
    description: 'A biodegradable ceramic used in bone grafting and tissue engineering.',
    formula: 'beta-Ca3(PO4)2',
    crystalSystem: 'Rhombohedral',
    spaceGroup: 'R3c',
    density: 3.07,
    applications: ['Bone Grafts', 'Dental Fillers', 'Drug Delivery']
  },
  { 
    name: 'Bioactive Glass (45S5)', 
    type: 'Biomaterial/Glass-Ceramic', 
    pattern: '25.0, 30\n30.0, 40\n32.0, 100\n34.0, 60\n47.0, 20',
    description: 'A glass-ceramic material that bonds to both bone and soft tissue.',
    formula: 'Na2O-CaO-P2O5-SiO2',
    crystalSystem: 'Amorphous/Crystalline mixture',
    spaceGroup: 'N/A',
    density: 2.7,
    applications: ['Orthopedics', 'Dentistry', 'Wound Healing']
  },
  { 
    name: 'Bioactive Glass (13-93)', 
    type: 'Biomaterial/Glass', 
    pattern: '25.5, 35\n30.5, 45\n32.5, 100\n34.5, 55\n47.5, 25',
    description: 'A more silicate-rich bioactive glass compared to 45S5, often used for scaffolds and slow-resorption implants.',
    formula: 'SiO2-CaO-Na2O-P2O5-K2O-MgO',
    crystalSystem: 'Glass',
    spaceGroup: 'N/A',
    density: 2.65,
    applications: ['Tissue Scaffolds', 'Drug Delivery']
  },
  { 
    name: 'Bioactive Glass (S53P4)', 
    type: 'Biomaterial/Glass', 
    pattern: '24.8, 30\n29.8, 40\n31.8, 100\n33.8, 60\n46.8, 20',
    description: 'A dedicated clinical grade bioglass with potent antibacterial properties.',
    formula: 'SiO2-Na2O-CaO-P2O5',
    crystalSystem: 'Glass',
    spaceGroup: 'N/A',
    density: 2.70,
    applications: ['Bone Infection Treatment', 'Skull Repair']
  },
  {
    name: 'Brushite (DCPD)',
    type: 'Biomaterial/Mineral',
    pattern: '11.6, 100\n20.9, 60\n23.4, 25\n29.3, 75\n31.2, 45\n34.1, 40',
    description: 'Dicalcium phosphate dihydrate, a precursor to hydroxyapatite in biological systems.',
    formula: 'CaHPO4·2H2O',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'Ia',
    density: 2.31,
    applications: ['Bone Cements', 'Food Additive', 'Dentifrices']
  },
  {
    name: 'Monetite (DCP)',
    type: 'Biomaterial/Mineral',
    pattern: '26.4, 100\n30.2, 85\n32.7, 45\n47.2, 15\n52.1, 10',
    description: 'Anhydrous dicalcium phosphate, used in calcium phosphate cements.',
    formula: 'CaHPO4',
    crystalSystem: 'Triclinic',
    spaceGroup: 'P-1',
    density: 2.92,
    applications: ['Bone Regeneration', 'Tableting Excipient']
  },
  {
    name: 'Bio-Aragonite',
    type: 'Biomaterial/Mineral',
    pattern: '26.2, 100\n33.1, 45\n36.1, 20\n37.8, 30\n38.4, 30\n45.8, 35\n48.4, 25',
    description: 'A calcium carbonate polymorph found in nacre and mollusk shells.',
    formula: 'CaCO3',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pmcn',
    density: 2.93,
    applications: ['Implants', 'Bone Augmentation', 'Biomimetic Materials']
  },
  {
    name: 'Tetracalcium Phosphate (TTCP)',
    type: 'Biomaterial/Ceramic',
    pattern: '25.4, 35\n29.2, 60\n29.8, 100\n31.1, 95\n32.4, 80\n34.5, 40',
    description: 'The most basic calcium phosphate, often used in self-setting cements.',
    formula: 'Ca4(PO4)2O',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21',
    density: 3.05,
    applications: ['Calcium Phosphate Cements', 'Coatings']
  },
  {
    name: 'alpha-Tricalcium Phosphate (alpha-TCP)',
    type: 'Biomaterial/Ceramic',
    pattern: '22.8, 40\n24.2, 35\n30.6, 100\n32.2, 85\n34.1, 55\n46.5, 20',
    description: 'High-temperature polymorph of TCP, highly reactive in water to form HAp.',
    formula: 'alpha-Ca3(PO4)2',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21/a',
    density: 2.86,
    applications: ['Bone Cements', 'Resorbable Ceramics']
  },
  {
    name: 'Lithium Titanate (Li4Ti5O12)',
    type: 'Battery/Anode',
    pattern: '18.4, 100\n35.6, 55\n43.3, 45\n47.4, 15\n57.2, 35\n62.8, 30',
    description: 'An "extremely safe" anode material for lithium-ion batteries with zero-strain characteristics.',
    formula: 'Li4Ti5O12',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fd-3m',
    density: 3.48,
    applications: ['Fast-charge Batteries', 'Heavy Duty EVs']
  },
  {
    name: 'YBCO Superconductor (YBa2Cu3O7)',
    type: 'Superconductor',
    pattern: '22.8, 35\n32.5, 100\n32.8, 95\n38.5, 20\n40.3, 15\n46.7, 45\n58.1, 35',
    description: 'The first material found to become a superconductor above the boiling point of liquid nitrogen.',
    formula: 'YBa2Cu3O7-δ',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pmmm',
    density: 6.38,
    applications: ['Magnetic Levitation', 'Power Cables', 'High-field Magnets']
  },
  {
    name: 'Zeolite ZSM-5',
    type: 'Microporous Catalyst',
    pattern: '7.9, 100\n8.8, 70\n23.1, 95\n23.3, 85\n23.9, 75\n24.4, 55',
    description: 'A high-silica zeolite used extensively in the petroleum industry as a heterogeneous catalyst.',
    formula: 'NanAlnSi96-nO192·16H2O',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pnma',
    density: 1.81,
    applications: ['Fluid Catalytic Cracking', 'Xylene Isomerization']
  },
  {
    name: 'Metal-Organic Framework-5 (MOF-5)',
    type: 'MOF/Gas Storage',
    pattern: '6.8, 100\n9.7, 45\n13.8, 35\n15.4, 20\n23.8, 15',
    description: 'A prototypical metal-organic framework with exceptionally high surface area for gas storage.',
    formula: 'Zn4O(BDC)3',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 0.59,
    applications: ['Hydrogen Storage', 'Carbon Capture', 'Chemical Sensing']
  },
  {
    name: 'Platinum (Pt)',
    type: 'Noble Metal',
    pattern: '39.8, 100\n46.2, 55\n67.5, 35\n81.3, 40\n85.7, 10',
    description: 'A dense, malleable, ductile, highly unreactive precious metal.',
    formula: 'Pt',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 21.45,
    applications: ['Catalytic Converters', 'Electrical Contacts', 'Jewelry']
  },
  {
    name: 'Palladium (Pd)',
    type: 'Noble Metal',
    pattern: '40.1, 100\n46.7, 45\n68.2, 25\n82.1, 30\n86.7, 8',
    description: 'A shiny, silvery-white metal that has the lowest melting point and is the least dense of the PGMs.',
    formula: 'Pd',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 12.02,
    applications: ['Hydrogen Purification', 'Catalysis', 'Electronics']
  },
  {
    name: 'NMC-111 (LiNi1/3Mn1/3Co1/3O2)',
    type: 'Battery Material',
    pattern: '18.7, 100\n36.6, 35\n37.2, 40\n38.3, 30\n44.4, 45\n48.6, 12\n58.5, 25',
    description: 'A mixed metal oxide used as a cathode material in state-of-the-art Li-ion batteries.',
    formula: 'LiNi1/3Mn1/3Co1/3O2',
    crystalSystem: 'Rhombohedral',
    spaceGroup: 'R-3m',
    density: 4.8,
    applications: ['Electric Vehicle Batteries', 'Power Backup']
  },
  {
    name: 'Yttria-Stabilized Zirconia (YSZ)',
    type: 'Fast-Ion Conductor',
    pattern: '30.1, 100\n34.8, 25\n50.2, 60\n59.7, 35\n62.8, 15',
    description: 'Zirconium dioxide stabilized with 8 mol% yttria, an ideal electrolyte for solid oxide fuel cells.',
    formula: '(ZrO2)0.92(Y2O3)0.08',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 5.9,
    applications: ['SOFC Electrolytes', 'Oxygen Sensors', 'Thermal Barrier Coatings']
  },
  {
    name: 'Strontium Ruthenate (SrRuO3)',
    type: 'Conductive Oxide',
    pattern: '22.4, 25\n31.8, 100\n39.3, 20\n45.8, 45\n57.2, 30\n67.1, 35',
    description: 'A metallic ferromagnet with high chemical stability and excellent lattice match for perovskite oxides.',
    formula: 'SrRuO3',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pbnm',
    density: 6.49,
    applications: ['Electrodes in RAM', 'Thin Film Research', 'Spintronics']
  },
  {
    name: 'Graphene Oxide (GO)',
    type: '2D Material',
    pattern: '10.5, 100\n22.0, 15\n26.6, 10\n42.6, 5',
    description: 'A carbon material derived from graphite with hydrophilic oxygen-containing groups.',
    formula: 'C(O,OH)x',
    crystalSystem: 'Layered (Disordered)',
    spaceGroup: 'N/A',
    density: 1.8,
    applications: ['Water Purification', 'Composites', 'Drug Delivery']
  },
  {
    name: 'Octacalcium Phosphate (OCP)',
    type: 'Biomaterial/Mineral',
    pattern: '4.7, 100\n9.4, 30\n22.8, 15\n26.0, 60\n31.6, 50\n33.6, 40',
    description: 'A transient intermediate in bone and tooth formation, structurally similar to hydroxyapatite.',
    formula: 'Ca8(HPO4)2(PO4)4·5H2O',
    crystalSystem: 'Triclinic',
    spaceGroup: 'P-1',
    density: 2.61,
    applications: ['Bone Morphogenesis Research', 'Implants']
  },
  {
    name: 'Cellulose (Type Ib)',
    type: 'Biomaterial/Polymer',
    pattern: '14.8, 60\n16.3, 70\n20.5, 30\n22.6, 100\n34.5, 20',
    description: 'The most abundant natural polymer, forming structural components of plant cell walls.',
    formula: '(C6H10O5)n',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21',
    density: 1.58,
    applications: ['Wound Dressings', 'Tissue Scaffolds', 'Drug Delivery']
  },
  {
    name: 'Chitosan',
    type: 'Biomaterial/Polymer',
    pattern: '10.5, 75\n20.1, 100\n21.8, 40',
    description: 'A linear polysaccharide derived from chitin, exhibiting excellent biocompatibility and antimicrobial properties.',
    formula: '(C6H11NO4)n',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'P212121',
    density: 1.45,
    applications: ['Wound Healing', 'Hemostatic Agents', 'Scaffolds']
  },
  {
    name: 'Silk Fibroin (Beta-Sheet)',
    type: 'Biomaterial/Protein',
    pattern: '9.1, 30\n18.9, 35\n20.7, 100\n24.3, 40\n28.6, 20',
    description: 'The structural protein in silk, forming crystalline beta-sheet regions responsible for its high tensile strength.',
    formula: 'Amino acid copolymer',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21',
    density: 1.35,
    applications: ['Sutures', 'Ligament Repair', 'Biosensors']
  },
  {
    name: 'Calcium Oxalate Monohydrate',
    type: 'Biomaterial/Pathological Mineral',
    pattern: '14.9, 100\n24.4, 45\n30.1, 30\n35.8, 20\n38.2, 25',
    description: 'Whewellite, the primary crystalline component found in most human kidney stones.',
    formula: 'CaC2O4·H2O',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21/c',
    density: 2.12,
    applications: ['Urology Research', 'Biomineralization Studies']
  },
  {
    name: 'Amorphous Calcium Phosphate (ACP)',
    type: 'Biomaterial/Precursor',
    pattern: '30.0, 100', // Typically very broad peak
    description: 'A non-crystalline phase of calcium phosphate, the initial solid phase that precipitates from high supersaturation.',
    formula: 'CaxHy(PO4)z·nH2O',
    crystalSystem: 'Amorphous',
    spaceGroup: 'N/A',
    density: 2.50,
    applications: ['Remineralizing Toothpastes', 'Precursor Studies']
  },
  {
    name: 'Polylactic Acid (PLA)',
    type: 'Biomaterial/Polymer',
    pattern: '16.7, 100\n19.1, 80\n22.3, 30',
    description: 'A biodegradable and bioactive thermoplastic aliphatic polyester derived from renewable resources.',
    formula: '(C3H4O2)n',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'P212121',
    density: 1.25,
    applications: ['3D Printing', 'Medical Implants', 'Biodegradable Packaging']
  },
  {
    name: 'Polyether ether ketone (PEEK)',
    type: 'Biomaterial/Polymer',
    pattern: '18.8, 100\n20.7, 85\n22.8, 90\n28.9, 60',
    description: 'A versatile high-performance semicrystalline engineering thermoplastic used extensively in medical and space applications.',
    formula: '(-C6H4-O-C6H4-O-C6H4-CO-)n',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pbcn',
    density: 1.32,
    applications: ['Spinal Fusion Devices', 'Aerospace Components', 'Bearings']
  },
  {
    name: 'Collagen Type I',
    type: 'Biomaterial/Protein',
    pattern: '8.0, 30\n20.5, 100', // Typical d~1.1 nm and ~0.45 nm halos
    description: 'The most abundant collagen of the human body, serving as a key structural fiber in tendons, bone, and skin.',
    formula: 'Protein Polymer',
    crystalSystem: 'Triple Helix (Hexagonal)',
    spaceGroup: 'N/A',
    density: 1.35,
    applications: ['Tissue Engineering Scaffolds', 'Wound Dressings', 'Cosmetics']
  },
  {
    name: 'Uranium Dioxide (UO2)',
    type: 'Nuclear/Fuel',
    pattern: '28.2, 100\n32.7, 45\n47.0, 50\n55.8, 40\n58.5, 30',
    description: 'An oxide of uranium utilized as the primary nuclear fuel in light water reactors.',
    formula: 'UO2',
    crystalSystem: 'Cubic (Fluorite)',
    spaceGroup: 'Fm-3m',
    density: 10.97,
    applications: ['Nuclear Reactor Fuel', 'Radiological Shielding'],
    molecularWeight: 270.03,
    bandGap: 2.2,
    elasticModulus: 180,
    magneticProperties: 'Paramagnetic (AFM below 30.8 K)',
    opticalProperties: 'Opaque (dark brown/black)',
    hazards: ['Radioactive', 'Toxic (Heavy Metal)']
  },
  {
    name: 'Thorium Dioxide (ThO2)',
    type: 'Nuclear/Fertile Material',
    pattern: '27.6, 100\n31.9, 40\n45.8, 55\n54.4, 45\n57.0, 35',
    description: 'A crystalline fertile powder that can be bred into fissile U-233; possesses the highest melting point of all oxides.',
    formula: 'ThO2',
    crystalSystem: 'Cubic (Fluorite)',
    spaceGroup: 'Fm-3m',
    density: 10.0,
    applications: ['Advanced Nuclear Fuel Cycles', 'High-Temp Crucibles'],
    molecularWeight: 264.04,
    bandGap: 5.7,
    elasticModulus: 250,
    opticalProperties: 'White to slightly yellow powder',
    hazards: ['Radioactive (Mild)']
  },
  {
    name: 'Boron Carbide (B4C)',
    type: 'Nuclear/Control Material',
    pattern: '23.5, 20\n34.9, 80\n37.8, 100\n39.1, 15\n44.8, 25\n53.4, 30',
    description: 'An extremely hard boron-carbon ceramic used in tank armor, bulletproof vests, and notably as control rods in nuclear reactors for neutron absorption.',
    formula: 'B4C',
    crystalSystem: 'Rhombohedral',
    spaceGroup: 'R-3m',
    density: 2.52,
    applications: ['Control Rods', 'Armor Plating', 'Abrasives'],
    molecularWeight: 55.25,
    elasticModulus: 450,
    hazards: ['Hard dust inhalation']
  },
  {
    name: 'Gadolinium Oxide (Gd2O3)',
    type: 'Nuclear/Burnable Poison',
    pattern: '28.6, 100\n33.1, 35\n47.5, 45\n56.4, 40\n59.1, 15\n69.5, 20',
    description: 'A chemical compound used as a neutron-absorbing "burnable poison" in nuclear fuel to manage reactivity over time.',
    formula: 'Gd2O3',
    crystalSystem: 'Cubic',
    spaceGroup: 'Ia-3',
    density: 7.40,
    applications: ['Neutron Absorption', 'Contrast Agents', 'Phosphors'],
    molecularWeight: 362.50,
    bandGap: 5.4,
    opticalProperties: 'White powder, paramagnetic'
  },
  {
    name: 'Plutonium Dioxide (PuO2)',
    type: 'Nuclear/Fuel',
    pattern: '28.6, 100\n33.1, 40\n47.5, 55\n56.4, 45\n59.1, 10\n69.5, 20',
    description: 'A stable ceramic form of plutonium used in MOX fuel and radioisotope thermoelectric generators (RTGs).',
    formula: 'PuO2',
    crystalSystem: 'Cubic (Fluorite)',
    spaceGroup: 'Fm-3m',
    density: 11.46,
    applications: ['MOX Fuel', 'Deep Space Power (RTGs)'],
    molecularWeight: 271.0,
    hazards: ['Highly Radioactive', 'Alpha Emitter', 'Chemically Toxic']
  },
  {
    name: 'Lead (Pb)',
    type: 'Metal/Shielding',
    pattern: '31.3, 100\n36.3, 40\n52.2, 35\n62.1, 45\n65.2, 10\n77.0, 15',
    description: 'A dense, soft, malleable post-transition metal used extensively for radiation shielding due to its high atomic number and density.',
    formula: 'Pb',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 11.34,
    applications: ['Radiation Shielding', 'Batteries', 'Weights'],
    molecularWeight: 207.2,
    hazards: ['Neurotoxic', 'Heavy Metal']
  },
  {
    name: 'Zirconium Hydride (ZrH2)',
    type: 'Nuclear/Moderator',
    pattern: '28.5, 30\n33.0, 100\n47.5, 40\n56.5, 45\n59.2, 15',
    description: 'A metallic hydride used as a moderator and fuel component in specialty reactors like TRIGA.',
    formula: 'ZrH2',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'I4/mmm',
    density: 5.60,
    applications: ['TRIGA Reactor Fuel', 'Neutron Moderation'],
    molecularWeight: 93.24
  },
  {
    name: 'Beryllium Oxide (BeO)',
    type: 'Nuclear/Reflector',
    pattern: '38.5, 100\n41.2, 45\n44.0, 40\n59.3, 20\n69.8, 15',
    description: 'An inorganic compound with high thermal conductivity and low neutron capture cross-section, used as a neutron reflector.',
    formula: 'BeO',
    crystalSystem: 'Hexagonal (Wurtzite)',
    spaceGroup: 'P63mc',
    density: 3.01,
    applications: ['Neutron Reflectors', 'Heat Sinks', 'High-temp Ceramics'],
    molecularWeight: 25.01,
    hazards: ['Extremely Toxic', 'Berylliosis risk']
  },
  {
    name: 'Austenite (γ-Fe)',
    type: 'Metallurgy/Phase',
    pattern: '43.6, 100\n50.8, 45\n74.7, 30\n90.7, 25\n95.9, 10',
    description: 'The face-centered cubic (FCC) phase of iron. High temperature stable phase often retained in stainless steels.',
    formula: 'γ-Fe',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 7.98,
    applications: ['Stainless Steels', 'Shape Memory Alloys'],
    molecularWeight: 55.85
  },
  {
    name: 'Martensite (α\'-Fe)',
    type: 'Metallurgy/Phase',
    pattern: '44.7, 100\n65.0, 15\n82.3, 25\n98.9, 10',
    description: 'A very hard, supersaturated solid solution of carbon in iron. Characterized by a body-centered tetragonal (BCT) structure formed by rapid quenching.',
    formula: 'α\'-Fe',
    crystalSystem: 'Tetragonal (BCT)',
    spaceGroup: 'I4/mmm',
    density: 7.85,
    applications: ['Hardened Steel', 'Tooling'],
    molecularWeight: 55.85
  },
  {
    name: 'Cementite (Fe3C)',
    type: 'Metallurgy/Carbide',
    pattern: '37.7, 60\n39.8, 80\n40.6, 100\n42.9, 70\n43.7, 90\n44.5, 85\n44.9, 95',
    description: 'An intermetallic compound of iron and carbon. Hard and brittle, it is a key constituent in most steels and cast irons.',
    formula: 'Fe3C',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pnma',
    density: 7.67,
    applications: ['Steel Reinforcement', 'Cast Iron'],
    molecularWeight: 179.55
  },
  {
    name: 'Titanium-6Al-4V (α+β)',
    type: 'Metallurgy/Alloy',
    pattern: '35.1, 40\n38.4, 100\n40.2, 80\n53.0, 30\n63.2, 25\n70.6, 20',
    description: 'The most common titanium alloy. Consists of a dual-phase microstructure of alpha and beta phases, offering high strength and corrosion resistance.',
    formula: 'Ti-6Al-4V',
    crystalSystem: 'HCP + BCC',
    spaceGroup: 'P63/mmc + Im-3m',
    density: 4.43,
    applications: ['Aerospace', 'Medical Implants', 'Marine Engineering'],
    molecularWeight: 47.87,
    hazards: ['Combustible dust']
  },
  {
    name: 'Zircaloy-4',
    type: 'Nuclear/Cladding',
    pattern: '31.9, 30\n34.8, 100\n36.5, 90\n47.9, 20\n63.4, 15\n68.1, 10',
    description: 'A zirconium alloy characterized by very low absorption cross-section of thermal neutrons, used for nuclear fuel cladding.',
    formula: 'Zr-1.5Sn-0.2Fe-0.1Cr',
    crystalSystem: 'Hexagonal (HCP)',
    spaceGroup: 'P63/mmc',
    density: 6.56,
    applications: ['Nuclear Fuel Cladding', 'Reactor Core Structures'],
    elasticModulus: 99,
    magneticProperties: 'Paramagnetic',
    opticalProperties: 'Metallic lustrous grey',
    hazards: ['Pyrophoric (powder form)']
  },
  {
    name: 'Nuclear Graphite',
    type: 'Nuclear/Moderator',
    pattern: '26.6, 100\n42.4, 15\n44.6, 25\n54.7, 30\n77.5, 10',
    description: 'Highly purified graphite optimized for its high moderating ratio and structural stability under intense radiation.',
    formula: 'C',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/mmc',
    density: 2.26,
    applications: ['Neutron Moderator', 'Reactor Reflector Components']
  },
  {
    name: 'Neodymium Magnet (Nd2Fe14B)',
    type: 'Magnetic Material',
    pattern: '29.3, 25\n38.4, 40\n41.0, 100\n41.8, 60\n43.7, 45\n49.1, 30\n53.2, 20',
    description: 'The strongest type of permanent magnet commercially available, featuring high coercivity and magnetic remanence.',
    formula: 'Nd2Fe14B',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P42/mnm',
    density: 7.55,
    applications: ['Electric Motors', 'Hard Disk Drives', 'Wind Turbines'],
    molecularWeight: 1081.54,
    elasticModulus: 151,
    magneticProperties: 'Ferromagnetic (High Coercivity)',
    opticalProperties: 'Metallic (usually plated)',
    hazards: ['Mechanical Pinching', 'Brittle']
  },
  {
    name: 'Titanium Carbide (TiC)',
    type: 'Ultra-hard Ceramic',
    pattern: '35.9, 100\n41.7, 85\n60.4, 60\n72.3, 45\n76.0, 15\n89.8, 20',
    description: 'An extremely hard refractory ceramic material, similar to tungsten carbide.',
    formula: 'TiC',
    crystalSystem: 'Cubic (NaCl-type)',
    spaceGroup: 'Fm-3m',
    density: 4.93,
    applications: ['Cutting Tools', 'Coatings', 'Abrasives'],
    molecularWeight: 59.88,
    elasticModulus: 450
  },
  {
    name: 'Chromium(III) Oxide (Cr2O3)',
    type: 'Oxide Ceramic/Mineral',
    pattern: '24.5, 40\n33.6, 100\n36.2, 75\n41.5, 25\n50.2, 40\n54.8, 90\n63.4, 20\n65.1, 35',
    description: 'Eskolaite, a hard green mineral used as a pigment and for polishing.',
    formula: 'Cr2O3',
    crystalSystem: 'Trigonal (Corundum)',
    spaceGroup: 'R-3c',
    density: 5.22,
    applications: ['Green Pigments', 'Polishing compounds', 'Refractories'],
    molecularWeight: 151.99,
    bandGap: 3.4
  },
  {
    name: 'Cobalt Ferrite (CoFe2O4)',
    type: 'Magnetic Ceramic',
    pattern: '30.1, 40\n35.4, 100\n37.1, 15\n43.1, 30\n53.4, 25\n57.0, 45\n62.6, 60',
    description: 'A hard magnetic material with high coercivity and moderate saturation magnetization.',
    formula: 'CoFe2O4',
    crystalSystem: 'Cubic (Spinel)',
    spaceGroup: 'Fd-3m',
    density: 5.29,
    applications: ['Magnetic Recording', 'Ferrofluids', 'Magnetostrictive Sensors'],
    molecularWeight: 234.62,
    magneticProperties: 'Ferrimagnetic'
  },
  {
    name: 'Bismuth Oxychloride (BiOCl)',
    type: 'Photocatalyst/Pigment',
    pattern: '12.0, 100\n24.2, 35\n25.8, 85\n32.5, 75\n33.4, 80\n40.7, 45\n46.6, 60\n49.3, 55',
    description: 'A layered material with excellent light-harvesting and photocatalytic properties.',
    formula: 'BiOCl',
    crystalSystem: 'Tetragonal',
    spaceGroup: 'P4/nmm',
    density: 7.72,
    applications: ['Cosmetic Pigments', 'Photocatalysis', 'Optical Coatings'],
    molecularWeight: 260.43,
    bandGap: 3.2
  },
  {
    name: 'Cesium Lead Iodide (CsPbI3)',
    type: 'Perovskite/Photovoltaic',
    pattern: '14.2, 100\n20.1, 45\n24.6, 35\n28.6, 90\n32.1, 25\n35.3, 30\n40.8, 55',
    description: 'An all-inorganic perovskite material with high thermal stability for solar cells.',
    formula: 'CsPbI3',
    crystalSystem: 'Cubic (at high temp)',
    spaceGroup: 'Pm-3m',
    density: 5.04,
    applications: ['Tandem Solar Cells', 'LEDs', 'Scintillators'],
    molecularWeight: 720.82,
    bandGap: 1.73
  },
  {
    name: 'Titanium MXene (Ti3C2Tx)',
    type: '2D Material',
    pattern: '9.2, 100\n18.4, 15\n27.6, 10\n34.2, 5\n38.9, 12\n42.1, 8\n60.5, 10',
    description: 'A prominent member of the MXene family of two-dimensional transition metal carbides.',
    formula: 'Ti3C2Tx',
    crystalSystem: 'Hexagonal (Layered)',
    spaceGroup: 'P63/mmc',
    density: 4.8,
    applications: ['Energy Storage', 'EMI Shielding', 'Water Purification'],
    opticalProperties: 'Metallic conductivity and hydrophilic surface'
  },
  {
    name: 'UiO-66 (Zr-MOF)',
    type: 'Metal-Organic Framework',
    pattern: '7.4, 100\n8.5, 95\n12.1, 45\n14.1, 15\n14.8, 20\n17.1, 25\n25.7, 10',
    description: 'A highly stable zirconium-based MOF with exceptional chemical and thermal resistance.',
    formula: 'Zr6O4(OH)4(BDC)6',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 1.2,
    applications: ['Gas Adsorption', 'Chemical Sensing', 'Catalysis'],
    molecularWeight: 1622.0
  },
  {
    name: 'HKUST-1 (Cu-MOF)',
    type: 'Metal-Organic Framework',
    pattern: '6.7, 100\n9.5, 65\n11.6, 85\n13.4, 25\n14.7, 20\n17.5, 40\n19.0, 35\n26.0, 15',
    description: 'A well-known copper-based MOF with high surface area and open metal sites.',
    formula: 'Cu3(BTC)2',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 0.88,
    applications: ['Gas Storage', 'Small Molecule Separation', 'Sensors'],
    molecularWeight: 604.87
  },
  {
    name: 'Molybdenum Trioxide (MoO3)',
    type: 'Semiconductor/Oxide',
    pattern: '12.8, 100\n23.3, 85\n25.7, 95\n27.3, 75\n33.7, 45\n39.0, 35\n49.3, 40',
    description: 'An n-type semiconductor used in electrochromic devices and catalysis.',
    formula: 'α-MoO3',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pbnm',
    density: 4.69,
    applications: ['Catalysis', 'Gas Sensors', 'Smart Windows'],
    molecularWeight: 143.94,
    bandGap: 3.0
  },
  {
    name: 'Vanadium(III) Oxide (V2O3)',
    type: 'Oxide/Mott Insulator',
    pattern: '24.3, 35\n33.0, 100\n36.2, 80\n41.2, 20\n49.7, 30\n54.0, 95\n62.9, 15\n64.1, 25',
    description: 'A classic Mott insulator that undergoes a metal-insulator transition around 150 K.',
    formula: 'V2O3',
    crystalSystem: 'Trigonal (Corundum)',
    spaceGroup: 'R-3c',
    density: 4.87,
    applications: ['Electronic Threshold Switches', 'Cryogenic Thermometers'],
    molecularWeight: 149.88
  },
  {
    name: 'Hematite (Fe2O3)',
    type: 'Oxide Mineral',
    pattern: '24.1, 40\n33.2, 100\n35.6, 75\n40.9, 25\n49.5, 40\n54.1, 85\n62.5, 30\n64.0, 35',
    description: 'The mineral form of iron(III) oxide, one of several iron oxides.',
    formula: 'Fe2O3',
    crystalSystem: 'Trigonal',
    spaceGroup: 'R-3c',
    density: 5.24,
    applications: ['Iron Ore', 'Pigments', 'Polishing compounds'],
    magneticProperties: 'Antiferromagnetic/Weak Ferromagnetic'
  },
  {
    name: 'Perovskite (CaTiO3)',
    type: 'Definitive Perovskite',
    pattern: '23.2, 25\n33.1, 100\n40.3, 15\n47.5, 45\n53.8, 10\n59.2, 35\n69.6, 30',
    description: 'The namesake of the perovskite crystal structure, found in the Earth\'s mantle.',
    formula: 'CaTiO3',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pbnm',
    density: 3.98,
    applications: ['Geological Studies', 'High-temp Ceramics']
  },
  {
    name: 'Feldspar (Orthoclase)',
    type: 'Silicate Mineral',
    pattern: '13.1, 30\n21.0, 25\n23.6, 100\n26.5, 80\n27.8, 45\n29.9, 15',
    description: 'A common rock-forming tectosilicate mineral.',
    formula: 'KAlSi3O8',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'C2/m',
    density: 2.56,
    applications: ['Glassmaking', 'Ceramics', 'Abrasives']
  },
  { 
    name: 'Stainless Steel 316L', 
    type: 'Metal Alloy', 
    pattern: '43.6, 100\n50.8, 45\n74.7, 25\n90.7, 20\n95.9, 10',
    description: 'Low-carbon FCC austenitic steel with excellent corrosion resistance containing Mo.',
    formula: 'Fe-Cr-Ni-Mo (316L)',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 8.0,
    applications: ['Medical Implants', 'Marine Hardware', 'Chemical Processing']
  },
  { 
    name: 'Stainless Steel 304', 
    type: 'Metal Alloy', 
    pattern: '43.5, 100\n50.7, 45\n74.5, 25\n90.5, 20\n95.7, 10',
    description: 'The most common austenitic stainless steel, widely used in various industries.',
    formula: 'Fe-Cr-Ni (304)',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 7.93,
    applications: ['Food Processing', 'Kitchenware', 'Building Facades']
  },
  { 
    name: 'Stainless Steel 310', 
    type: 'Metal Alloy', 
    pattern: '43.4, 100\n50.5, 40\n74.2, 20\n90.2, 15\n95.4, 8',
    description: 'Heat-resistant austenitic stainless steel with high chromium and nickel content.',
    formula: 'Fe-Cr-Ni (310)',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 7.9,
    applications: ['Kiln Linings', 'Furnace Parts', 'Heat Exchangers']
  },
  { 
    name: 'Stainless Steel 430', 
    type: 'Metal Alloy', 
    pattern: '44.5, 100\n64.8, 15\n82.1, 20\n98.7, 10',
    description: 'Ferritic stainless steel (BCC) with good corrosion resistance and formability.',
    formula: 'Fe-Cr (430)',
    crystalSystem: 'Cubic (BCC)',
    spaceGroup: 'Im-3m',
    density: 7.7,
    applications: ['Automotive Trim', 'Appliance Panels']
  },
  {
    name: 'Ti-6Al-4V (Grade 5)',
    type: 'Metal Alloy',
    pattern: '35.1, 30\n38.4, 30\n40.2, 100\n53.0, 20\n63.3, 25\n70.6, 20\n76.2, 15',
    description: 'High-strength alpha-beta titanium alloy, widely used in aerospace and medical implants.',
    formula: 'Ti-6Al-4V',
    crystalSystem: 'Hexagonal (Alpha) + Cubic (Beta)',
    spaceGroup: 'P63/mmc',
    density: 4.43,
    applications: ['Aerospace Structures', 'Engine Components', 'Surgical Tools']
  },
  {
    name: 'Brass (C26000)',
    type: 'Metal Alloy',
    pattern: '42.6, 100\n49.6, 45\n72.8, 20\n88.1, 15',
    description: 'A copper-zinc alloy (70-30), exhibiting good strength and corrosion resistance.',
    formula: 'Cu-Zn (Brass)',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 8.53,
    applications: ['Ammunition', 'Plumbing', 'Musical Instruments']
  },
  {
    name: 'Inconel 718',
    type: 'Superalloy',
    pattern: '43.8, 100\n51.0, 48\n75.1, 22\n91.2, 18',
    description: 'Nickel-chromium-based superalloy used for high-temperature applications.',
    formula: 'Ni-Cr-Fe-Nb-Mo',
    crystalSystem: 'Cubic (FCC)',
    spaceGroup: 'Fm-3m',
    density: 8.19,
    applications: ['Jet Engines', 'Gas Turbines', 'Nuclear Reactors']
  },
  {
    name: 'SBA-15 (Mesoporous Silica)',
    type: 'Drug Delivery',
    pattern: '0.9, 100\n1.6, 30\n1.8, 25',
    description: 'Hexagonal mesoporous silica with high surface area and thick walls.',
    formula: 'SiO2',
    crystalSystem: 'Hexagonal (2D)',
    spaceGroup: 'p6mm',
    density: 0.6,
    applications: ['Drug Loading', 'Catalysis', 'Adsorption']
  },
  {
    name: 'MCM-41 (Mesoporous Silica)',
    type: 'Drug Delivery',
    pattern: '2.1, 100\n3.6, 15\n4.2, 10',
    description: 'Ordered mesoporous material with high pore volume and surface area.',
    formula: 'SiO2',
    crystalSystem: 'Hexagonal (2D)',
    spaceGroup: 'p6mm',
    density: 0.7,
    applications: ['Controlled Release', 'Environmental Remediation']
  },
  {
    name: 'MOF-5 (Zinc Tera-terephthalate)',
    type: 'Framework',
    pattern: '6.8, 100\n9.7, 45\n13.8, 35\n14.1, 20',
    description: 'Classic Metal-Organic Framework with high porosity for gas storage and drug delivery.',
    formula: 'Zn4O(BDC)3',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 0.59,
    applications: ['Hydrogen Storage', 'Drug Delivery Carriers']
  },
  {
    name: 'ZIF-8 (Zeolitic Imidazolate Framework)',
    type: 'Framework',
    pattern: '7.3, 100\n10.3, 40\n12.7, 30\n14.7, 15\n16.4, 25\n18.0, 10',
    description: 'Chemically stable MOF used for pH-responsive drug delivery.',
    formula: 'Zn(mIm)2',
    crystalSystem: 'Cubic',
    spaceGroup: 'I-43m',
    density: 0.95,
    applications: ['Biotech', 'Drug Encapsulation', 'Gas Separation']
  },
  {
    name: 'Ibuprofen (Crystalline)',
    type: 'Pharmaceutical',
    pattern: '6.1, 80\n12.2, 50\n16.6, 100\n17.7, 45\n18.9, 60\n20.2, 70\n22.3, 90',
    description: 'Propionic acid derivative drug, showing sharp Bragg peaks in its crystalline form.',
    formula: 'C13H18O2',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21/c',
    density: 1.03,
    applications: ['Anti-inflammatory', 'Drug Delivery Studies']
  },
  {
    name: 'Paracetamol (Acetaminophen)',
    type: 'Pharmaceutical',
    pattern: '12.1, 40\n15.5, 60\n18.2, 100\n20.4, 35\n23.5, 45\n24.4, 80\n32.8, 20',
    description: 'Common analgesic. Studied for polymorphic transitions in drug formulation.',
    formula: 'C8H9NO2',
    crystalSystem: 'Monoclinic (Form I)',
    spaceGroup: 'P21/n',
    density: 1.29,
    applications: ['Analgesics', 'Crystallization Research']
  },
  {
    name: 'Magnetite (Fe3O4)',
    type: 'Magnetic Oxide',
    pattern: '30.1, 30\n35.4, 100\n43.1, 20\n53.4, 10\n57.0, 30\n62.6, 40',
    description: 'A common ferrimagnetic iron oxide mineral with an inverse spinel structure.',
    formula: 'Fe3O4',
    crystalSystem: 'Cubic (Spinel)',
    spaceGroup: 'Fd-3m',
    density: 5.17,
    applications: ['Magnetic Storage', 'Biomedical Imaging', 'Catalysis']
  },
  {
    name: 'Polyethylene (PE)',
    type: 'Polymer',
    pattern: '21.5, 100\n24.0, 45\n36.3, 10',
    description: 'Semicrystalline thermoplastic showing characteristic orthorhombic crystalline peaks.',
    formula: '(C2H4)n',
    crystalSystem: 'Orthorhombic (Crystalline)',
    spaceGroup: 'Pnam',
    density: 0.94,
    applications: ['Packaging', 'Consumer Goods', 'Industrial Pipes']
  },
  {
    name: 'YBCO Superconductor',
    type: 'Superconductor',
    pattern: '32.5, 80\n32.8, 100\n38.5, 20\n46.7, 45\n58.1, 30',
    description: 'High-temperature superconducting ceramic material (Yttrium Barium Copper Oxide).',
    formula: 'YBa2Cu3O7',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pmmm',
    density: 6.38,
    applications: ['Maglev Trains', 'MRI Machines', 'Particle Accelerators']
  },
  {
    name: 'Portland Cement (Alite)',
    type: 'Construction material',
    pattern: '29.4, 100\n32.2, 80\n32.6, 85\n34.4, 40\n41.2, 35\n51.7, 30',
    description: 'The primary active phase (Tricalcium Silicate) in Portland cement clinker.',
    formula: 'Ca3SiO5 (C3S)',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'Cm',
    density: 3.15,
    applications: ['Infrastructure', 'Building Construction', 'Concrete']
  },
  {
    name: 'Graphene (C)',
    type: '2D Material',
    pattern: '26.3, 100\n42.4, 15\n44.6, 20\n54.7, 10\n77.6, 5',
    description: 'A single layer of carbon atoms arranged in a two-dimensional honeycomb lattice.',
    formula: 'C',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P6/mmm',
    density: 2.26,
    applications: ['Transistors', 'Sensors', 'Batteries']
  },
  {
    name: 'Lithium Manganese Oxide (LiMn2O4)',
    type: 'Battery Cathode',
    pattern: '18.6, 100\n36.1, 40\n43.8, 30\n58.0, 25\n63.9, 15\n76.5, 10',
    description: 'Spinel-structured oxide used as a cathode material in lithium-ion batteries.',
    formula: 'LiMn2O4',
    crystalSystem: 'Cubic (Spinel)',
    spaceGroup: 'Fd-3m',
    density: 4.28,
    applications: ['EV Batteries', 'Power Tools']
  },
  {
    name: 'Bismuth (Bi)',
    type: 'Metal',
    pattern: '22.5, 20\n27.1, 100\n37.9, 30\n39.6, 35\n48.7, 15\n62.2, 10',
    description: 'A brittle metal with a pinkish tinge, known for its remarkably low thermal conductivity and high diamagnetism.',
    formula: 'Bi',
    crystalSystem: 'Rhombohedral',
    spaceGroup: 'R-3m',
    density: 9.78,
    applications: ['Alloys', 'Thermoelectrics', 'Cosmetics']
  },
  {
    name: 'Germanium (Ge)',
    type: 'Semiconductor',
    pattern: '27.3, 100\n45.3, 55\n53.7, 35\n66.0, 10\n72.8, 15\n83.7, 5',
    description: 'A lustrous, hard, grayish-white metalloid in the carbon group, used historically in early transistors.',
    formula: 'Ge',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fd-3m',
    density: 5.32,
    applications: ['Fiber Optics', 'IR Optics', 'Solar Cells']
  },
  {
    name: 'Titanium Nitride (TiN)',
    type: 'Hard Coating',
    pattern: '36.6, 40\n42.6, 100\n61.8, 45\n74.1, 20\n77.9, 15',
    description: 'An extremely hard ceramic material, often used as a coating to improve surface properties.',
    formula: 'TiN',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 5.22,
    applications: ['Cutting Tools', 'Medical Implants', 'Microelectronics']
  },
  {
    name: 'Molybdenum (Mo)',
    type: 'Metal',
    pattern: '40.5, 100\n58.6, 30\n73.7, 18\n87.6, 8\n101.4, 5',
    description: 'A refractory metal used in high-strength alloys and high-temperature applications.',
    formula: 'Mo',
    crystalSystem: 'Cubic',
    spaceGroup: 'Im-3m',
    density: 10.28,
    applications: ['Alloys', 'Electrodes', 'Catalysts']
  },
  {
    name: 'Iridium (Ir)',
    type: 'Metal',
    pattern: '40.7, 100\n47.3, 45\n69.3, 28\n83.6, 32\n88.4, 10',
    description: 'A very hard, brittle, silvery-white transition metal of the platinum group.',
    formula: 'Ir',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 22.56,
    applications: ['Spark Plugs', 'Crucibles', 'Electrical Contacts']
  },
  {
    name: 'Osmium (Os)',
    type: 'Metal',
    pattern: '41.6, 30\n43.7, 100\n45.8, 40\n60.4, 25\n72.3, 15\n85.4, 18',
    description: 'The densest naturally occurring element, a hard, brittle, bluish-white transition metal.',
    formula: 'Os',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63/mmc',
    density: 22.59,
    applications: ['Electrical Contacts', 'Fountain Pen Nibs', 'Alloys']
  },
  {
    name: 'Rhodium (Rh)',
    type: 'Metal',
    pattern: '41.1, 100\n47.8, 45\n70.2, 25\n84.7, 30\n89.6, 12',
    description: 'A rare, silvery-white, hard, corrosion-resistant transition metal.',
    formula: 'Rh',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 12.41,
    applications: ['Catalytic Converters', 'Jewelry', 'Electrical Contacts']
  },
  {
    name: 'Lithium Tantalate (LiTaO3)',
    type: 'Ferroelectric',
    pattern: '23.7, 100\n32.6, 50\n34.8, 40\n46.5, 30\n53.2, 25\n56.7, 20',
    description: 'A piezoelectric and ferroelectric material highly useful in nonlinear optics and surface acoustic wave devices.',
    formula: 'LiTaO3',
    crystalSystem: 'Trigonal',
    spaceGroup: 'R3c',
    density: 7.45,
    applications: ['SAW Devices', 'Optics', 'Detectors']
  },
  {
    name: 'Lithium Niobate (LiNbO3)',
    type: 'Ferroelectric',
    pattern: '23.7, 100\n32.7, 55\n34.8, 45\n46.1, 35\n52.8, 25\n56.3, 20',
    description: 'A colorless solid, known for its optical properties including the linear electro-optic effect.',
    formula: 'LiNbO3',
    crystalSystem: 'Trigonal',
    spaceGroup: 'R3c',
    density: 4.65,
    applications: ['Optical Modulators', 'SAW Devices', 'Holography']
  },
  {
    name: 'Lead Sulphide (PbS)',
    type: 'Semiconductor',
    pattern: '26.0, 100\n30.1, 80\n43.1, 60\n51.0, 40\n53.4, 25\n62.5, 20\n68.9, 15\n71.0, 10\n79.0, 8',
    description: 'Known as galena, a narrow bandgap semiconductor used in infrared detectors.',
    formula: 'PbS',
    crystalSystem: 'Cubic',
    spaceGroup: 'Fm-3m',
    density: 7.6,
    applications: ['Infrared Detectors', 'Photography', 'Optoelectronics']
  },
  {
    name: 'Zinc Telluride (ZnTe)',
    type: 'Semiconductor',
    pattern: '25.3, 100\n41.9, 60\n49.6, 40\n60.4, 15\n67.1, 20\n76.5, 10',
    description: 'A binary chemical compound with a direct band gap, used in optoelectronic devices.',
    formula: 'ZnTe',
    crystalSystem: 'Cubic',
    spaceGroup: 'F-43m',
    density: 6.34,
    applications: ['LEDs', 'Solar Cells', 'Terahertz Generators']
  },
  {
    name: 'Lanthanum Aluminate (LaAlO3)',
    type: 'Substrate / Oxide',
    pattern: '23.4, 50\n33.1, 100\n41.2, 12\n47.5, 60\n54.2, 18\n58.9, 45',
    description: 'A synthetic ceramic oxide that is widely used as a high-quality substrate for epitaxial growth of thin films.',
    formula: 'LaAlO3',
    crystalSystem: 'Rhombohedral',
    spaceGroup: 'R-3c',
    density: 6.52,
    applications: ['Substrates', 'Superconductivity Films', 'Ferroics']
  },
  {
    name: 'Cuprite (Cu2O)',
    type: 'Semiconductor',
    pattern: '29.5, 35\n36.4, 100\n42.3, 40\n61.3, 25\n73.5, 20\n77.3, 15',
    description: 'A copper oxide mineral that naturally crystallizes as an octahedral cubic structure and acts as a p-type semiconductor.',
    formula: 'Cu2O',
    crystalSystem: 'Cubic',
    spaceGroup: 'Pn-3m',
    density: 6.0,
    applications: ['Solar Cells', 'Photocatalysis', 'Chemical Sensors']
  },
  {
    name: 'Cadmium Selenide (CdSe)',
    type: 'Semiconductor',
    pattern: '25.4, 100\n27.1, 70\n28.2, 85\n35.1, 35\n42.2, 50\n45.8, 40\n49.7, 30',
    description: 'A binary solid semiconductor known for its highly tunable optical properties when structured as colloidal quantum dots.',
    formula: 'CdSe',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P63mc',
    density: 5.81,
    applications: ['Quantum Dots', 'Nanolasers', 'Photo-detectors']
  },
  {
    name: 'Silicon Monoxide (SiO)',
    type: 'Amorphous / Anode',
    pattern: '24.0, 100\n40.0, 15',
    description: 'An amorphous Silicon compound favored for lithium battery anodes due to high capacity and minimized swelling compared to pure Silicon.',
    formula: 'SiO',
    crystalSystem: 'Amorphous',
    spaceGroup: 'None',
    density: 2.13,
    applications: ['Li-Ion Anodes', 'Optical Coatings', 'Insulating Barriers']
  },
  {
    name: 'Yttrium Oxide (Y2O3)',
    type: 'Refractory Oxide',
    pattern: '29.1, 100\n33.7, 45\n48.5, 55\n57.6, 35\n78.4, 20',
    description: 'An air-stable white solid refractory substance, widely used in optics and host materials for phosphors.',
    formula: 'Y2O3',
    crystalSystem: 'Cubic',
    spaceGroup: 'Ia-3',
    density: 5.01,
    applications: ['Laser Materials', 'Phosphor Hosts', 'Thermal Barrier Coatings']
  },
  {
    name: 'Barium Zirconate (BaZrO3)',
    type: 'Cubic Ceramic',
    pattern: '21.2, 10\n30.1, 100\n37.1, 35\n43.1, 60\n53.5, 45\n62.6, 50',
    description: 'A high melting point ceramic possessing high protonic conductivity, ideal for solid oxide fuel cell membranes.',
    formula: 'BaZrO3',
    crystalSystem: 'Cubic',
    spaceGroup: 'Pm-3m',
    density: 6.22,
    applications: ['Solid Oxide Fuel Cells', 'High-Temp Crucibles', 'Proton Conductors']
  },
  {
    name: 'NASICON (Na3Zr2Si2PO12)',
    type: 'Solid Electrolyte',
    pattern: '19.2, 100\n22.8, 70\n27.5, 55\n30.4, 85\n34.2, 40\n47.8, 30',
    description: 'Sodium Super Ionic Conductor with high ionic conductivity at room temperature, crucial for standard solid state Sodium battering systems.',
    formula: 'Na3Zr2Si2PO12',
    crystalSystem: 'Trigonal',
    spaceGroup: 'R-3c',
    density: 3.27,
    applications: ['Sodium Batteries', 'Solid-State Electrolytes', 'Ion-Selective Sensors']
  },
  {
    name: 'Titanium Disulfide (TiS2)',
    type: 'Semiconductor',
    pattern: '15.5, 100\n34.1, 80\n44.2, 45\n53.9, 50\n60.4, 25',
    description: 'A layered transition metal dichalcogenide compound with a high electrical conductivity and excellent intercalation chemistry.',
    formula: 'TiS2',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'P-3m1',
    density: 3.22,
    applications: ['Cathode Intercalation', 'Solid State Batteries', 'Thermoelectric Converters']
  },
  {
    name: 'Hafnium Oxide (HfO2)',
    type: 'High-k Dielectric',
    pattern: '28.2, 100\n31.5, 75\n34.2, 35\n41.2, 20\n50.2, 30',
    description: 'A high-k dielectric material used as gate oxides in modern computer processors and dynamic random-access memory (DRAM).',
    formula: 'HfO2',
    crystalSystem: 'Monoclinic',
    spaceGroup: 'P21/c',
    density: 9.68,
    applications: ['CPU Gate Oxide', 'DRAM Capacitors', 'Optical Coatings']
  },
  {
    name: 'Lead-Free Solder (SAC305)',
    type: 'PCB Interconnect',
    pattern: '30.6, 100\n32.0, 90\n43.9, 70\n44.9, 60\n55.3, 30\n62.5, 30',
    description: 'An alloy composed of Tin, Silver, and Copper (Sn-Ag-Cu), widely used as solder for computer hardware printed circuit boards.',
    formula: 'Sn-3.0Ag-0.5Cu',
    crystalSystem: 'Tetragonal (Sn matrix)',
    spaceGroup: 'I41/amd',
    density: 7.38,
    applications: ['PCB Assembly', 'SMD Soldering', 'Electronic Packaging']
  },
  {
    name: 'Tantalum Pentoxide (Ta2O5)',
    type: 'Dielectric Ceramic',
    pattern: '22.9, 100\n28.3, 40\n36.7, 50\n46.8, 30\n55.6, 25',
    description: 'A high refractive index and high dielectric constant material used in motherboard decoupler capacitors.',
    formula: 'Ta2O5',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Pccm',
    density: 8.2,
    applications: ['Tantalum Capacitors', 'Anti-reflective Coatings', 'RAM Memories']
  },
  {
    name: 'Single-Walled Carbon Nanotubes (SWCNTs)',
    type: '1D Nanoelectronics',
    pattern: '26.1, 100\n42.8, 35\n44.4, 25\n53.8, 12\n77.9, 8',
    description: 'Seamless cylinders of graphene sheets demonstrating ballistical electron conductivity, studied as channels for sub-3nm transistors.',
    formula: 'C (SWCNT)',
    crystalSystem: 'Chiral / Hexagonal',
    spaceGroup: 'Pseudo-P6/mmm',
    density: 1.3,
    applications: ['1D Transistors', 'Interconnects', 'Nanostructured Electrodes']
  },
  {
    name: 'Black Phosphorus (Phosphorene)',
    type: '2D Semiconductor',
    pattern: '16.9, 100\n34.2, 85\n52.3, 40\n62.1, 20\n65.9, 15',
    description: 'An anisotropic layered elemental 2D semiconductor possessing a direct bandgap and exceptionally high charge-carrier mobility.',
    formula: 'P (Phosphorene)',
    crystalSystem: 'Orthorhombic',
    spaceGroup: 'Cmca',
    density: 2.69,
    applications: ['Optoelectronics', 'High-Speed FETs', 'Gas Sensors']
  },
  {
    name: 'Indium Gallium Zinc Oxide (IGZO)',
    type: 'Thin-Film Transistor',
    pattern: '30.2, 45\n35.5, 100\n55.4, 30\n60.8, 25',
    description: 'An amorphous or highly textured oxide semiconductor used primarily as the active channel material of thin-film transistors (TFTs) in OLED/LCD displays.',
    formula: 'InGaZnO4',
    crystalSystem: 'Hexagonal',
    spaceGroup: 'R-3m',
    density: 6.25,
    applications: ['OLED Displays', 'Active-Matrix Backplanes', 'Transparent Electronics']
  },
  {
    name: 'Superparamagnetic Iron Oxide Nanoparticles (SPIONs)',
    type: 'Nanomedicine',
    pattern: '30.1, 30\n35.5, 100\n43.1, 20\n53.4, 10\n57.0, 30\n62.6, 40',
    description: 'Biocompatible magnetite/maghemite core nanoparticles used as T2 MRI contrast enhancement agents and in target-guided magnetic hyperthermia cancer therapy.',
    formula: 'Fe3O4 (SPION)',
    crystalSystem: 'Cubic (Broadened)',
    spaceGroup: 'Fd-3m',
    density: 5.15,
    applications: ['MRI Contrast', 'Magnetic Hyperthermia', 'Drug Delivery Carriers']
  },
  {
    name: 'Mesoporous Silica Nanoparticles (MSN / MCM-41)',
    type: 'Nanomedicine Carrier',
    pattern: '2.3, 100\n4.0, 20\n4.6, 15\n22.0, 8',
    description: 'A solid silicate framework featuring highly organized hexagonal arrays of mesopores, ideal for high-capacity drug loading and controlled release.',
    formula: 'SiO2 (MSN)',
    crystalSystem: 'Hexagonal Pores / Amorphous matrix',
    spaceGroup: 'p6mm',
    density: 1.4,
    applications: ['Targeted Drug Delivery', 'Gene Therapy', 'Theranostics']
  },
  {
    name: 'Silver Nanoparticles (AgNPs)',
    type: 'Antimicrobial Nanomedicine',
    pattern: '38.1, 100\n44.3, 40\n64.4, 25\n77.4, 26\n81.5, 8',
    description: 'Ultrafine silver crystals with extremely high surface-to-volume ratio, demonstrating potent oligodynamic antimicrobic/antiviral effects.',
    formula: 'Ag (Nano)',
    crystalSystem: 'Cubic (Broadened)',
    spaceGroup: 'Fm-3m',
    density: 10.49,
    applications: ['Antimicrobial Coatings', 'Wound Dressings', 'Catalysts']
  }
];