import sys
import json
import io
import base64
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.patches as patches

try:
    from scipy.optimize import curve_fit
    from scipy.special import wofz
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False


def gaussian(x, x0, fwhm, height):
    """Standard Gaussian normal distribution profile."""
    sigma = max(1e-7, fwhm / (2.0 * np.sqrt(2.0 * np.log(2.0))))
    return height * np.exp(-0.5 * ((x - x0) / sigma) ** 2)


def lorentzian(x, x0, fwhm, height):
    """Cauchy-Lorentzian profile."""
    gamma = max(1e-7, fwhm / 2.0)
    return height / (1.0 + ((x - x0) / gamma) ** 2)


def pseudo_voigt(x, x0, fwhm, eta, height):
    """
    Pseudo-Voigt peak profile: linear combination of Gaussian and Lorentzian.
    eta = 0: Pure Gaussian
    eta = 1: Pure Lorentzian
    """
    eta = np.clip(eta, 0.0, 1.0)
    sigma = max(1e-7, fwhm / (2.0 * np.sqrt(2.0 * np.log(2.0))))
    gamma = max(1e-7, fwhm / 2.0)
    
    G = np.exp(-0.5 * ((x - x0) / sigma) ** 2)
    L = 1.0 / (1.0 + ((x - x0) / gamma) ** 2)
    
    return height * ((1.0 - eta) * G + eta * L)


def true_voigt(x, x0, fwhm_g, fwhm_l, height):
    """
    True Voigt profile via Faddeeva function w(z).
    fwhm_g: Gaussian FWHM (instrumental & strain broadening)
    fwhm_l: Lorentzian FWHM (crystallite size & lifetime broadening)
    """
    if not SCIPY_AVAILABLE:
        # Thompson-Cox-Hastings pseudo-Voigt fallback
        f_g5 = max(1e-9, fwhm_g)**5
        f_l5 = max(1e-9, fwhm_l)**5
        fwhm_tot = (f_g5 + 2.69269*fwhm_g**4*fwhm_l + 2.42843*fwhm_g**3*fwhm_l**2 + 
                    4.47163*fwhm_g**2*fwhm_l**3 + 0.07842*fwhm_g*fwhm_l**4 + f_l5)**0.2
        eta_eff = np.clip(1.36603 * (fwhm_l / fwhm_tot) - 0.47719 * (fwhm_l / fwhm_tot)**2 + 0.11116 * (fwhm_l / fwhm_tot)**3, 0.0, 1.0)
        return pseudo_voigt(x, x0, fwhm_tot, eta_eff, height)
    
    sigma = max(1e-7, fwhm_g / (2.0 * np.sqrt(2.0 * np.log(2.0))))
    gamma = max(1e-7, fwhm_l / 2.0)
    z = ((x - x0) + 1j * gamma) / (sigma * np.sqrt(2.0))
    v = np.real(wofz(z)) / (sigma * np.sqrt(2.0 * np.pi))
    
    z0 = (1j * gamma) / (sigma * np.sqrt(2.0))
    v0 = np.real(wofz(z0)) / (sigma * np.sqrt(2.0 * np.pi))
    return height * (v / max(1e-9, v0))


def pearson_vii(x, x0, fwhm, m, height):
    """
    Pearson VII peak profile function.
    m = 1: Lorentzian, m -> infinity: Gaussian
    """
    if m <= 0.5:
        m = 0.51
    c = 2.0 * np.sqrt(2.0 ** (1.0 / m) - 1.0) / max(1e-6, fwhm)
    return height * (1.0 + (c * (x - x0)) ** 2) ** (-m)


def asymmetric_pseudo_voigt(x, x0, fwhm, eta, height, asym):
    """
    Split Asymmetric Pseudo-Voigt profile with left/right half-width modulation.
    asym > 1: tail extends toward higher angles (positive asymmetry)
    asym < 1: tail extends toward lower angles (negative asymmetry / axial divergence)
    """
    asym = max(0.2, min(5.0, asym))
    fwhm_l = 2.0 * fwhm / (1.0 + asym)
    fwhm_r = 2.0 * fwhm * asym / (1.0 + asym)
    
    y = np.zeros_like(x)
    left_mask = x < x0
    right_mask = ~left_mask
    
    y[left_mask] = pseudo_voigt(x[left_mask], x0, fwhm_l, eta, height)
    y[right_mask] = pseudo_voigt(x[right_mask], x0, fwhm_r, eta, height)
    return y


def ka1_ka2_doublet(x, x0, fwhm, eta, height, lambda1=0.154056, lambda2=0.154439, ratio=0.5):
    """
    K-alpha 1 & K-alpha 2 Laboratory X-ray Source Doublet.
    Calculates exact angular separation via Bragg's Law:
    sin(theta2) = (lambda2 / lambda1) * sin(theta1)
    """
    theta1_rad = np.radians(x0 / 2.0)
    sin_theta2 = (lambda2 / lambda1) * np.sin(theta1_rad)
    if sin_theta2 > 1.0:
        sin_theta2 = 1.0
    theta2_rad = np.arcsin(sin_theta2)
    x0_ka2 = np.degrees(theta2_rad) * 2.0
    
    y_ka1 = pseudo_voigt(x, x0, fwhm, eta, height)
    y_ka2 = pseudo_voigt(x, x0_ka2, fwhm * 1.05, eta, height * ratio)
    
    return y_ka1 + y_ka2, y_ka1, y_ka2, x0_ka2


def integrate_area(y_arr, x_arr):
    """Trapezoidal integration compatible with numpy versions."""
    if hasattr(np, 'trapezoid'):
        return float(np.trapezoid(y_arr, x_arr))
    elif hasattr(np, 'trapz'):
        return float(np.trapz(y_arr, x_arr))
    else:
        return float(np.sum(y_arr[:-1] + y_arr[1:]) * 0.5 * np.mean(np.diff(x_arr)))


def generate_jupyter_notebook_json(python_code: str, title="OriginPro_XRD_FWHM_Deconvolution") -> str:
    """Generates standard Jupyter Notebook (.ipynb) structure as JSON string."""
    notebook = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    f"# {title}\n",
                    "### Generated by **OriginPro & Matplotlib XRD Peak Studio**\n",
                    "This interactive notebook performs high-precision peak deconvolution, instrumental FWHM correction, and Scherrer / Williamson-Hall / De Keijser crystallite size extraction with academic publication formatting."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": python_code.splitlines(keepends=True)
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }
    return json.dumps(notebook, indent=2)


def generate_origin_fwhm_plot(params: dict) -> dict:
    """
    Generates an advanced, publication-grade OriginPro XRD Peak Fitting & FWHM Deconvolution plot.
    Supports multi-peak Levenberg-Marquardt non-linear least squares, secondary Q / d-spacing axes,
    journal-ready themes, and multi-format script/data export (OriginPro Python, LabTalk, Jupyter, CSV).
    """
    # 1. Primary Parameters
    center = float(params.get('center', 28.442))
    fwhm = float(params.get('fwhm', 0.285))
    profile_type = params.get('profileType', 'pseudo_voigt')
    eta = float(params.get('eta', 0.50))
    pearson_m = float(params.get('pearsonM', 2.0))
    asymmetry = float(params.get('asymmetry', 1.15))
    height = float(params.get('height', 1000.0))
    
    # Background params
    bg_const = float(params.get('bgConst', 60.0))
    bg_slope = float(params.get('bgSlope', 0.5))
    bg_quad = float(params.get('bgQuad', 0.0))
    bg_type = params.get('bgType', 'linear')  # 'constant', 'linear', 'quadratic', 'amorphous_halo'
    halo_center = float(params.get('haloCenter', 22.0))
    halo_fwhm = float(params.get('haloFwhm', 8.0))
    halo_height = float(params.get('haloHeight', 150.0))
    
    # Instrumental broadening & Radiation
    inst_fwhm = float(params.get('instFwhm', 0.085))
    wavelength = float(params.get('wavelength', 0.154056))  # nm (Cu Ka1)
    wavelength2 = float(params.get('wavelength2', 0.154439))  # nm (Cu Ka2)
    ka_ratio = float(params.get('kaRatio', 0.5))
    
    # Domain span & noise
    noise_pct = float(params.get('noisePct', 2.5))
    x_span = float(params.get('xSpan', 3.5))
    n_points = int(params.get('numPoints', 350))
    
    # Visual & Theme options
    theme = params.get('theme', 'origin_classic')
    top_axis = params.get('topAxis', 'none')  # 'none', 'q_space', 'd_spacing'
    show_residual = bool(params.get('showResidual', True))
    show_fwhm_bracket = bool(params.get('showFwhmBracket', True))
    show_table = bool(params.get('showTable', True))
    show_deconv_peaks = bool(params.get('showDeconvPeaks', True))
    show_legend = bool(params.get('showLegend', True))
    dpi = int(params.get('dpi', 220))
    
    # Sub-peaks for multi-peak mode
    peaks_data = params.get('deconvolutionPeaks', [])
    is_multi_peak_mode = bool(params.get('isMultiPeakMode', False)) or len(peaks_data) > 1
    
    # Experimental Data Fitting input
    raw_x = params.get('rawX', None)
    raw_y = params.get('rawY', None)
    is_auto_fit = bool(params.get('isAutoFit', False)) and (raw_x is not None and raw_y is not None)
    
    # 2. Construct or Load 2-Theta Grid
    if is_auto_fit and len(raw_x) > 5 and len(raw_y) > 5:
        x = np.array(raw_x, dtype=float)
        y_observed = np.array(raw_y, dtype=float)
        x_min = float(np.min(x))
        x_max = float(np.max(x))
        center_est = float(x[np.argmax(y_observed)])
    else:
        x_min = center - x_span / 2.0
        x_max = center + x_span / 2.0
        x = np.linspace(x_min, x_max, n_points)
        center_est = center

    # 3. Compute Baseline Function
    def compute_baseline(x_arr, b0, b1, b2=0.0):
        if bg_type == 'quadratic':
            base = b0 + b1 * (x_arr - center_est) + b2 * (x_arr - center_est) ** 2
        elif bg_type == 'constant':
            base = np.full_like(x_arr, b0)
        else:
            base = b0 + b1 * (x_arr - center_est)
        if bg_type == 'amorphous_halo':
            base += gaussian(x_arr, halo_center, halo_fwhm, halo_height)
        return base

    bg = compute_baseline(x, bg_const, bg_slope, bg_quad)
    
    # 4. Multi-Peak Least-Squares Optimization or Construction
    palette_colors = ['#2563EB', '#16A34A', '#9333EA', '#D97706', '#0891B2', '#E11D48', '#4F46E5', '#059669', '#DB2777', '#CA8A04']
    sub_curves = []
    ka2_info = None
    y_total_calc = np.copy(bg)
    fit_errors = {}

    # Determine if we should run Scipy Multi-Peak Fitting
    if is_auto_fit and SCIPY_AVAILABLE and is_multi_peak_mode and len(peaks_data) > 0:
        # Multi-peak simultaneous fitting
        n_sub = len(peaks_data)
        try:
            def multi_pv_model(x_arr, b0, b1, *p_peaks):
                res = b0 + b1 * (x_arr - center_est)
                for i in range(n_sub):
                    ci = p_peaks[i * 4]
                    fwi = p_peaks[i * 4 + 1]
                    hi = p_peaks[i * 4 + 2]
                    eti = p_peaks[i * 4 + 3]
                    res += pseudo_voigt(x_arr, ci, fwi, eti, hi)
                return res

            p0 = [np.min(y_observed), 0.0]
            lb = [0.0, -1000.0]
            ub = [np.max(y_observed), 1000.0]

            for pk in peaks_data:
                p0.extend([float(pk.get('center', center_est)), float(pk.get('fwhm', fwhm)), float(pk.get('height', height)), float(pk.get('eta', eta))])
                lb.extend([x_min, 0.02, 1.0, 0.0])
                ub.extend([x_max, x_span, np.max(y_observed) * 3.0, 1.0])

            popt, pcov = curve_fit(multi_pv_model, x, y_observed, p0=p0, bounds=(lb, ub), maxfev=6000)
            perr = np.sqrt(np.diag(pcov))

            bg_const = float(popt[0])
            bg_slope = float(popt[1])
            bg = compute_baseline(x, bg_const, bg_slope)
            y_total_calc = np.copy(bg)

            for i, pk in enumerate(peaks_data):
                ci = float(popt[2 + i * 4])
                fwi = float(popt[2 + i * 4 + 1])
                hi = float(popt[2 + i * 4 + 2])
                eti = float(popt[2 + i * 4 + 3])
                
                c_err = float(perr[2 + i * 4]) if not np.isinf(perr[2 + i * 4]) else 0.001
                fw_err = float(perr[2 + i * 4 + 1]) if not np.isinf(perr[2 + i * 4 + 1]) else 0.001
                h_err = float(perr[2 + i * 4 + 2]) if not np.isinf(perr[2 + i * 4 + 2]) else 1.0
                eta_err = float(perr[2 + i * 4 + 3]) if not np.isinf(perr[2 + i * 4 + 3]) else 0.01

                y_pk = pseudo_voigt(x, ci, fwi, eti, hi)
                y_total_calc += y_pk

                sub_curves.append({
                    'id': str(i + 1),
                    'label': pk.get('label', f'Phase #{i+1}'),
                    'center': ci,
                    'center_err': c_err,
                    'fwhm': fwi,
                    'fwhm_err': fw_err,
                    'height': hi,
                    'height_err': h_err,
                    'eta': eti,
                    'eta_err': eta_err,
                    'y': y_pk + bg,
                    'y_pure': y_pk,
                    'color': pk.get('color', palette_colors[i % len(palette_colors)])
                })
        except Exception:
            # Fallback if multi-peak fit encounters singularity
            for i, pk in enumerate(peaks_data):
                ci = float(pk.get('center', center))
                fwi = float(pk.get('fwhm', fwhm))
                hi = float(pk.get('height', height))
                eti = float(pk.get('eta', eta))
                y_pk = pseudo_voigt(x, ci, fwi, eti, hi)
                y_total_calc += y_pk
                sub_curves.append({
                    'id': str(i + 1),
                    'label': pk.get('label', f'Phase #{i+1}'),
                    'center': ci,
                    'fwhm': fwi,
                    'height': hi,
                    'eta': eti,
                    'y': y_pk + bg,
                    'y_pure': y_pk,
                    'color': pk.get('color', palette_colors[i % len(palette_colors)])
                })
    elif is_auto_fit and SCIPY_AVAILABLE:
        # Single peak Levenberg-Marquardt fitting
        try:
            def fit_single_pv(x_arr, c0, fw, h, et, b0, b1):
                return b0 + b1 * (x_arr - c0) + pseudo_voigt(x_arr, c0, fw, et, h)

            p0 = [center_est, max(0.08, fwhm), np.max(y_observed) - np.min(y_observed), eta, np.min(y_observed), 0.0]
            bounds = (
                [x_min, 0.02, 1.0, 0.0, 0.0, -1000.0],
                [x_max, x_span, np.max(y_observed) * 3.0, 1.0, np.max(y_observed), 1000.0]
            )
            popt, pcov = curve_fit(fit_single_pv, x, y_observed, p0=p0, bounds=bounds, maxfev=4000)
            perr = np.sqrt(np.diag(pcov))

            center = float(popt[0])
            fwhm = float(popt[1])
            height = float(popt[2])
            eta = float(popt[3])
            bg_const = float(popt[4])
            bg_slope = float(popt[5])
            bg = compute_baseline(x, bg_const, bg_slope)

            y_pk = pseudo_voigt(x, center, fwhm, eta, height)
            y_total_calc = bg + y_pk

            fit_errors = {
                'center_err': float(perr[0]),
                'fwhm_err': float(perr[1]),
                'height_err': float(perr[2]),
                'eta_err': float(perr[3])
            }

            sub_curves.append({
                'id': '1',
                'label': 'Fitted Pseudo-Voigt Peak',
                'center': center,
                'center_err': fit_errors['center_err'],
                'fwhm': fwhm,
                'fwhm_err': fit_errors['fwhm_err'],
                'height': height,
                'height_err': fit_errors['height_err'],
                'eta': eta,
                'eta_err': fit_errors['eta_err'],
                'y': y_total_calc,
                'y_pure': y_pk,
                'color': '#2563EB'
            })
        except Exception:
            y_pk = pseudo_voigt(x, center, fwhm, eta, height)
            y_total_calc = bg + y_pk
            sub_curves.append({
                'id': '1',
                'label': 'Peak 1',
                'center': center,
                'fwhm': fwhm,
                'height': height,
                'eta': eta,
                'y': y_total_calc,
                'y_pure': y_pk,
                'color': '#2563EB'
            })
    elif is_multi_peak_mode and len(peaks_data) > 0:
        # Multi-peak manual synthesis
        for i, pk in enumerate(peaks_data):
            p_center = float(pk.get('center', center))
            p_fwhm = float(pk.get('fwhm', fwhm))
            p_height = float(pk.get('height', height))
            p_eta = float(pk.get('eta', eta))
            p_type = pk.get('profileType', profile_type)
            p_label = pk.get('label', f'Phase #{i+1}')
            p_color = pk.get('color', palette_colors[i % len(palette_colors)])

            if p_type == 'gaussian':
                y_p = gaussian(x, p_center, p_fwhm, p_height)
            elif p_type == 'lorentzian':
                y_p = lorentzian(x, p_center, p_fwhm, p_height)
            elif p_type == 'pearson7':
                y_p = pearson_vii(x, p_center, p_fwhm, pearson_m, p_height)
            elif p_type == 'asymmetric':
                y_p = asymmetric_pseudo_voigt(x, p_center, p_fwhm, p_eta, p_height, asymmetry)
            else:
                y_p = pseudo_voigt(x, p_center, p_fwhm, p_eta, p_height)

            y_total_calc += y_p
            sub_curves.append({
                'id': str(i + 1),
                'label': p_label,
                'center': p_center,
                'fwhm': p_fwhm,
                'height': p_height,
                'eta': p_eta,
                'y': y_p + bg,
                'y_pure': y_p,
                'color': p_color
            })
    else:
        # Single peak standard models
        if profile_type == 'gaussian':
            y_pk = gaussian(x, center, fwhm, height)
            y_total_calc += y_pk
            sub_curves.append({'id': '1', 'label': 'Gaussian Peak', 'center': center, 'fwhm': fwhm, 'height': height, 'eta': 0.0, 'y': y_pk + bg, 'y_pure': y_pk, 'color': '#2563EB'})
        elif profile_type == 'lorentzian':
            y_pk = lorentzian(x, center, fwhm, height)
            y_total_calc += y_pk
            sub_curves.append({'id': '1', 'label': 'Lorentzian Peak', 'center': center, 'fwhm': fwhm, 'height': height, 'eta': 1.0, 'y': y_pk + bg, 'y_pure': y_pk, 'color': '#2563EB'})
        elif profile_type == 'true_voigt':
            fwhm_g = max(0.01, inst_fwhm)
            fwhm_l = max(0.01, np.sqrt(max(1e-6, fwhm**2 - inst_fwhm**2)))
            y_pk = true_voigt(x, center, fwhm_g, fwhm_l, height)
            y_total_calc += y_pk
            sub_curves.append({'id': '1', 'label': f'True Voigt (βG={fwhm_g:.3f}°, βL={fwhm_l:.3f}°)', 'center': center, 'fwhm': fwhm, 'height': height, 'eta': eta, 'y': y_pk + bg, 'y_pure': y_pk, 'color': '#2563EB'})
        elif profile_type == 'pearson7':
            y_pk = pearson_vii(x, center, fwhm, pearson_m, height)
            y_total_calc += y_pk
            sub_curves.append({'id': '1', 'label': f'Pearson VII (m={pearson_m:.1f})', 'center': center, 'fwhm': fwhm, 'height': height, 'eta': eta, 'y': y_pk + bg, 'y_pure': y_pk, 'color': '#2563EB'})
        elif profile_type == 'asymmetric':
            y_pk = asymmetric_pseudo_voigt(x, center, fwhm, eta, height, asymmetry)
            y_total_calc += y_pk
            sub_curves.append({'id': '1', 'label': f'Asym Pseudo-Voigt (Asym={asymmetry:.2f})', 'center': center, 'fwhm': fwhm, 'height': height, 'eta': eta, 'y': y_pk + bg, 'y_pure': y_pk, 'color': '#2563EB'})
        elif profile_type == 'ka_doublet':
            y_doublet, y_ka1, y_ka2, x0_ka2 = ka1_ka2_doublet(x, center, fwhm, eta, height, wavelength, wavelength2, ka_ratio)
            y_total_calc += y_doublet
            ka2_info = {'x0_ka1': center, 'x0_ka2': x0_ka2, 'separation': x0_ka2 - center}
            sub_curves.append({'id': '1', 'label': f'Kα₁ (λ={wavelength*10:.4f} Å)', 'center': center, 'fwhm': fwhm, 'height': height, 'eta': eta, 'y': y_ka1 + bg, 'y_pure': y_ka1, 'color': '#2563EB'})
            sub_curves.append({'id': '2', 'label': f'Kα₂ (λ={wavelength2*10:.4f} Å, I={ka_ratio:.2f})', 'center': x0_ka2, 'fwhm': fwhm * 1.05, 'height': height * ka_ratio, 'eta': eta, 'y': y_ka2 + bg, 'y_pure': y_ka2, 'color': '#16A34A'})
        else:
            y_pk = pseudo_voigt(x, center, fwhm, eta, height)
            y_total_calc += y_pk
            sub_curves.append({'id': '1', 'label': f'Pseudo-Voigt (η={eta:.2f})', 'center': center, 'fwhm': fwhm, 'height': height, 'eta': eta, 'y': y_pk + bg, 'y_pure': y_pk, 'color': '#2563EB'})

    # 5. Generate Observed Scatter Points if not provided experimentally
    if not is_auto_fit:
        np.random.seed(42)
        noise_sigma = float(max(1.0, height * (noise_pct / 100.0)))
        noise = np.random.normal(0, noise_sigma, len(x))
        y_observed = y_total_calc + noise
    else:
        noise_sigma = float(max(0.5, np.std(y_observed - y_total_calc)))

    # 6. Residual & Metrology Calculations
    residual = y_observed - y_total_calc
    ss_res = np.sum(residual ** 2)
    ss_tot = np.sum((y_observed - np.mean(y_observed)) ** 2)
    r_squared = float(np.clip(1.0 - (ss_res / ss_tot) if ss_tot > 0 else 0.9999, 0.0, 0.99999))
    
    weights = 1.0 / np.maximum(1.0, y_observed)
    r_wp = float(np.sqrt(np.sum(weights * (residual ** 2)) / np.maximum(1e-6, np.sum(weights * (y_observed ** 2)))) * 100.0)
    r_p = float((np.sum(np.abs(residual)) / np.maximum(1e-6, np.sum(y_observed))) * 100.0)
    
    dof = max(1, len(x) - (len(sub_curves) * 4 + 2))
    reduced_chi_sq = float((ss_res / (max(1e-6, noise_sigma) ** 2)) / dof)
    gof = float(np.sqrt(max(0.01, reduced_chi_sq)))
    
    # Durbin-Watson statistic for serial correlation
    diff_res = np.diff(residual)
    durbin_watson = float(np.sum(diff_res ** 2) / max(1e-6, ss_res))

    # 7. Physical Deconvolved FWHM & Microstructure (De Keijser & Scherrer)
    if fwhm > inst_fwhm:
        beta_phys_gauss = np.sqrt(fwhm ** 2 - inst_fwhm ** 2)
        beta_phys_lorentz = fwhm - inst_fwhm
        beta_phys = (1.0 - eta) * beta_phys_gauss + eta * beta_phys_lorentz
    else:
        beta_phys = fwhm * 0.15
        
    theta_rad = np.radians(center / 2.0)
    beta_rad = np.radians(beta_phys)
    crystallite_size_nm = float((0.94 * wavelength) / (beta_rad * np.cos(theta_rad))) if beta_rad > 0 else 0.0
    microstrain_pct = float((np.radians(max(0.001, (1.0 - eta) * beta_phys)) / (4.0 * np.tan(max(1e-4, theta_rad)))) * 100.0)

    # Calculate Sub-Peak Areas, Crystallite Size, and Strain per peak
    total_area = integrate_area(y_total_calc - bg, x)
    sub_peaks_metrics = []
    for sc in sub_curves:
        area_i = integrate_area(sc['y_pure'], x)
        sc_center = sc['center']
        sc_fwhm = sc['fwhm']
        sc_eta = sc.get('eta', eta)
        
        # Per-peak size and strain
        if sc_fwhm > inst_fwhm:
            bp_g = np.sqrt(sc_fwhm**2 - inst_fwhm**2)
            bp_l = sc_fwhm - inst_fwhm
            bp_i = (1.0 - sc_eta) * bp_g + sc_eta * bp_l
        else:
            bp_i = sc_fwhm * 0.15
        
        th_rad_i = np.radians(sc_center / 2.0)
        c_size_i = float((0.94 * wavelength) / (np.radians(bp_i) * np.cos(th_rad_i))) if bp_i > 0 else 0.0
        m_strain_i = float((np.radians(max(0.001, (1.0 - sc_eta) * bp_i)) / (4.0 * np.tan(max(1e-4, th_rad_i)))) * 100.0)

        sub_peaks_metrics.append({
            'id': sc.get('id', '1'),
            'label': sc['label'],
            'center': sc_center,
            'center_err': sc.get('center_err', 0.0),
            'fwhm': sc_fwhm,
            'fwhm_err': sc.get('fwhm_err', 0.0),
            'height': sc['height'],
            'height_err': sc.get('height_err', 0.0),
            'eta': sc_eta,
            'eta_err': sc.get('eta_err', 0.0),
            'area': area_i,
            'area_fraction': float(area_i / max(1e-6, total_area)) * 100.0,
            'crystallite_size_nm': c_size_i,
            'microstrain_pct': m_strain_i,
            'color': sc['color']
        })

    # 8. Theme Configurations for Academic Publishing
    theme_cfg = {
        'origin_classic': {
            'bg_fig': '#FFFFFF',
            'bg_ax': '#FFFFFF',
            'text_color': '#000000',
            'spine_color': '#000000',
            'spine_width': 1.4,
            'obs_marker': 'o',
            'obs_color': '#1E293B',
            'obs_face': 'none',
            'fit_color': '#DC2626',
            'bg_color': '#64748B',
            'res_color': '#0284C7',
            'grid': True,
            'grid_color': '#E2E8F0',
            'grid_ls': ':',
            'font_family': 'sans-serif',
            'badge': 'OriginPro 2024 Classic'
        },
        'nature': {
            'bg_fig': '#FFFFFF',
            'bg_ax': '#FFFFFF',
            'text_color': '#111827',
            'spine_color': '#1F2937',
            'spine_width': 1.2,
            'obs_marker': 's',
            'obs_color': '#111827',
            'obs_face': '#E5E7EB',
            'fit_color': '#991B1B',
            'bg_color': '#9CA3AF',
            'res_color': '#374151',
            'grid': False,
            'grid_color': '#F3F4F6',
            'grid_ls': '-',
            'font_family': 'sans-serif',
            'badge': 'Nature / Springer Nature'
        },
        'acs_nano': {
            'bg_fig': '#FAFAFA',
            'bg_ax': '#FAFAFA',
            'text_color': '#0F172A',
            'spine_color': '#0F172A',
            'spine_width': 1.5,
            'obs_marker': 'o',
            'obs_color': '#0F172A',
            'obs_face': '#E2E8F0',
            'fit_color': '#EA580C',
            'bg_color': '#64748B',
            'res_color': '#0284C7',
            'grid': True,
            'grid_color': '#E2E8F0',
            'grid_ls': '--',
            'font_family': 'sans-serif',
            'badge': 'ACS Nano / JACS'
        },
        'elsevier': {
            'bg_fig': '#FFFFFF',
            'bg_ax': '#FFFFFF',
            'text_color': '#000000',
            'spine_color': '#000000',
            'spine_width': 1.6,
            'obs_marker': '^',
            'obs_color': '#000000',
            'obs_face': 'none',
            'fit_color': '#2563EB',
            'bg_color': '#4B5563',
            'res_color': '#059669',
            'grid': True,
            'grid_color': '#D1D5DB',
            'grid_ls': ':',
            'font_family': 'sans-serif',
            'badge': 'Elsevier / Acta Materialia'
        },
        'wiley': {
            'bg_fig': '#FFFFFF',
            'bg_ax': '#FFFFFF',
            'text_color': '#1E293B',
            'spine_color': '#334155',
            'spine_width': 1.5,
            'obs_marker': 'D',
            'obs_color': '#0F172A',
            'obs_face': '#F1F5F9',
            'fit_color': '#D97706',
            'bg_color': '#64748B',
            'res_color': '#0284C7',
            'grid': True,
            'grid_color': '#E2E8F0',
            'grid_ls': ':',
            'font_family': 'sans-serif',
            'badge': 'Wiley / Adv. Energy Mater.'
        },
        'dark_lab': {
            'bg_fig': '#0B0F19',
            'bg_ax': '#070A12',
            'text_color': '#F8FAFC',
            'spine_color': '#334155',
            'spine_width': 1.3,
            'obs_marker': 'o',
            'obs_color': '#94A3B8',
            'obs_face': 'none',
            'fit_color': '#38BDF8',
            'bg_color': '#64748B',
            'res_color': '#C084FC',
            'grid': True,
            'grid_color': '#1E293B',
            'grid_ls': ':',
            'font_family': 'sans-serif',
            'badge': 'Darkroom Scientific Lab'
        }
    }
    
    cfg = theme_cfg.get(theme, theme_cfg['origin_classic'])

    # 9. Matplotlib Canvas & Grid Setup
    plt.rcParams['font.family'] = cfg['font_family']
    plt.rcParams['mathtext.fontset'] = 'cm'
    
    if show_residual:
        fig, (ax1, ax2) = plt.subplots(
            2, 1, 
            figsize=(9.2, 7.2), 
            dpi=dpi, 
            gridspec_kw={'height_ratios': [3.6, 1.0], 'hspace': 0.04}, 
            sharex=True
        )
    else:
        fig, ax1 = plt.subplots(figsize=(9.2, 5.6), dpi=dpi)
        ax2 = None

    fig.patch.set_facecolor(cfg['bg_fig'])
    ax1.set_facecolor(cfg['bg_ax'])
    if ax2:
        ax2.set_facecolor(cfg['bg_ax'])

    # 10. Inward Ticks & Double-Box Spines
    for ax in ([ax1, ax2] if ax2 else [ax1]):
        ax.tick_params(
            direction='in', 
            which='both', 
            top=True, 
            right=True, 
            colors=cfg['text_color'],
            length=6.5, 
            width=cfg['spine_width']
        )
        ax.tick_params(which='minor', length=3.5, width=cfg['spine_width'] * 0.8)
        ax.minorticks_on()
        for spine in ax.spines.values():
            spine.set_edgecolor(cfg['spine_color'])
            spine.set_linewidth(cfg['spine_width'])
        if cfg['grid']:
            ax.grid(True, which='major', color=cfg['grid_color'], linestyle=cfg['grid_ls'], alpha=0.7)

    # 11. Plot Observed Scatter Points
    step = max(1, len(x) // 140)
    ax1.scatter(
        x[::step], 
        y_observed[::step], 
        s=26, 
        marker=cfg['obs_marker'],
        facecolors=cfg['obs_face'], 
        edgecolors=cfg['obs_color'], 
        linewidths=1.25, 
        label=r'Observed ($I_{\mathrm{obs}}$)',
        zorder=3
    )

    # 12. Plot Deconvoluted Sub-Peaks with subtle shading
    if show_deconv_peaks and len(sub_curves) > 1:
        for idx, sub in enumerate(sub_curves):
            ax1.plot(
                x, 
                sub['y'], 
                linestyle='--', 
                linewidth=1.75, 
                color=sub['color'],
                label=f"{sub['label']}",
                zorder=4
            )
            ax1.fill_between(x, bg, sub['y'], color=sub['color'], alpha=0.12, zorder=2)

    # 13. Plot Baseline
    ax1.plot(
        x, 
        bg, 
        linestyle=':', 
        linewidth=1.4, 
        color=cfg['bg_color'], 
        label=r'Baseline ($y_0$)',
        zorder=2
    )

    # 14. Plot Total Calculated Profile Curve
    ax1.plot(
        x, 
        y_total_calc, 
        color=cfg['fit_color'], 
        linewidth=2.3, 
        label=r'Origin Fit ($I_{\mathrm{calc}}$)',
        zorder=5
    )

    # 15. OriginPro FWHM Dimension Caliper Annotation & Drop-line
    if show_fwhm_bracket and len(sub_curves) == 1:
        half_max_y = bg_const + height / 2.0
        x_left = center - fwhm / 2.0
        x_right = center + fwhm / 2.0
        
        arrow_color = cfg['fit_color'] if theme != 'dark_lab' else '#38BDF8'
        ax1.annotate(
            '', 
            xy=(x_left, half_max_y), 
            xytext=(x_right, half_max_y),
            arrowprops=dict(arrowstyle='<->', color=arrow_color, lw=1.6, mutation_scale=15),
            zorder=6
        )
        
        ax1.vlines(
            x=center, 
            ymin=bg_const, 
            ymax=bg_const + height, 
            colors=arrow_color, 
            linestyles='-.', 
            linewidth=1.3,
            zorder=6
        )

        label_y = half_max_y + height * 0.09
        ax1.text(
            center, 
            label_y, 
            rf'$\mathbf{{FWHM}} = {fwhm:.4f}^\circ$' + '\n' +
            rf'$\beta_{{\mathrm{{phys}}}} = {beta_phys:.4f}^\circ$',
            fontsize=9.5, 
            ha='center', 
            va='bottom',
            color=cfg['text_color'],
            bbox=dict(boxstyle='round,pad=0.35', facecolor=cfg['bg_fig'], edgecolor=arrow_color, alpha=0.92, lw=1.1),
            zorder=7
        )

    # 16. Ka1 / Ka2 Doublet Annotations
    if ka2_info:
        ax1.axvline(x=ka2_info['x0_ka1'], color='#2563EB', linestyle=':', alpha=0.6, lw=1.0)
        ax1.axvline(x=ka2_info['x0_ka2'], color='#16A34A', linestyle=':', alpha=0.6, lw=1.0)
        ax1.text(
            ka2_info['x0_ka2'], 
            bg_const + height * ka_ratio * 1.05, 
            rf'$\mathrm{{K\alpha_2}}\ (+{ka2_info["separation"]:.3f}^\circ)$', 
            fontsize=8.5, 
            color='#16A34A', 
            ha='left', 
            va='bottom',
            fontweight='bold'
        )

    # 17. OriginPro Analytical Inset Table
    if show_table:
        table_lines = [
            r"$\mathbf{OriginPro\ Peak\ Analytics}$",
            "────────────────────────",
            rf"Model: {profile_type.replace('_', ' ').title()}",
            rf"$2\theta_0 = {center:.4f}^\circ$",
            rf"$\mathrm{{FWHM}}\ (\beta_{{\mathrm{{obs}}}}) = {fwhm:.4f}^\circ$",
            rf"$\beta_{{\mathrm{{inst}}}} = {inst_fwhm:.4f}^\circ$",
            rf"$\beta_{{\mathrm{{phys}}}} = {beta_phys:.4f}^\circ$",
            rf"$D_{{\mathrm{{size}}}} = {crystallite_size_nm:.1f}\ \mathrm{{nm}}$",
            rf"$\varepsilon_{{\mathrm{{strain}}}} = {microstrain_pct:.3f}\ \%$",
            rf"$R^2 = {r_squared:.5f}$ | $R_{{wp}} = {r_wp:.2f}\%$",
            rf"$\mathrm{{GoF}} = {gof:.2f}$"
        ]
        table_text = "\n".join(table_lines)
        
        ax1.text(
            0.03, 0.96, 
            table_text, 
            transform=ax1.transAxes, 
            fontsize=8.5, 
            va='top', 
            ha='left',
            color=cfg['text_color'],
            bbox=dict(
                boxstyle='square,pad=0.5', 
                facecolor=cfg['bg_ax'], 
                edgecolor=cfg['spine_color'], 
                alpha=0.90, 
                lw=1.1
            ),
            zorder=7
        )

    # Labels and Legend for Ax1
    ax1.set_ylabel(r'Diffraction Intensity $I$ (counts)', fontsize=11, fontweight='bold', color=cfg['text_color'])
    if show_legend:
        ax1.legend(loc='upper right', frameon=True, framealpha=0.88, facecolor=cfg['bg_ax'], edgecolor=cfg['spine_color'], fontsize=8.5)
    
    y_top = max(np.max(y_observed), np.max(y_total_calc)) * 1.25
    ax1.set_ylim(bottom=max(0, bg_const - height * 0.15), top=y_top)

    # 18. Secondary Top Axis (Q-space or d-spacing)
    lam_angstrom = wavelength * 10.0
    if top_axis == 'q_space':
        try:
            def tth_to_q(tth):
                return (4.0 * np.pi / lam_angstrom) * np.sin(np.radians(np.maximum(0.1, tth) / 2.0))

            def q_to_tth(q):
                val = (q * lam_angstrom) / (4.0 * np.pi)
                return 2.0 * np.degrees(np.arcsin(np.clip(val, -1.0, 1.0)))

            secax = ax1.secondary_xaxis('top', functions=(tth_to_q, q_to_tth))
            secax.set_xlabel(r'Scattering Wavevector $Q\ (\mathrm{\AA}^{-1})$', fontsize=10, fontweight='bold', color=cfg['text_color'])
            secax.tick_params(direction='in', which='both', colors=cfg['text_color'])
        except Exception:
            pass
    elif top_axis == 'd_spacing':
        try:
            def tth_to_d(tth):
                return lam_angstrom / (2.0 * np.sin(np.radians(np.maximum(0.5, tth) / 2.0)))

            def d_to_tth(d):
                val = lam_angstrom / (2.0 * np.maximum(0.1, d))
                return 2.0 * np.degrees(np.arcsin(np.clip(val, -1.0, 1.0)))

            secax = ax1.secondary_xaxis('top', functions=(tth_to_d, d_to_tth))
            secax.set_xlabel(r'Interplanar Spacing $d\ (\mathrm{\AA})$', fontsize=10, fontweight='bold', color=cfg['text_color'])
            secax.tick_params(direction='in', which='both', colors=cfg['text_color'])
        except Exception:
            pass

    # 19. Residual Subplot
    if ax2:
        ax2.scatter(
            x[::step], 
            residual[::step], 
            s=18, 
            color=cfg['res_color'], 
            alpha=0.85,
            zorder=3
        )
        ax2.axhline(0, color=cfg['spine_color'], linestyle='-', linewidth=1.0, zorder=2)
        ax2.axhline(2 * noise_sigma, color='gray', linestyle=':', linewidth=0.8, alpha=0.7)
        ax2.axhline(-2 * noise_sigma, color='gray', linestyle=':', linewidth=0.8, alpha=0.7)
        ax2.axhspan(-2 * noise_sigma, 2 * noise_sigma, color='gray', alpha=0.08)
        
        ax2.set_xlabel(r'Diffraction Angle $2\theta$ (degrees)', fontsize=11, fontweight='bold', color=cfg['text_color'])
        ax2.set_ylabel(r'$\Delta I$', fontsize=10, fontweight='bold', color=cfg['text_color'])
        
        max_res = max(abs(float(np.min(residual))), abs(float(np.max(residual)))) * 1.35
        if max_res == 0:
            max_res = 1.0
        ax2.set_ylim(-max_res, max_res)
    else:
        ax1.set_xlabel(r'Diffraction Angle $2\theta$ (degrees)', fontsize=11, fontweight='bold', color=cfg['text_color'])

    # 20. Export High-Res PNG and Vector SVG
    buf_png = io.BytesIO()
    plt.savefig(
        buf_png, 
        format='png', 
        dpi=dpi, 
        bbox_inches='tight', 
        facecolor=fig.get_facecolor(), 
        edgecolor='none'
    )
    buf_png.seek(0)
    base64_image = base64.b64encode(buf_png.read()).decode('utf-8')

    buf_svg = io.StringIO()
    plt.savefig(
        buf_svg,
        format='svg',
        bbox_inches='tight',
        facecolor=fig.get_facecolor(),
        edgecolor='none'
    )
    svg_content = buf_svg.getvalue()
    plt.close(fig)

    # 21. Generate Clean CSV / ASCII Data Export
    csv_header = [
        f"# OriginPro & Matplotlib XRD Peak Studio Export",
        f"# Center: {center:.4f} deg | Observed FWHM: {fwhm:.4f} deg | Inst FWHM: {inst_fwhm:.4f} deg",
        f"# Wavelength: {wavelength:.6f} nm ({lam_angstrom:.4f} Angstroms) | Scherrer Size: {crystallite_size_nm:.2f} nm",
        f"# Fit Quality: R^2 = {r_squared:.5f} | R_wp = {r_wp:.2f}% | GoF = {gof:.2f}"
    ]
    col_names = ["2Theta_deg", "Intensity_Obs", "Intensity_Calc", "Baseline", "Residual"]
    for sc in sub_curves:
        safe_label = sc['label'].replace(' ', '_').replace('(', '').replace(')', '').replace('/', '_')
        col_names.append(f"{safe_label}")
        
    csv_lines = [", ".join(csv_header[:2]), ", ".join(csv_header[2:]), ", ".join(col_names)]
    for i in range(len(x)):
        row = [f"{x[i]:.4f}", f"{y_observed[i]:.2f}", f"{y_total_calc[i]:.2f}", f"{bg[i]:.2f}", f"{residual[i]:.2f}"]
        for sc in sub_curves:
            row.append(f"{sc['y_pure'][i]:.2f}")
        csv_lines.append(", ".join(row))
    csv_data = "\n".join(csv_lines)

    # 22. Generate Standalone Python Code for Matplotlib
    python_code = f"""# ==============================================================================
# OriginPro / Python Publication XRD Peak Fitting & FWHM Deconvolution
# Generated by XRD Scientific Intelligence Suite (OriginPro Matplotlib Studio)
# Compatible with OriginLab Python, Jupyter Notebook, and Matplotlib
# ==============================================================================
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

def pseudo_voigt(x, x0, fwhm, eta, height):
    \"\"\"Pseudo-Voigt peak profile: linear combination of Gaussian & Lorentzian.\"\"\"
    eta = np.clip(eta, 0.0, 1.0)
    sigma = fwhm / (2.0 * np.sqrt(2.0 * np.log(2.0)))
    gamma = fwhm / 2.0
    G = np.exp(-0.5 * ((x - x0) / sigma) ** 2)
    L = 1.0 / (1.0 + ((x - x0) / gamma) ** 2)
    return height * ((1.0 - eta) * G + eta * L)

# --- Peak & Instrument Parameters ---
center = {center:.4f}         # 2-theta peak center (deg)
fwhm = {fwhm:.4f}           # Observed FWHM beta_obs (deg)
inst_fwhm = {inst_fwhm:.4f}      # Instrumental broadening beta_inst (deg)
eta = {eta:.3f}              # Lorentzian fraction (0=Gauss, 1=Lorentz)
height = {height:.1f}        # Net peak height (counts)
bg_const = {bg_const:.1f}       # Baseline offset
bg_slope = {bg_slope:.3f}       # Baseline linear slope
wavelength = {wavelength}     # Cu K-alpha 1 wavelength (nm)

# --- Grid Definition ---
x = np.linspace({x_min:.3f}, {x_max:.3f}, {n_points})
bg = bg_const + bg_slope * (x - center)
y_calc = bg + pseudo_voigt(x, center, fwhm, eta, height)

# --- Physical Deconvolution & Crystallite Size ---
if fwhm > inst_fwhm:
    beta_phys = (1.0 - eta) * np.sqrt(fwhm**2 - inst_fwhm**2) + eta * (fwhm - inst_fwhm)
else:
    beta_phys = fwhm * 0.15

theta_rad = np.radians(center / 2.0)
d_scherrer = (0.94 * wavelength) / (np.radians(beta_phys) * np.cos(theta_rad))
microstrain = (np.radians(max(0.001, (1.0 - eta) * beta_phys)) / (4.0 * np.tan(theta_rad))) * 100.0

print("--- OriginPro Peak Metrology ---")
print(f"Center 2-Theta  : {{center:.4f}} deg")
print(f"Observed FWHM   : {{fwhm:.4f}} deg")
print(f"Physical Beta   : {{beta_phys:.4f}} deg")
print(f"Crystallite Size: {{d_scherrer:.2f}} nm")
print(f"Microstrain     : {{microstrain:.4f}} %")

# --- Publication Figure Setup ---
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(8.5, 6.5), dpi=300, 
                               gridspec_kw={{'height_ratios': [3.5, 1.0], 'hspace': 0.04}}, sharex=True)

for ax in [ax1, ax2]:
    ax.tick_params(direction='in', which='both', top=True, right=True, length=6, width=1.3)
    ax.tick_params(which='minor', length=3, width=0.8)
    ax.minorticks_on()
    for spine in ax.spines.values():
        spine.set_linewidth(1.3)

# Main Plot
ax1.plot(x, y_calc, color='#DC2626', lw=2.0, label='OriginPro Pseudo-Voigt Fit')
ax1.plot(x, bg, color='#64748B', ls=':', lw=1.3, label='Baseline')
ax1.set_ylabel(r'Intensity $I$ (counts)', fontsize=11, fontweight='bold')
ax1.legend(loc='upper right', frameon=True)

# FWHM Dimension Caliper
ax1.annotate('', xy=(center - fwhm/2, bg_const + height/2), xytext=(center + fwhm/2, bg_const + height/2),
             arrowprops=dict(arrowstyle='<->', color='#DC2626', lw=1.5))
ax1.text(center, bg_const + height/2 + height*0.08, f'FWHM = {{fwhm:.3f}}°\\nSize = {{d_scherrer:.1f}} nm', 
         ha='center', fontsize=9, bbox=dict(boxstyle='round,pad=0.3', facecolor='white', edgecolor='#DC2626'))

# Residual Subplot
ax2.axhline(0, color='black', lw=1)
ax2.set_xlabel(r'Diffraction Angle $2\\theta$ (degrees)', fontsize=11, fontweight='bold')
ax2.set_ylabel(r'$\\Delta I$', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.show()
"""

    # 23. Generate Native OriginPro Python Script (`import originpro as op`)
    originpro_code = f"""# ==============================================================================
# OriginPro Native Python Script (originpro API)
# Generates native multi-column worksheet and graph window in OriginLab 2021+
# Instructions: In OriginPro, press Alt+5 to open Python Console, paste & run.
# ==============================================================================
import numpy as np
import originpro as op
import sys

def pseudo_voigt(x, x0, fwhm, eta, height):
    eta = np.clip(eta, 0.0, 1.0)
    sigma = fwhm / (2.0 * np.sqrt(2.0 * np.log(2.0)))
    gamma = fwhm / 2.0
    G = np.exp(-0.5 * ((x - x0) / sigma) ** 2)
    L = 1.0 / (1.0 + ((x - x0) / gamma) ** 2)
    return height * ((1.0 - eta) * G + eta * L)

center = {center:.4f}
fwhm = {fwhm:.4f}
eta = {eta:.3f}
height = {height:.1f}
bg_const = {bg_const:.1f}
bg_slope = {bg_slope:.3f}

# Check OriginPro Ext access
if op and op.oext:
    op.set_show(True)
else:
    print("This script is designed to run directly inside OriginPro Python Console (Alt+5).")

# Generate Data Arrays
x = np.linspace({x_min:.3f}, {x_max:.3f}, {n_points})
bg = bg_const + bg_slope * (x - center)
y_calc = bg + pseudo_voigt(x, center, fwhm, eta, height)
noise = np.random.normal(0, {noise_sigma:.2f}, len(x))
y_obs = y_calc + noise
residual = y_obs - y_calc

# Create OriginPro Workbook & Worksheet
wks = op.new_sheet('w', 'XRD_Deconv_Studio')
wks.set_labels(['2Theta', 'Intensity_Obs', 'Intensity_Calc', 'Baseline', 'Residual'])
wks.from_list(0, x.tolist(), 'X', units='deg', comments='Diffraction Angle')
wks.from_list(1, y_obs.tolist(), 'Y', units='counts', comments='Observed Data')
wks.from_list(2, y_calc.tolist(), 'Y', units='counts', comments='OriginPro Fit')
wks.from_list(3, bg.tolist(), 'Y', units='counts', comments='Background Baseline')
wks.from_list(4, residual.tolist(), 'Y', units='counts', comments='Fit Residual')

# Create Publication Double-Layer Graph
gp = op.new_graph(template='Origin')
gl = gp[0]

# Add Plots to Layer 1
plot_obs = gl.add_plot(wks, coly=1, colx=0, type='scatter')
plot_fit = gl.add_plot(wks, coly=2, colx=0, type='line')
plot_bg  = gl.add_plot(wks, coly=3, colx=0, type='line')

# Format Layer 1
gl.set_xlim({x_min:.3f}, {x_max:.3f}, 0.5)
gl.xaxis.title = r'Diffraction Angle 2\\theta (\\+(o))'
gl.yaxis.title = 'Intensity I (counts)'
gl.rescale()

print("Successfully exported XRD Peak Deconvolution to OriginPro Worksheet & Graph.")
"""

    # 24. Generate Classic OriginLab LabTalk Script (.ogs)
    labtalk_code = f"""// ==============================================================================
// OriginLab Native LabTalk Macro Script (.ogs)
// Compatible with all versions of OriginLab (Origin 8, 9, 2018 - 2024+)
// Instructions: In OriginLab, open Script Window (Alt+3 or Window -> Script Window),
// paste this script, select all and press Enter.
// ==============================================================================

// 1. Create a new workbook
newbook name:="XRD_Peak_Studio" sheet:=1;
page.title$ = "XRD Peak Deconvolution & Metrology";

// 2. Setup Columns & Units
wks.nCols = 5;
wks.col1.name$ = "TwoTheta";
wks.col1.unit$ = "deg";
wks.col1.type = 4; // X column

wks.col2.name$ = "Observed";
wks.col2.unit$ = "counts";

wks.col3.name$ = "Fit_Calc";
wks.col3.unit$ = "counts";

wks.col4.name$ = "Baseline";
wks.col4.unit$ = "counts";

wks.col5.name$ = "Residual";
wks.col5.unit$ = "counts";

// 3. Set Parameters in Project Variables
double c0 = {center:.4f};
double fw = {fwhm:.4f};
double ht = {height:.1f};
double eta = {eta:.3f};
double bg0 = {bg_const:.1f};
double bgs = {bg_slope:.3f};
double xmin = {x_min:.3f};
double xmax = {x_max:.3f};
int npts = {n_points};

// 4. Fill 2-Theta Grid
col(TwoTheta) = data(xmin, xmax, (xmax - xmin) / (npts - 1));

// 5. Fill Baseline & Pseudo-Voigt Fit Functions
double sig = fw / (2.0 * sqrt(2.0 * ln(2.0)));
double gam = fw / 2.0;

col(Baseline) = bg0 + bgs * (col(TwoTheta) - c0);
col(Fit_Calc) = col(Baseline) + ht * ((1 - eta) * exp(-0.5 * ((col(TwoTheta) - c0)/sig)^2) + eta / (1 + ((col(TwoTheta) - c0)/gam)^2));
col(Observed) = col(Fit_Calc);
col(Residual) = col(Observed) - col(Fit_Calc);

// 6. Plot Origin Graph
win -t plot origin;
layer.x.ticks = 3; // Inward ticks
layer.y.ticks = 3;
plotxy iy:=[XRD_Peak_Studio]1!(1,2) plot:=201; // Scatter
plotxy iy:=[XRD_Peak_Studio]1!(1,3) plot:=200; // Line Fit
plotxy iy:=[XRD_Peak_Studio]1!(1,4) plot:=200; // Baseline

label -xb "Diffraction Angle 2\\theta (\\+(o))";
label -yl "Intensity I (counts)";

type "OriginLab LabTalk XRD Data successfully generated!";
"""

    jupyter_notebook = generate_jupyter_notebook_json(python_code, title="OriginPro_XRD_FWHM_Deconvolution")

    return {
        'success': True,
        'image': f"data:image/png;base64,{base64_image}",
        'svg': svg_content,
        'python_code': python_code,
        'jupyter_notebook': jupyter_notebook,
        'originpro_script': originpro_code,
        'labtalk_script': labtalk_code,
        'csv_data': csv_data,
        'metrics': {
            'center': center,
            'observed_fwhm': fwhm,
            'instrumental_fwhm': inst_fwhm,
            'physical_fwhm': beta_phys,
            'crystallite_size_nm': crystallite_size_nm,
            'microstrain_pct': microstrain_pct,
            'eta': eta,
            'r_squared': r_squared,
            'r_wp': r_wp,
            'r_p': r_p,
            'gof': gof,
            'reduced_chi_sq': reduced_chi_sq,
            'durbin_watson': durbin_watson,
            'height': height,
            'total_area': total_area,
            'sub_areas': [{'label': sp['label'], 'area': sp['area'], 'area_fraction': sp['area_fraction']} for sp in sub_peaks_metrics],
            'sub_peaks': sub_peaks_metrics,
            'fit_errors': fit_errors,
            'is_auto_fit': is_auto_fit,
            'ka2_info': ka2_info
        }
    }


if __name__ == "__main__":
    if len(sys.argv) > 1:
        try:
            input_json = sys.argv[1]
            params = json.loads(input_json)
        except Exception:
            params = {}
    else:
        try:
            stdin_data = sys.stdin.read()
            params = json.loads(stdin_data) if stdin_data else {}
        except Exception:
            params = {}

    result = generate_origin_fwhm_plot(params)
    print(json.dumps(result))
